#include "d3dSeam.h"

#include "../../common/gfx/d3d9Backend.h"
#include "../../common/standalone.h"

#include <windows.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ---------------------------------------------------------------------------------------------------------------
// The driving engine's graphics seam - docs/driving-engine-plan.md section 6.1.
//
// WHERE THE SEAM IS, AND WHY IT IS NOT WHERE THE ACTION ENGINE'S IS.
//
// The action engine's seam sits above D3D8: Eurocom's own thin wrapper functions are reimplemented in C++, and
// each D3D8 call inside them goes either to the XBE's library (under CXBX) or to the native backend. That
// works there because those wrappers are a small, well-understood layer with good symbols.
//
// The driving engine's equivalent layer is EAGL, which is most of the binary, largely unnamed, and reaches
// D3D8 from everywhere - 108 entry points against the action engine's 41. Reimplementing enough of EAGL to
// cover them all before anything renders would be a very long time with nothing running. So this seam is at
// the library boundary instead: every D3D8 and XGRAPHC entry point is patched at its own address, and EAGL
// runs exactly as built. That is the same technique the plan prescribes for the DirectSound entry points the
// sound seam cannot cover from above (section 6.2), applied to graphics because the boundary is the same
// shape: the backend's API already mirrors D3D8 entry point for entry point.
//
// It is also what makes bring-up incremental. An entry point with no implementation yet gets a stub that
// reports itself, cleans up the caller's stack and returns zero, so one run names everything the game
// actually reaches rather than stopping at the first gap. The stack-argument size each stub needs comes from
// the table in d3d8Entries.inc, generated by tools/d3d8_entry_points.py from the binary itself.
//
// CALLING CONVENTIONS. Everything here is __stdcall unless the table says the function pops nothing while
// plainly taking arguments, which means they arrive in registers. D3DDevice_SetRenderState_Simple is the one
// of those so far - it writes ECX and EDX straight into the push buffer - and it is handled by a naked
// adapter below. The backend's functions are ordinary __cdecl, so each replacement is a __stdcall wrapper
// rather than the backend function itself: jumping a __stdcall call site into a __cdecl function would leave
// the arguments on the stack.
// ---------------------------------------------------------------------------------------------------------------

struct D3D8Entry {
    const char *name;
    unsigned    address;
    unsigned    stackBytes;   // what the original pops on return, so a stub can stand in for it
    void       *replacement;  // NULL until one is registered below
    unsigned    calls;        // stub calls only; what the periodic report prints
    bool        reported;
};

static D3D8Entry g_entries[] = {
#define D3D8_ENTRY(name, address, stack)        { #name, address, stack, NULL, 0, false },
#define D3D8_ENTRY_UNKNOWN_STACK(name, address) { #name, address, 0xffffffffu, NULL, 0, false },
#include "d3d8Entries.inc"
#undef D3D8_ENTRY
#undef D3D8_ENTRY_UNKNOWN_STACK
};

static const unsigned ENTRY_COUNT = sizeof(g_entries) / sizeof(g_entries[0]);

// ---------------------------------------------------------------------------------------------------------------
// The stub for entry points with no implementation yet.
//
// One trampoline per entry point, so that a single handler can still say which one it was reached through -
// the same arrangement as the loader's kernel import stubs (src/loader/kernel.cpp), and for the same reason.
// Each trampoline is "push index; jmp D3D8StubEntry", reached by a jump patched over the entry point, so on
// entry the stack is [esp] = index, [esp+4] = the caller's return address, then the arguments.
//
// Unlike the kernel stubs these return rather than stopping. A missing kernel import means the game is about
// to use something that does not exist; a missing D3D8 entry point usually means a piece of drawing does not
// happen, and carrying on names the next twenty as well as this one. Returning correctly is the whole trick:
// the handler hands back the argument size out of the table, and the epilogue pops exactly that much.
// ---------------------------------------------------------------------------------------------------------------

#pragma pack(push, 1)
struct StubTrampoline {
    uint8_t  pushOpcode;
    uint32_t index;
    uint8_t  jmpOpcode;
    int32_t  relativeTarget;
};
#pragma pack(pop)

static StubTrampoline *g_trampolines = NULL;

static unsigned __cdecl D3D8StubReport(unsigned index, uint32_t calledFrom) {
    if (index >= ENTRY_COUNT)
        return 0;

    D3D8Entry *entry = &g_entries[index];
    entry->calls++;
    if (!entry->reported) {
        entry->reported = true;
        printf("[d3dSeam] not implemented: %s, first called from 0x%08x\n", entry->name, calledFrom);
        fflush(stdout);
    }
    return entry->stackBytes == 0xffffffffu ? 0 : entry->stackBytes;
}

// Entered by a jmp from a trampoline. Returns zero, in EAX, having popped the caller's arguments.
static void __declspec(naked) D3D8StubEntry(void) {
    __asm {
        push [esp + 4]          // the caller's return address, for the report
        push [esp + 4]          // the index the trampoline pushed, now one slot further down
        call D3D8StubReport
        add  esp, 8             // __cdecl: ours to clean up. EAX is now the argument size
        add  esp, 4             // drop the index
        pop  edx                // the caller's return address
        add  esp, eax           // and the arguments, exactly as the original would have
        xor  eax, eax           // D3D8 entry points that return anything return an HRESULT or a pointer;
        jmp  edx                //   zero is success, or null, and either is the safer answer
    }
}

// ---------------------------------------------------------------------------------------------------------------
// The entry points that do have an implementation.
//
// Each is a __stdcall function with the original's signature, forwarding to the backend. Where the backend
// wants something in a different shape - a viewport as six numbers rather than a structure, a float where the
// stack holds a dword - the conversion happens here, so the backend stays free of Xbox-isms it does not need.
// ---------------------------------------------------------------------------------------------------------------

// The game's tick rate, as Timer_Init (0x0010ae50) left it: 50 on a PAL video mode, 60 on an NTSC one.
#define GameTimerFrequency (*(const uint32_t *)0x00242424u)

static uint32_t __stdcall Seam_Direct3D_CreateDevice(uint32_t adapter, uint32_t deviceType, void *focusWindow,
                                                     uint32_t behaviourFlags, void *presentationParameters,
                                                     void **returnedDevice) {
    // The backend paces Present to the refresh rate in the present parameters, standing in for the vertical
    // blank an Xbox Swap would have waited for. EAGL leaves that field zero unless the game asked for a
    // particular rate, which would mean no pacing at all - so where it is zero, the video mode's own rate is
    // what it means, and that is the rate Timer_Init already derived.
    uint32_t *parameters = (uint32_t *)presentationParameters;
    if (parameters != NULL && parameters[11] == 0 && GameTimerFrequency != 0) {
        parameters[11] = GameTimerFrequency;
        printf("[d3dSeam] no refresh rate in the present parameters; pacing to the game's %u Hz tick\n",
               GameTimerFrequency);
    }

    return D3D9_CreateDevice(adapter, deviceType, focusWindow, behaviourFlags,
                             parameters, returnedDevice);
}

static void __stdcall Seam_D3D_SetPushBufferSize(uint32_t pushBufferSize, uint32_t kickOffSize) {
    D3D9_SetPushBufferSize(pushBufferSize, kickOffSize);
}

static void __stdcall Seam_D3DDevice_Clear(uint32_t count, void *rects, uint32_t flags, uint32_t colour,
                                           uint32_t z, uint32_t stencil) {
    // Z arrives as the raw bits of a float, pushed like any other dword.
    float depth;
    memcpy(&depth, &z, sizeof(depth));
    D3D9_Clear(count, rects, flags, colour, depth, stencil);
}

static void __stdcall Seam_D3DDevice_Swap(uint32_t flags) {
    D3D9_Swap(flags);
}

static uint32_t *__stdcall Seam_D3DDevice_GetBackBuffer2(int32_t index) {
    return D3D9_GetBackBuffer2(index);
}

static void *__stdcall Seam_D3DDevice_GetDepthStencilSurface2(void) {
    return D3D9_GetDepthStencilSurface2();
}

static void *__stdcall Seam_D3DTexture_GetSurfaceLevel2(void *texture, uint32_t level) {
    return D3D9_GetSurfaceLevel2(texture, level);
}

static void __stdcall Seam_D3DDevice_SetShaderConstantMode(uint32_t mode) {
    D3D9_SetShaderConstantMode(mode);
}

static void __stdcall Seam_D3DDevice_SetRenderState_CullMode(int cullMode) {
    D3D9_SetCullMode(cullMode);
}

static void __stdcall Seam_D3DDevice_SetRenderState_ZEnable(uint32_t value) {
    D3D9_SetZEnable(value);
}

static void __stdcall Seam_D3DDevice_SetRenderState_FogColor(uint32_t colour) {
    D3D9_SetFogColor(colour);
}

static void __stdcall Seam_D3DDevice_SetTexture(uint32_t stage, void *texture) {
    D3D9_SetTexture(stage, texture);
}

static void __stdcall Seam_D3DResource_Register(void *resource, uint32_t data) {
    D3D9_ResourceRegister(resource, data);
}

static uint32_t __stdcall Seam_D3DResource_Release(void *resource) {
    return D3D9_ResourceRelease(resource);
}

static void __stdcall Seam_D3DResource_BlockUntilNotBusy(void *resource) {
    D3D9_BlockUntilNotBusy(resource);
}

static void __stdcall Seam_XGSetTextureHeader(uint32_t width, uint32_t height, uint32_t levels, uint32_t usage,
                                              int format, uint32_t pool, void *texture, uint32_t data,
                                              uint32_t pitch) {
    D3D9_XGSetTextureHeader(width, height, levels, usage, format, pool, texture, data, pitch);
}

// The Xbox D3DVIEWPORT8, as the entry point receives it.
struct XboxViewport { uint32_t X, Y, Width, Height; float MinZ, MaxZ; };

static void __stdcall Seam_D3DDevice_SetViewport(const XboxViewport *viewport) {
    if (viewport == NULL)
        return;
    D3D9_SetViewport(viewport->X, viewport->Y, viewport->Width, viewport->Height,
                     viewport->MinZ, viewport->MaxZ);
}

// The Xbox D3DSURFACE_DESC, which is not the PC one: there is no Size field between Pool and
// MultiSampleType, so Width and Height sit at +0x14 and +0x18. Read off the original Get2DSurfaceDesc
// (0x0016e390), which writes exactly these seven words - and getting it wrong is not academic, since the
// first version of this file had the PC layout and EAGL built its backbuffer texture header out of the
// wrong two words.
struct XboxSurfaceDesc {
    uint32_t Format, Type, Usage, Pool, MultiSampleType, Width, Height;
};

#define XBOX_MULTISAMPLE_NONE 0x11u

static void FillSurfaceDesc(void *surface, XboxSurfaceDesc *desc) {
    if (desc == NULL)
        return;
    memset(desc, 0, sizeof(*desc));
    desc->Type = 1;                              // D3DRTYPE_SURFACE
    desc->MultiSampleType = XBOX_MULTISAMPLE_NONE;
    D3D9_GetSurfaceDesc(surface, &desc->Format, &desc->Width, &desc->Height);
}

static void __stdcall Seam_D3DSurface_GetDesc(void *surface, XboxSurfaceDesc *desc) {
    FillSurfaceDesc(surface, desc);
}

// The same thing one level down, and the one the rest of EAGL calls directly. The middle argument is the mip
// level, which only matters for textures; every caller here passes zero.
static void __stdcall Seam_Get2DSurfaceDesc(void *surface, uint32_t level, XboxSurfaceDesc *desc) {
    (void)level;
    FillSurfaceDesc(surface, desc);
}

// The gamma ramp the game reads at startup and puts back later. There is no Xbox ramp to read, so hand back
// the identity - which is what is in effect anyway, since the backend does not touch the host's gamma.
struct XboxGammaRamp { uint8_t red[256], green[256], blue[256]; };

static void __stdcall Seam_D3DDevice_GetGammaRamp(XboxGammaRamp *ramp) {
    if (ramp == NULL)
        return;
    for (int i = 0; i < 256; i++)
        ramp->red[i] = ramp->green[i] = ramp->blue[i] = (uint8_t)i;
}

// Memory tiling. The nv2a can mark regions of memory as tiled so that framebuffer access is faster; D3D9
// resources have no such notion, and the game only reads the tiles back in order to restore them, so
// reporting them as unset and accepting whatever is set is both truthful and inert.
struct XboxTile { uint32_t Flags, Size, Pitch, ZStartTag, ZOffset, ZEndTag; };

static void __stdcall Seam_D3DDevice_GetTile(uint32_t index, XboxTile *tile) {
    (void)index;
    if (tile != NULL)
        memset(tile, 0, sizeof(*tile));
}

static void __stdcall Seam_D3DDevice_SetTile(uint32_t index, const XboxTile *tile) {
    (void)index; (void)tile;
}

// The nv2a's screen-space offset is the sub-pixel origin of rasterisation. The backend applies the pixel
// centre offset D3D9 needs in its own vertex path, so taking this one as well would shift everything twice.
static void __stdcall Seam_D3DDevice_SetScreenSpaceOffset(float x, float y) {
    (void)x; (void)y;
}

// Stencil, and the shadow-buffer comparison that goes with it. The backend has no stencil support yet - it
// creates a depth-stencil buffer but never sets a stencil state - so these are accepted and dropped rather
// than reported on every frame. They are on the list for when shadows are looked at.
static void __stdcall Seam_D3DDevice_SetRenderState_StencilEnable(uint32_t value) {
    (void)value;
}

static void __stdcall Seam_D3DDevice_SetRenderState_StencilFail(uint32_t value) {
    (void)value;
}

static void __stdcall Seam_D3DDevice_SetRenderState_ShadowFunc(uint32_t value) {
    (void)value;
}

static uint32_t __stdcall Seam_D3DDevice_CreateVertexShader(const void *declaration, const void *function,
                                                            void **handle, uint32_t usage) {
    return D3D9_CreateVertexShader(declaration, function, handle, usage);
}

// D3DDevice_SetRenderState_Simple takes the NV2A method in ECX and the value in EDX and writes the pair
// straight into the push buffer - it pops nothing, which is how the generated table spots it. Confirmed by
// disassembly at 0x001673e0, the same arrangement the action engine found at its own address.
static void __declspec(naked) Seam_D3DDevice_SetRenderState_Simple(void) {
    __asm {
        push edx                        // value
        push ecx                        // method
        call D3D9_SetRenderStateSimple
        add  esp, 8                     // __cdecl
        ret
    }
}

// Name, not address: the addresses live in the generated table, and a name that is not in it is a mistake
// worth hearing about rather than a patch that silently lands nowhere.
static const struct { const char *name; void *replacement; } g_replacements[] = {
    { "Direct3D_CreateDevice",                (void *)Seam_Direct3D_CreateDevice },
    { "D3D_SetPushBufferSize",                (void *)Seam_D3D_SetPushBufferSize },
    { "D3DDevice_Clear",                      (void *)Seam_D3DDevice_Clear },
    { "D3DDevice_Swap",                       (void *)Seam_D3DDevice_Swap },
    { "D3DDevice_GetBackBuffer2",             (void *)Seam_D3DDevice_GetBackBuffer2 },
    { "D3DDevice_GetDepthStencilSurface2",    (void *)Seam_D3DDevice_GetDepthStencilSurface2 },
    { "D3DTexture_GetSurfaceLevel2",          (void *)Seam_D3DTexture_GetSurfaceLevel2 },
    { "D3DDevice_SetShaderConstantMode",      (void *)Seam_D3DDevice_SetShaderConstantMode },
    { "D3DDevice_SetRenderState_CullMode",    (void *)Seam_D3DDevice_SetRenderState_CullMode },
    { "D3DDevice_SetRenderState_ZEnable",     (void *)Seam_D3DDevice_SetRenderState_ZEnable },
    { "D3DDevice_SetRenderState_FogColor",    (void *)Seam_D3DDevice_SetRenderState_FogColor },
    { "D3DDevice_SetRenderState_Simple",      (void *)Seam_D3DDevice_SetRenderState_Simple },
    { "D3DDevice_SetTexture",                 (void *)Seam_D3DDevice_SetTexture },
    { "D3DDevice_SetViewport",                (void *)Seam_D3DDevice_SetViewport },
    { "D3DSurface_GetDesc",                   (void *)Seam_D3DSurface_GetDesc },
    { "Get2DSurfaceDesc",                     (void *)Seam_Get2DSurfaceDesc },
    { "D3DDevice_GetGammaRamp",               (void *)Seam_D3DDevice_GetGammaRamp },
    { "D3DDevice_GetTile",                    (void *)Seam_D3DDevice_GetTile },
    { "D3DDevice_SetTile",                    (void *)Seam_D3DDevice_SetTile },
    { "D3DDevice_SetScreenSpaceOffset",       (void *)Seam_D3DDevice_SetScreenSpaceOffset },
    { "D3DDevice_SetRenderState_StencilEnable", (void *)Seam_D3DDevice_SetRenderState_StencilEnable },
    { "D3DDevice_SetRenderState_StencilFail", (void *)Seam_D3DDevice_SetRenderState_StencilFail },
    { "D3DDevice_SetRenderState_ShadowFunc",  (void *)Seam_D3DDevice_SetRenderState_ShadowFunc },
    { "D3DDevice_CreateVertexShader",         (void *)Seam_D3DDevice_CreateVertexShader },
    { "D3DResource_Register",                 (void *)Seam_D3DResource_Register },
    { "D3DResource_Release",                  (void *)Seam_D3DResource_Release },
    { "D3DResource_BlockUntilNotBusy",        (void *)Seam_D3DResource_BlockUntilNotBusy },
    { "XGSetTextureHeader",                   (void *)Seam_XGSetTextureHeader },
};

// ---------------------------------------------------------------------------------------------------------------
// Installing it.
// ---------------------------------------------------------------------------------------------------------------

static void WriteJump(unsigned address, const void *target) {
    unsigned char *site = (unsigned char *)address;
    DWORD previous = 0;
    if (!VirtualProtect(site, 5, PAGE_EXECUTE_READWRITE, &previous)) {
        printf("[d3dSeam] could not make 0x%08x writable (error %lu)\n", address, GetLastError());
        return;
    }
    site[0] = 0xE9;                                             // jmp rel32
    *(int *)(site + 1) = (int)((const unsigned char *)target - (site + 5));
}

// Every entry with this name, because a few names appear twice in the binary (D3DDevice_End,
// Get2DSurfaceDesc and D3D_KickOffAndWaitForIdle each have an inlined copy as well as the library one).
// Patching both copies is what the caller means; patching the first one found is a coin toss.
static int ReplaceByName(const char *name, void *replacement) {
    int found = 0;
    for (unsigned i = 0; i < ENTRY_COUNT; i++) {
        if (strcmp(g_entries[i].name, name) == 0) {
            g_entries[i].replacement = replacement;
            found++;
        }
    }
    return found;
}

// Printed alongside the backend's frame timing, through GfxHost_ReportPeriodic - see gfx/backendHost.cpp.
// Only entry points that have actually been reached appear, which is the list that decides what to write
// next.
void D3dSeam_ReportMissing(void) {
    unsigned reached = 0;
    for (unsigned i = 0; i < ENTRY_COUNT; i++)
        reached += (g_entries[i].calls != 0) ? 1 : 0;
    if (reached == 0)
        return;

    printf("[d3dSeam] %u unimplemented entry points reached so far:\n", reached);
    for (unsigned i = 0; i < ENTRY_COUNT; i++) {
        if (g_entries[i].calls != 0)
            printf("[d3dSeam]   %-44s %u\n", g_entries[i].name, g_entries[i].calls);
    }
    fflush(stdout);
}

void Inject_D3dSeam(void) {
    // Under CXBX the D3D8 library is already replaced by CXBX's HLE, which owns the device; a second backend
    // patched over the same entry points would be two renderers fighting over one window.
    if (!Xbox_RunningStandalone())
        return;

    for (size_t i = 0; i < sizeof(g_replacements) / sizeof(g_replacements[0]); i++) {
        if (ReplaceByName(g_replacements[i].name, g_replacements[i].replacement) == 0)
            printf("[d3dSeam] no entry point called %s - has the table been regenerated?\n",
                   g_replacements[i].name);
    }

    g_trampolines = (StubTrampoline *)VirtualAlloc(NULL, ENTRY_COUNT * sizeof(StubTrampoline),
                                                   MEM_RESERVE | MEM_COMMIT, PAGE_EXECUTE_READWRITE);
    if (g_trampolines == NULL) {
        printf("[d3dSeam] could not allocate the stub trampolines (error %lu)\n", GetLastError());
        return;
    }

    unsigned implemented = 0;
    for (unsigned i = 0; i < ENTRY_COUNT; i++) {
        D3D8Entry *entry = &g_entries[i];

        if (entry->replacement != NULL) {
            WriteJump(entry->address, entry->replacement);
            implemented++;
            continue;
        }

        StubTrampoline *t = &g_trampolines[i];
        t->pushOpcode = 0x68;                 // push imm32
        t->index = i;
        t->jmpOpcode = 0xE9;                  // jmp rel32, measured from the end of this instruction
        t->relativeTarget = (int32_t)((const uint8_t *)D3D8StubEntry - ((uint8_t *)&t->relativeTarget + 4));
        WriteJump(entry->address, t);
    }

    FlushInstructionCache(GetCurrentProcess(), g_trampolines, ENTRY_COUNT * sizeof(StubTrampoline));
    printf("[d3dSeam] %u D3D8 entry points patched, %u of them implemented\n", ENTRY_COUNT, implemented);
    fflush(stdout);
}
