#ifndef DRIVING_PHYSICS_RIGIDBODY_H_
#define DRIVING_PHYSICS_RIGIDBODY_H_

#include <stddef.h>
#include <stdint.h>

#include "PhysicsObject.h"
#include "../../common/xbeOverload.h"   // XbeVirtual
#include "../../helpers.h"
#include "../autogenerated_layouts.h"   // MATRIX4
#include "../data/CoordConvert.h"       // Coord3, Coord4
#include "../engine/OBB.h"

// ---------------------------------------------------------------------------------------------------------------
// RigidBody (0x80 bytes, the Simulation's array): the full rigid-body simulation of a physics object - momentum
// and angular momentum integrated from the forces and torques resolved on it each step, the orientation as a
// quaternion, levers (the points it rests on: a car's wheels or the box's corners) against the ground, and
// sleeping. Its larger working state is a RigidBodyInfo from the Simulation's pool.
//
// The methods are in four files: RigidBody.cpp (the core), RigidBodyBasics.cpp (the small methods),
// RigidBodyResolve.cpp (collision response) and RigidBodyCollide.cpp (collision detection).
// ---------------------------------------------------------------------------------------------------------------

class WWorldPos;

constexpr int kMaxLevers = 16;
constexpr int kBoxCorners = 8;

// A body's working state (0x500 bytes): Simulation::GetRigidBodyInfo hands the constructor one by the body's owner
// index, which clears it.
struct RigidBodyInfo {
    MATRIX4 orientation;                    // +0x000 the quaternion as a matrix: body to world
    MATRIX4 worldInverseInertia;            // +0x040 the inverse inertia tensor in the world's frame
    Coord4 levers[kMaxLevers];              // +0x080 in the body's frame
    Coord4 worldLevers[kMaxLevers];         // +0x180 rotated into the world's frame
    Coord4 corners[2][kBoxCorners];         // +0x280 the box's corners in the world's frame, alternate steps
                                            //        writing alternate halves (cornerBank)
    WWorldPos *leverPositions[kMaxLevers];  // +0x380 each lever's place on the ground
    Coord4 leverGround[kMaxLevers];         // +0x3c0 the ground under each lever: its normal, w the height above it
    Coord4 halfExtents;                     // +0x4c0
    float unknown4d0;
    float groundFriction;                   // +0x4d4 mass / 0x1c36d0's constant * GROUND_FRICTION_COEFF
    WWorldPos *worldPosition;               // +0x4d8 the owner's
    int8_t leverCount;                      // +0x4dc
    uint8_t cornerBank;                     // +0x4dd 0 or 1: the half of `corners` last written
    uint16_t unknown4de;                    // +0x4de counts steps up to 0xffff; 0xffff at construction and reset
    Coord4 ground;                          // +0x4e0 the ground under the centre: its normal, w the height
    int32_t zone[3];                        // +0x4f0 the position's cell (UpdateZonalInfo)
    uint8_t unknown4fc;
    uint8_t unknown4fd;                     // +0x4fd set by GenerateImpulse
    uint8_t unknown4fe;                     // +0x4fe cleared each step, after being copied to unknown4ff
    uint8_t unknown4ff;
};
static_assert(sizeof(RigidBodyInfo) == 0x500, "RigidBodyInfo is 0x500 bytes");
static_assert(offsetof(RigidBodyInfo, levers) == 0x080 && offsetof(RigidBodyInfo, corners) == 0x280 &&
              offsetof(RigidBodyInfo, leverPositions) == 0x380 && offsetof(RigidBodyInfo, leverGround) == 0x3c0 &&
              offsetof(RigidBodyInfo, halfExtents) == 0x4c0 && offsetof(RigidBodyInfo, leverCount) == 0x4dc &&
              offsetof(RigidBodyInfo, ground) == 0x4e0 && offsetof(RigidBodyInfo, zone) == 0x4f0,
              "RigidBodyInfo layout");

// The argument record CollideWithGround hands ResolveLeverForces (0x10 bytes; the names are ours)
struct LeverContacts {
    float unknown00;
    float friction;                         // +0x04 RigidBodyInfo::groundFriction
    float unknown08;                        // +0x08 RigidBodyInfo::unknown4d0
    int32_t count;                          // +0x0c the levers in contact
};
static_assert(sizeof(LeverContacts) == 0x10, "LeverContacts is 16 bytes");

struct RigidBody {
    enum SleepState : uint8_t {
        kAsleep = 1,                        // ForceToSleep's
        kAwake = 2,                         // set by any force or torque resolved on it
        kFrozen = 3,                        // forces and torques are ignored
    };

    enum Flag : uint32_t {
        kFlag0 = 0x1,                       // set at construction and reset for kinds 1 and 2
        kFlag1 = 0x2,                       // the constructor's last argument; cleared by a force
    };

    Coord4 orientation;                     // +0x00 a quaternion
    Coord3 position;                        // +0x10
    float inverseInertiaX;                  // +0x1c the inverse inertia tensor's diagonal in the body's frame
    Coord3 velocity;                        // +0x20
    float inverseInertiaY;                  // +0x2c
    Coord3 angularVelocity;                 // +0x30
    float inverseInertiaZ;                  // +0x3c
    Coord3 momentum;                        // +0x40
    float mass;                             // +0x4c
    Coord3 angularMomentum;                 // +0x50
    RigidBodyInfo *info;                    // +0x5c
    Coord3 force;                           // +0x60 resolved this step
    uint8_t groundContacts;                 // +0x6c the levers CollideWithGround found on the ground
    int8_t kind;                            // +0x6d 1 and 2 set kFlag0; below 4 the owner's virtual methods are consulted
    uint8_t sleepState;                     // +0x6e SleepState
    int8_t ownerIndex;                      // +0x6f the owner's place in the Simulation's tables
    Coord3 torque;                          // +0x70 resolved this step
    // The bounding radius (the half extents' length, set at construction), whose two low bits the code then uses
    // as flags (Flag)
    union {
        float radius;
        uint32_t flags;
    };                                      // +0x7c

    // ---- RigidBody.cpp
    // RigidBody::RigidBody (0x000b0b20)
    RigidBody* Construct(int8_t ownerIndex, int8_t kind, const Coord3 *position, const Coord3 *velocity,
                         const Coord3 *angularVelocity, const MATRIX4 *orientation, float mass,
                         const Coord3 *inverseInertia, const Coord4 *halfExtents, PhysicsObject *owner,
                         bool moving, bool flag1);
    void Destruct();                                                                            // 0x000adc80
    void ResetObject(const MATRIX4 *orientation, const Coord3 *position);                      // 0x000adcd0
    void ApplyInitialForcesAndTorques();                                                        // 0x000ade40
    void ResolveLeverForces(const LeverContacts *contacts, const Coord4 *levers, const Coord4 *grounds,
                            const MATRIX4 *worldInverseInertia);                                // 0x000ae150
    void CollideWithGround();                                                                   // 0x000ae4c0
    static void ModifyLevers(RigidBody *a, RigidBody *b, Coord4 *leverA, Coord4 *leverB, const Coord4 *point,
                             Coord4 *direction, bool modify);                                    // 0x000ae830
    static void ScaleObjObjForces(RigidBody *a, RigidBody *b, Coord4 *forceA, Coord4 *forceB, float limit,
                                  float scale, float boost);                                     // 0x000aea40
    void ControlSleep();                                                                        // 0x000b09d0
    void UpdatePositionAndOrientation(float unused);                                            // 0x000b0ec0
    static void ResetRigidBodySPThunk();    // a second entry to ResetRigidBodySP (a jump to it) // 0x000b2810

    // ---- RigidBodyBasics.cpp
    static void InitRigidBodySystem();                                                          // 0x000acde0
    static void ResetRigidBodySP();                                                             // 0x000ad0e0
    PhysicsObject* GetOwner();                                                                  // 0x000ad100
    double GetOrientToGround();                                                                 // 0x000ad110
    void ApplyAngularDamping();                                                                 // 0x000ad130
    void ApplyHeavyFriction();                                                                  // 0x000ad170
    void ModifyAngularMomentum(Coord3 *localDelta);     // carried into the world's frame in place // 0x000ad1a0
    Coord3* GetLocalAngularMomentum(Coord3 *result);                                            // 0x000ad1d0
    Coord3* GetLocalVelocity(Coord3 *result);                                                   // 0x000ad220
    Coord3* GetLocalAngularVelocity(Coord3 *result);                                            // 0x000ad270
    void ConvertWorldToLocal(Coord4 *v);    // x, y and z                                       // 0x000ad2c0
    void ConvertLocalToWorld(Coord3 *v);                                                        // 0x000ad2f0
    void SetAngularMomentum(const Coord3 *local);                                              // 0x000ad310
    void SetOrientation(const Coord4 *quaternion);                                              // 0x000ad330
    void ResolveForce(const Coord3 *force);                                                     // 0x000ad3f0
    void ResolveTorque(const Coord3 *torque);                                                   // 0x000ad420
    void ResolveMassScaledForce4(const Coord4 *acceleration);   // 0x000ad440 (FUN_000ad440; the name is ours)
    void ResolveMassScaledTorque4(const Coord4 *acceleration);                                  // 0x000ad470
    void UpdateZonalInfo();                                                                     // 0x000ad4a0
    void CalculateAndApplyWorldDamage(const Coord4 *direction, float force);                   // 0x000ad520
    void ForceToSleep();                                                                        // 0x000ad600
    bool TempGetHeightInformation(bool unused, const Coord3 *point, Coord4 *ground,
                                  WWorldPos *worldPosition);                                    // 0x000ad690
    void InitLevers(PhysicsObject *owner, const Coord4 *halfExtents);                           // 0x000ad840

    // ---- RigidBodyResolve.cpp
    // `normal` is rewritten when only one of the bodies is a vehicle (ModifyLevers)
    bool ResolveCollision(RigidBody *a, RigidBody *b, Coord4 *normal, const Coord4 *point, float depth,
                          struct CollisionImpact *impact);                                       // 0x000aec10
    void GenerateImpulse(struct CollisionImpact *impact, const Coord4 *normal, const Coord4 *point, float push,
                         bool fromWorld, uint16_t tag, float speedScale);                        // 0x000afdb0

    // ---- RigidBodyCollide.cpp
    bool ResolveWorldOBBCollision(const Coord4 *normal, const Coord4 *point, float depth,
                                  struct CollisionImpact *impact, const Coord3 *objectVelocity,
                                  float forceScale);                                             // 0x000af960
    void CollideWithObject(int index, int unknown);                                             // 0x000b0510
    void CollideWithWorld();                                                                    // 0x000b1420
};
static_assert(sizeof(RigidBody) == 0x80, "a rigid body is 128 bytes");
static_assert(offsetof(RigidBody, position) == 0x10 && offsetof(RigidBody, mass) == 0x4c &&
              offsetof(RigidBody, info) == 0x5c && offsetof(RigidBody, groundContacts) == 0x6c &&
              offsetof(RigidBody, ownerIndex) == 0x6f && offsetof(RigidBody, torque) == 0x70 &&
              offsetof(RigidBody, flags) == 0x7c, "rigid body layout");

// std::vector's _Xlen: throws std::length_error("vector<T> too long") (FUN_000b13a0; the name is ours)
void VectorXlen();

// What PVehicle::GetPhysics answers (PBondCar's tuning record): only the fields ported code reads
struct RigidVehiclePhysics {
    uint8_t unknown00[0x60];
    float unknown60;                        // +0x60 1.5 from InitLevers when the body has no collision geometry
    uint8_t unknown64[0x58];
    int32_t unknownBC;                      // +0xbc non-zero: the targeting aims at the screen's centre
    int32_t unknownC0;                      // +0xc0 1: ApplyInitialForcesAndTorques adds no gravity
    int32_t unknownC4;                      // +0xc4 non-zero: CollideWithGround does nothing
    int32_t unknownC8;                      // +0xc8 non-zero: the rear levers on the centre line (InitLevers), the
                                            //       second restitution rate (ResolveLeverForces)
    int32_t unknownCC;                      // +0xcc non-zero: TempGetHeightInformation adds 10 to the height;
                                            //       ApplyInitialForcesAndTorques' drag
};
static_assert(offsetof(RigidVehiclePhysics, unknownBC) == 0xbc && offsetof(RigidVehiclePhysics, unknownC0) == 0xc0 &&
              offsetof(RigidVehiclePhysics, unknownCC) == 0xcc, "vehicle physics layout");

// What PVehicle::GetCarControl copies out (0x20 bytes)
struct CarControl {
    float unknown00;
    uint8_t unknown04[0x1c];
};
static_assert(sizeof(CarControl) == 0x20, "a car control is 32 bytes");

// The owner of a body of kind below 4: a vehicle, whose vtable (PVehicle's, 0x0018fa00) has these virtual methods
// past PhysicsObject's seven (the names are PBondCar's overrides', its vtable at 0x0018f580)
struct RigidVehicle : PhysicsObject {
    typedef void *(RigidVehicle::*GetSplinePathMethod)();
    typedef const char *(RigidVehicle::*GetCarTypeMethod)();
    typedef int (RigidVehicle::*GetCarClassMethod)();
    typedef CarControl *(RigidVehicle::*GetCarControlMethod)(CarControl *result);
    typedef int (RigidVehicle::*GetNumWheelsOnGroundMethod)();
    typedef void (RigidVehicle::*AddDamageByPlayerMethod)(float damage);
    typedef bool (RigidVehicle::*GetDamageByPlayerTimerMethod)();
    typedef RigidVehiclePhysics *(RigidVehicle::*GetPhysicsMethod)();
    typedef bool (RigidVehicle::*IsReversingMethod)();
    typedef void (RigidVehicle::*SetAgainstWallFlagMethod)(bool against);
    typedef bool (RigidVehicle::*GetIsInTwoWheelModeMethod)();
    typedef bool (RigidVehicle::*GetWasInAirMethod)();
    typedef void (RigidVehicle::*SetWasInAirMethod)(bool wasInAir);

    void *GetSplinePath() { return (this->*XbeVirtual<GetSplinePathMethod>(this, 0x2c / 4))(); }
    const char *GetCarType() { return (this->*XbeVirtual<GetCarTypeMethod>(this, 0x3c / 4))(); }
    int GetCarClass() { return (this->*XbeVirtual<GetCarClassMethod>(this, 0x48 / 4))(); }
    // The control is returned by value: the caller's record, filled and answered
    CarControl *GetCarControl(CarControl *result) {
        return (this->*XbeVirtual<GetCarControlMethod>(this, 0x94 / 4))(result);
    }
    int GetNumWheelsOnGround() { return (this->*XbeVirtual<GetNumWheelsOnGroundMethod>(this, 0xc0 / 4))(); }
    void AddDamageByPlayer(float damage) { (this->*XbeVirtual<AddDamageByPlayerMethod>(this, 0xd0 / 4))(damage); }
    bool GetDamageByPlayerTimer() { return (this->*XbeVirtual<GetDamageByPlayerTimerMethod>(this, 0xd4 / 4))(); }
    RigidVehiclePhysics *GetPhysics() { return (this->*XbeVirtual<GetPhysicsMethod>(this, 0xe4 / 4))(); }
    bool IsReversing() { return (this->*XbeVirtual<IsReversingMethod>(this, 0xe8 / 4))(); }
    void SetAgainstWallFlag(bool against) {
        (this->*XbeVirtual<SetAgainstWallFlagMethod>(this, 0xec / 4))(against);
    }
    bool GetIsInTwoWheelMode() { return (this->*XbeVirtual<GetIsInTwoWheelModeMethod>(this, 0x110 / 4))(); }
    bool GetWasInAir() { return (this->*XbeVirtual<GetWasInAirMethod>(this, 0x118 / 4))(); }
    void SetWasInAir(bool wasInAir) { (this->*XbeVirtual<SetWasInAirMethod>(this, 0x11c / 4))(wasInAir); }
};

// The Simulation's scratch pad (RigidScratchPad): only the fields the rigid bodies use
struct RigidScratchPadFields {
    Coord4 contactLevers[kMaxLevers];       // +0x000 CollideWithGround's levers on the ground, in the world's frame
    Coord4 contactGrounds[kMaxLevers];      // +0x100 and the ground under each
    OBB body;                               // +0x200 the colliding body's box (CollideWithObject, CollideWithWorld)
    OBB other;                              // +0x2b0 the other body's
    uint8_t unknown360[0x30];
    int32_t unknown390;                     // +0x390 cleared by ResetRigidBodySP
    uint8_t unknown394[4];
    bool bodyBoxValid;                      // +0x398 `body` is this body's box (cleared by each test, then built
                                            //        once)
    uint8_t unknown399;                     // +0x399 cleared by ResetRigidBodySP
};
static_assert(offsetof(RigidScratchPadFields, contactGrounds) == 0x100 &&
              offsetof(RigidScratchPadFields, body) == 0x200 && offsetof(RigidScratchPadFields, other) == 0x2b0 &&
              offsetof(RigidScratchPadFields, unknown390) == 0x390 &&
              offsetof(RigidScratchPadFields, bodyBoxValid) == 0x398 &&
              offsetof(RigidScratchPadFields, unknown399) == 0x399, "scratch pad layout");

// The shared rigid-body globals. The tuning values are loaded by InitRigidBodySystem from "Physics:Rigid" (each
// named as its attribute); the names of the tuning block's floats with no attribute are ours.
#define RigidScratchPad (*(RigidScratchPadFields **)0x00233fac)    // Simulation::GetScratchPadFreeZone's, set by
                                                                    // InitRigidBodySystem
#define RigidUnderwater BOOL8_AT(0x00233fb0)            // the track's name holds "uw_"
#define RigidPlayerGravity FLOAT_AT(0x00233fb8)         // BODGE_PLAYER_GRAVITY at start; -34 for "jungle_truck"
#define RigidGroundRestitutionRate FLOAT_AT(0x00233fbc) // GROUND_RESTITUTION / MICRO_THRESHOLD (static initialiser)
#define RigidRestitutionRateC8 FLOAT_AT(0x00233fc0)     // 0x001c8f3c's value / MICRO_THRESHOLD (static initialiser)
#define RigidBuildingRestitutionRate FLOAT_AT(0x00233fc4) // BUILDING_COEFF_RESTITUTION / BUILDING_MICRO_THRESHOLD
#define DamageSourceSig ((const uint32_t *)0x00233fe8)  // the source world and object damage name (the name is ours)
#define PhysicsObjects ((PhysicsObject **)0x002342a0)   // [64] by owner index (the Simulation's)
#define RigidVehicles ((RigidVehicle **)0x002342a0)     // the same, for owners of kind below 4
#define SimpleBodyOwners ((PhysicsObject **)0x002343a0) // [96] the simple bodies' owners, by slot (NULL: not in use)
#define SimStepsPerSecond I32_AT(0x00234e2c)            // the Simulation's steps a second
#define Rigid_GRAVITY FLOAT_AT(0x001c8f2c)
#define Rigid_BODGE_PLAYER_GRAVITY FLOAT_AT(0x001c8f30)
#define Rigid_MICRO_THRESHOLD FLOAT_AT(0x001c8f34)
#define Rigid_GROUND_RESTITUTION FLOAT_AT(0x001c8f38)
#define Rigid_GROUND_FRICTION_COEFF FLOAT_AT(0x001c8f40)
#define Rigid_NATURAL_ANGULAR_DAMPING FLOAT_AT(0x001c8f44)
#define Rigid_SLEEP_VEL FLOAT_AT(0x001c8f48)
#define Rigid_AM_LIMIT FLOAT_AT(0x001c8f4c)
#define Rigid_M_LIMIT FLOAT_AT(0x001c8f50)
#define Rigid_SPEED_FORCE_LIMIT FLOAT_AT(0x001c8f54)
#define Rigid_SPEED_SCALE FLOAT_AT(0x001c8f5c)
#define Rigid_DEPTH_FORCE_SCALE FLOAT_AT(0x001c8f60)
#define Rigid_TOTAL_FORCE_LIMIT FLOAT_AT(0x001c8f64)
#define Rigid_ForceCapDivisor FLOAT_AT(0x001c8f68)      // ResolveCollision's
#define Rigid_ForceCapFloor FLOAT_AT(0x001c8f6c)        // ResolveCollision's and ResolveWorldOBBCollision's
#define Rigid_BoxSpeedScale FLOAT_AT(0x001c8f70)        // ResolveWorldOBBCollision's
#define Rigid_BoxDepthScale FLOAT_AT(0x001c8f74)
#define Rigid_BoxForceCapScale FLOAT_AT(0x001c8f78)
#define Rigid_BUILDING_MICRO_THRESHOLD FLOAT_AT(0x001c8f7c)
#define Rigid_BUILDING_COEFF_RESTITUTION FLOAT_AT(0x001c8f80)
#define Rigid_BUILDING_FRICTION_FACTOR FLOAT_AT(0x001c8f84)
#define Rigid_BUILDING_FRICTION_LIMIT FLOAT_AT(0x001c8f88)
#define Rigid_BUILDING_COLLIDE_COG_SCALE FLOAT_AT(0x001c8f8c)
#define Rigid_BUILDING_FORCE_LIMIT FLOAT_AT(0x001c8f90)
#define Rigid_CornerLift FLOAT_AT(0x001c8f94)           // CollideWithWorld's
#define Rigid_PF_SCALE FLOAT_AT(0x001c8f98)
#define Rigid_WorldDamageFactor FLOAT_AT(0x001c8f9c)    // 0.35: ApplyDamage's fourth argument for world damage
#define Rigid_CAR_COLLIDE_COG_SCALE FLOAT_AT(0x001c8fa0)
#define Rigid_UnknownCogScale FLOAT_AT(0x001c8fa4)      // ModifyLevers' scale for bodies of kinds other than 1
#define Rigid_ObjectDamageFactor FLOAT_AT(0x001c8fa8)   // ApplyDamage's fourth argument for a body's damage
#define Rigid_DamageScale FLOAT_AT(0x001c8fac)          // 5: world and object damage (read, never written)
#define Rigid_VehicleWorldDamageScale FLOAT_AT(0x001c8fb0)  // 6: a vehicle's world damage (read, never written)

#endif // DRIVING_PHYSICS_RIGIDBODY_H_
