#ifndef DRIVING_PHYSICS_SIMPLERIGIDBODY_H_
#define DRIVING_PHYSICS_SIMPLERIGIDBODY_H_

#include <stddef.h>
#include <stdint.h>

#include "../autogenerated_layouts.h"   // MATRIX4
#include "../data/CoordConvert.h"       // Coord3, Coord4

// ---------------------------------------------------------------------------------------------------------------
// SimpleRigidBody (0x40 bytes, the Simulation's second array of bodies): a light point body - an orientation that
// is only set, never integrated, a position moved by its velocity each step, and a radius and box for the tests
// against the other bodies. See SimpleRigidBody.cpp.
// ---------------------------------------------------------------------------------------------------------------

struct PhysicsObject;

// A simple body's type, as each owner's constructor gives it
enum SimpleBodyType : uint8_t {
    kSimpleExplosion = 1,
    kSimpleHuman = 2,           // CheckCollisions tests it 0.5 higher
    kSimpleMine = 3,
    kSimpleMissile = 4,
    kSimpleShell = 5,
    kSimpleGrenade = 6,
    kSimpleNewton = 7,
    kSimpleHelicopter = 8,      // PHelicopter's
    kSimpleSentry = 9,
};

struct SimpleRigidBody {
    enum Flag : uint16_t {
        kFlag01 = 0x0001,           // CheckCollisions skips such a body; PhysicsObject::GetCollisionBounds has none
        kFlag04 = 0x0004,           // PhysicsObject::ApplyForces accelerates it; with kMoves UpdatePosition damps
                                    //   its velocity and acceleration
        kMoves = 0x0008,            // Accelerate and UpdatePosition change it
        kNearRigidHits = 0x0010,    // CheckCollisions: a rigid body within the two radii is a hit
        kNearSimpleHits = 0x0020,   // ... a simple body within them is a hit
        kBoxRigidHits = 0x0040,     // ... a rigid body within them is a hit if their boxes overlap
        kBoxSimpleHits = 0x0080,    // ... a simple body within them is a hit if their boxes overlap
        kCollisionChecks = 0x00f0,
        kTouchesTriggers = 0x0100,  // tested against the triggers (the name is ours; SetCanHitTrigger sets it)
    };

    Coord4 orientation;         // +0x00 a quaternion
    Coord3 position;            // +0x10
    uint8_t bodyType;           // +0x1c SimpleBodyType
    int8_t slot;                // +0x1d its place in the Simulation's simple-body tables (Ghidra: ownerIndex)
    uint16_t flags;             // +0x1e Flag
    Coord3 velocity;            // +0x20
    float radius;               // +0x2c
    Coord3 acceleration;        // +0x30
    float mass;                 // +0x3c PhysicsObject::GetMass's

    // SimpleRigidBody::SimpleRigidBody (0x000b1e10); `slot` is kept as its low byte
    SimpleRigidBody* Construct(int slot, uint8_t bodyType, const Coord3 *position, const Coord3 *velocity,
                               const Coord3 *acceleration, const MATRIX4 *orientation, float radius, float mass);
    void Destruct();                                                                            // 0x000b1e90
    PhysicsObject* GetOwner();                                                                  // 0x000b1ea0
    void RecalcOrientMat(MATRIX4 *matrix);                                                      // 0x000b1eb0
    void GetForwardVector(Coord3 *forward);                                                     // 0x000b1ec0
    void GetRightVector(Coord3 *right);                                                         // 0x000b1ee0
    void SetOrientMat(const MATRIX4 *matrix);                                                   // 0x000b1f00
    void SetOrientation(const Coord4 *quaternion);                                              // 0x000b1f10
    float GetScalarVelocity();                                                                  // 0x000b1f30
    void Accelerate(const Coord3 *acceleration);                                                // 0x000b1f40
    void UpdatePosition();                                                                      // 0x000b1f80
    bool NeedsCollisionCheck();                                                                 // 0x000b1fe0
    // Sets the bit of each body it hits in `hits` (by bit: the rigid bodies 0-63, then the simple ones 64-159)
    void CheckCollisions(uint64_t *hits);                                                       // 0x000b1ff0
    void SetCanHitTrigger(bool canHit);                                                         // 0x000b25c0
};
static_assert(sizeof(SimpleRigidBody) == 0x40, "a simple rigid body is 64 bytes");
static_assert(offsetof(SimpleRigidBody, position) == 0x10 && offsetof(SimpleRigidBody, slot) == 0x1d &&
              offsetof(SimpleRigidBody, flags) == 0x1e && offsetof(SimpleRigidBody, radius) == 0x2c &&
              offsetof(SimpleRigidBody, mass) == 0x3c, "simple rigid body layout");

#endif // DRIVING_PHYSICS_SIMPLERIGIDBODY_H_
