// Compares the drone tables generated by tools/drone_tables.py (src/action/game/drone/DroneTables.inc) with the
// game's copies, byte for byte, at start (MenuCheckLists=on, MenuProbe.cpp). The generator reads the same bytes from
// the XBE, so this checks what it cannot: that the generated initialisers compile to exactly those bytes with our
// struct layouts, before any reimplementation makes one of them the real table.

#include "DroneTablesCheck.h"

#include "../game/drone/DroneTables.h"

#include <stdio.h>
#include <string.h>

#include "../game/drone/DroneTables.inc"

static const DroneStateFunc stateFuncs[NUM_DSTATES] = DRONE_STATE_FUNCS_INIT;
static const DroneModeSetting modeSettings[DMODE_COUNT] = DRONE_MODE_SETTINGS_INIT;
static const DroneTypeSetting typeSettings[DTYPE_COUNT] = DRONE_TYPE_SETTINGS_INIT;
static const DroneBehaviourLayout behaviourLayouts[NUM_DRONE_PROPERTIES] = DRONE_BEHAVIOUR_LAYOUTS_INIT;
static const uint32_t behaviourMasks[] = DRONE_BEHAVIOUR_MASKS_INIT;
static const BOT_stats_t botStats[] = DEFAULT_BOT_STATS_INIT;

static_assert(sizeof(behaviourMasks) == sizeof(DroneBehaviourMasks), "mask count");
static_assert(sizeof(botStats) == sizeof(DefaultBotStats), "bot stats count");

static int Compare(const char *name, const void *ours, const void *theirs, size_t size, size_t entry) {
    if (memcmp(ours, theirs, size) == 0)
        return 0;
    for (size_t i = 0; i < size; i++)
        if (((const uchar *)ours)[i] != ((const uchar *)theirs)[i]) {
            printf("[drone tables] %s differs from entry %u (byte 0x%x)\n", name, (uint)(i / entry), (uint)i);
            break;
        }
    return 1;
}

void DroneTablesCheck_Run(void) {
    int differ = 0;
    differ += Compare("NDrone2_StateFuncs", stateFuncs, &NDrone2_StateFuncs, sizeof(stateFuncs), sizeof(stateFuncs[0]));
    differ += Compare("DroneModeSettings", modeSettings, &DroneModeSettings, sizeof(modeSettings), sizeof(modeSettings[0]));
    differ += Compare("DroneTypeSettings", typeSettings, &DroneTypeSettings, sizeof(typeSettings), sizeof(typeSettings[0]));
    differ += Compare("DroneBehaviourLayouts", behaviourLayouts, &DroneBehaviourLayouts, sizeof(behaviourLayouts),
                      sizeof(behaviourLayouts[0]));
    differ += Compare("DroneBehaviourMasks", behaviourMasks, &DroneBehaviourMasks, sizeof(behaviourMasks), 4);
    differ += Compare("DefaultBotStats", botStats, &DefaultBotStats, sizeof(botStats), sizeof(botStats[0]));
    printf("[drone tables] 6 tables checked against the game's: %d differ\n", differ);
}
