#ifndef DRIVING_CAMERA_CAMERASPLINE_H_
#define DRIVING_CAMERA_CAMERASPLINE_H_

// ---------------------------------------------------------------------------------------------------------------
// The cameras' maths and splines (RCameraMath, RCameraSpline, FindPointInList), and what the camera helpers share:
// the std::list layout the spline's point list and the director's queue are compiled from, and the warning beside
// a provisional port. Also the few functions the linker placed among them from other units (the end of this file).
//
// Vectors are Coord4s (the fourth word kept or cleared as each function says), matrices the engine's MATRIX4 (row
// vectors, the translation in row 3). Angles are in turns.
// ---------------------------------------------------------------------------------------------------------------

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "../autogenerated_layouts.h"   // MATRIX4
#include "../data/CoordConvert.h"       // Coord3, Coord4
#include "../data/SymbolTable.h"        // USymbolTable
#include "../data/UData.h"
#include "../engine/CoreFoundation.h"   // ThrowLengthError
#include "../engine/UMemory.hpp"

// ---- the warning beside a provisional port: code no shipped data reaches, said once, the first time it runs

inline void CameraUntested(const char *what) {
    printf("[camera] WARNING: %s ran - a provisional port that no shipped data reaches, UNTESTED. Check what it "
           "computes against the original.\n", what);
    fflush(stdout);
}

#define CAMERA_UNTESTED(what) \
    do { \
        static bool warned_; \
        if (!warned_) { \
            warned_ = true; \
            CameraUntested(what); \
        } \
    } while (0)

// ---- std::list<T> as the game compiled it (MSVC 7): the allocator's byte, the head node (end()), the size. A node
//      is the links, then the value. Each instantiation has its own compiled copies of the members, entered by
//      address from its own class (CameraSpline.cpp's points, DirectorQueue.cpp's queue).

template <class T>
struct CameraListNode {
    CameraListNode *next;       // +0x00
    CameraListNode *prev;       // +0x04
    T value;                    // +0x08
};

template <class T>
struct CameraList {
    typedef CameraListNode<T> Node;

    uint8_t allocator;          // +0x00
    uint8_t unknown01[3];
    Node *head;                 // +0x04
    uint32_t size;              // +0x08

    static constexpr uint32_t kMaxSize = 0xffffffffu / sizeof(T);

    // begin(), as the compiled code reads it: NULL without a head
    Node *Begin() const { return head != NULL ? head->next : NULL; }

    // A node from the pools ("STL"), linked as given, its value a copy (ConstructListValue)
    Node *BuyNodeT(Node *next, Node *prev, const T *value) {
        Node *node = static_cast<Node *>(UMemory::FastAlloc(sizeof(Node), "STL"));
        if (node != NULL) {
            node->next = next;
            node->prev = prev;
            ConstructListValue(&node->value, value);
        }
        return node;
    }

    // The head, linked to itself
    Node *BuyHeadT() {
        Node *node = static_cast<Node *>(UMemory::FastAlloc(sizeof(Node), "STL"));
        if (node != NULL) {
            node->next = node;
            node->prev = node;
        }
        return node;
    }

    // erase(first, last): unlinks, destroys (DestroyListValue) and frees each node but the head; answers last
    Node **EraseT(Node **result, Node *first, Node *last) {
        while (first != last) {
            Node *node = first;
            first = first->next;
            if (node != head) {
                node->prev->next = node->next;
                node->next->prev = node->prev;
                DestroyListValue(node);
                UMemory::FastFree(node, sizeof(Node));
                size--;
            }
        }
        *result = first;
        return result;
    }

    // _Incsize: length_error past kMaxSize nodes
    void IncreaseSizeT(uint32_t count) {
        if (kMaxSize - size < count) {
            CAMERA_UNTESTED("list<T>::_Incsize (too long)");
            ThrowLengthError("list<T> too long");
        }
        size += count;
    }

    // push_back (inlined in the game)
    void PushBackT(const T *value) {
        Node *node = BuyNodeT(head, head->prev, value);
        IncreaseSizeT(1);
        head->prev = node;
        node->prev->next = node;
    }

    // ~list() (inlined in the game): every node erased, then the head freed
    void DestructT() {
        Node *end;
        EraseT(&end, Begin(), head);
        if (head != NULL)
            UMemory::FastFree(head, sizeof(Node));
        head = NULL;
        size = 0;
    }
};

// A list of points: the values are copied as they are, and need no destruction
inline void ConstructListValue(Coord4 *slot, const Coord4 *value) {
    *slot = *value;
}
inline void DestroyListValue(CameraListNode<Coord4> *) {
}

// ---- the C runtime's arc cosine and sine (_CIacos at 0x001328d0, _CIasin at 0x00133f94, the game's own), which
//      take and answer the value on the x87 stack: the answer times *scale, multiplied there before anything
//      rounds it, as the cameras' callers do. Unrounded.

double CrtAcosTimes(float value, const float *scale);
double CrtAsinTimes(float value, const float *scale);

// ---- RCameraMath

class RCameraMath {
public:
    // The quaternion turning `turns` about the unit axis.                                          0x0007a1e0
    static void BuildRotationQuat(Coord4 *quat, float turns, const Coord4 *axis);
    // The rotation matrix of the same.                                                             0x0007a280
    static void BuildRotationMat4(MATRIX4 *matrix, float turns, const Coord4 *axis);
    // An orthonormal frame whose row 2 is `forward` (a unit vector, usually the matrix's own row 2): row 0 the unit
    // cross product of straight up with it, row 1 row 2 x row 0, row 3 (0, 0, 0, 1); the w words of rows 0-2 zero.
    //                                                                                              0x0007a2b0
    static void VU0_GenerateMatrix4Unit(const Coord4 *forward, MATRIX4 *matrix);
    // The same with row 3 the position, its w 1 (name ours).                                       0x0007a320
    static void VU0_GenerateMatrix4UnitAt(const Coord4 *forward, const Coord4 *position, MATRIX4 *matrix);
    // The arc cosine in turns of a cosine clamped to [-1, 1], unrounded (name ours).               0x0007a3b0
    static double ACosTurns(float cosine);
    // The frame looking along `direction`: row 2 its unit vector, then VU0_GenerateMatrix4Unit (name ours).
    //                                                                                              0x0007a410
    static void MatrixFromDirection(const Coord4 *direction, MATRIX4 *matrix);
    // ... with row 3 the position (name ours).                                                     0x0007a440
    static void MatrixFromDirectionAt(const Coord4 *direction, const Coord4 *position, MATRIX4 *matrix);
    // The angle in turns from a to b (unit vectors), 0-1 round the y axis: the arc cosine of their dot product,
    // from 1 when their cross product points down (name ours).                                    0x0007a470
    static double AngleTurns(const Coord4 *a, const Coord4 *b);
    // The rotation of the frame looking along `direction`.                                         0x0007a4e0
    static void VU0_GenerateQuat(const Coord4 *direction, Coord4 *quat);
};

// ---- RCameraSpline

// RCameraSpline (0x70 bytes): a cubic through four control points - a Bezier curve (BuildSplineEx), or a
// Catmull-Rom segment between two points of its point list (BuildSpline) - and two rotations to blend along it.
// GetSegmentCurveStep and WRoadNav use the Bezier form for curved road segments; the player camera the rest.
class RCameraSpline {
public:
    enum SplineType : int32_t {
        kSplineBezier = 0,          // the control points are the ends and the handles
        kSplineCatmullRom = 1,      // the control points are four points on the path; the curve is halved
        kSplineUnbuilt = 2,         // as constructed (evaluated as a Bezier)
    };

    typedef CameraListNode<Coord4> PointNode;

    // The point list (std::list<Coord4>): the path BuildSpline finds its segment in
    struct PointList : CameraList<Coord4> {
        PointNode* BuyNode(PointNode *next, PointNode *prev, const Coord4 *value);   // 0x0007a850
        PointNode* BuyHead();                                                      // 0x0007a950
        PointNode** Erase(PointNode **result, PointNode *first, PointNode *last);  // 0x0007a900
        void IncreaseSize(uint32_t count);                                          // 0x0007ad50
    };
    static_assert(sizeof(PointList) == 0xc, "a list is 12 bytes");

    Coord4 points[4];           // +0x00 the control points
    Coord4 rotations[2];        // +0x40 the quaternions at the two ends
    int32_t type;               // +0x60 SplineType
    PointList pointList;        // +0x64

    RCameraSpline* Construct();                                                     // 0x0007acd0
    void Destruct();                                                                // 0x0007a9b0
    // The point on the curve at t (0-1), its w 1.                                                  0x0007a530
    void EvaluateSpline(float t, Coord4 *point);
    // The unit tangent at t, its w 1.                                                              0x0007a5c0
    void EvaluateTangent(float t, Coord4 *tangent);
    uint32_t GetPointListSize();                                                    // 0x0007a640
    // A Bezier curve from start to end with the two handles; nothing while the point list holds more than one
    // point.                                                                                       0x0007a650
    void BuildSplineEx(const Coord3 *start, const Coord3 *startControl, const Coord3 *end, const Coord3 *endControl);
    // The frame at t: its rotation blended between the two quaternions (`blendRotations`), or looking along the
    // blend of their z axes; row 3 the point on the curve.                                         0x0007a6d0
    void EvaluateSpline(float t, MATRIX4 *frame, bool blendRotations);
    void ClearSplinePtList();                                                       // 0x0007a9f0
    // The segment from `from` to `to`, leaving and arriving along the two directions (normalised here, in place,
    // unless zero), handles scaled by `tension` times the distance between them: a Bezier when the point list has
    // fewer than two points (which it then clears), else the Catmull-Rom segment of the list that ends at `to`
    // (nothing if `to` is not in it). The two rotations are taken when both are given.            0x0007aa20
    void BuildSpline(const Coord4 *from, Coord4 *fromDirection, const Coord4 *to, Coord4 *toDirection,
                     const Coord4 *fromRotation, const Coord4 *toRotation, float tension);
    void AddToSplinePtList(const Coord4 *point);                                    // 0x0007ae00
};
static_assert(sizeof(RCameraSpline) == 0x70, "RCameraSpline is 0x70 bytes");
static_assert(offsetof(RCameraSpline, rotations) == 0x40 && offsetof(RCameraSpline, type) == 0x60 &&
              offsetof(RCameraSpline, pointList) == 0x64, "RCameraSpline layout");

// The first node of the list whose point has these x, y and z, or end() (answered through `result`).  0x0007a8a0
RCameraSpline::PointNode** FindPointInList(RCameraSpline::PointNode **result, RCameraSpline::PointList *list,
                                           const Coord4 *point);

// ---- placed here by the linker from other units

// The global symbol table's class (vtable 0x00190e18; GlobalSymbolTable::Init in data/RCARPFile.cpp makes it): a
// USymbolTable with a deleting destructor of its own (name ours).
class GameSymbolTable : public USymbolTable {
public:
    void Destruct();                    // 0x0007ae60: back to USymbolTable's, then its destructor
    GameSymbolTable* Delete(unsigned flags);   // 0x0007ae40, the vtable's slot 0
};

// UData::MatchTag, compiled out of line once (for RVehicle::PostLoad).
class UDataRecord : public UData {
public:
    uint32_t MatchTag() const;          // 0x0007ae70
};

// A symbol callback that answers nothing (RegisterCallback::AddMajorCallbacks registers it; name ours).    0x0007ae90
void* NoSymbolCallback(const char *name, bool *found);

// Frees the EAGL material objects RCARPFile::LoadEAGLMaterials loaded (name ours).                    0x0007aee0
void FreeEAGLMaterials();

#endif // DRIVING_CAMERA_CAMERASPLINE_H_
