#ifndef PARSEMAP_H_
#define PARSEMAP_H_

#include "../actionhelpers.h"


typedef enum {
    Place_Drone	                = 15,
    Place_Breakable	            = 32,
    Place_Ripples               = 33,
    Place_Ladder                = 34,
    Place_PlayerNewStartPos     = 36,
    Place_MPSpawnPoint          = 37,
    Place_MPObject              = 38,
    Place_GunTurret             = 39,
    Place_Sensor                = 40,
    Place_Switch                = 41,
    Place_SkyObject             = 42,
    Place_LeafGen               = 43,
    Place_Lightning             = 44,
    Place_AddNewStartPos2       = 45,
    Place_Lock                  = 46,
    Place_Copter                = 47,
    Place_Monitor               = 48,
    Place_FuseBox               = 49,
    Place_RainBox               = 50,
    Place_Hint                  = 51,
    Place_GunImp                = 52,
    Place_PCQWorm               = 53,
    Place_Sub                   = 54,
    Place_MiniSub               = 55,
    Place_SpaceLaser            = 56,
    Place_SpaceMissile          = 57,
    Place_Grapple               = 58,
    Place_DynamicObject         = 59,
    Place_Wire                  = 62,
    Place_CreepWall             = 63,
    Place_InverterTrigger       = 65,
    Place_Apocalypse            = 74,
    Place_Light                 = 78,
    Place_Rotor                 = 113,
    Place_Shooter               = 210,
    Place_Cloud                 = 212,
    Place_OneSided              = 213,
    Place_RigidBody             = 216,
    Place_ScriptPlayer          = 217,
    Place_Car                   = 218,
    Place_Door                  = 219,
    Place_Trigger               = 220,
    Place_Searchlight           = 222,
    Place_Env                   = 223,
    Place_Creature              = 224,
    Place_Destroy               = 225,
    Place_SS                    = 226,
    Place_Flicker               = 227,
    Place_Hurt                  = 228,
    Place_DroneCoverCorner      = 229,
    Place_DroneCoverLow         = 230,
    Place_ThirdCam              = 231,
    Place_TriggerLoadLevel      = 232,
    Place_DroneAIPoint          = 233,
    Place_TriggerTouchOnce      = 234,
    Place_TriggerTouch          = 235,
    Place_TriggerMultiplexIn    = 236,
    Place_TriggerMultiplexSIn   = 237,
    Place_TriggerMultiplexOut   = 238,
    Place_TriggerMultiplexOrIn  = 239,
    Place_Pickup                = 240,
    Place_DroneSpawner          = 241,
    Place_Emitter               = 242,
    Place_EnvTree               = 243,
    Place_TriggerMoviePlayer    = 244,
    Place_DroneAIVolume1        = 245,
    Place_DroneAIVolume2        = 248,
    Place_SoundTrigger          = 249,
    Place_ThirdIcon             = 250,
    Place_MusicTrigger          = 251,
    Place_Corona                = 252,
    Place_CamSubject            = 253,
    Place_Mine                  = 254,
    Place_Force_U32             = 0x7FFFFFFF
} ObjectPlacementType;



bool parsemap_parsemap(uint hashcode, bool param_2);
void parsemap_create_dynamic_objects(TARGET_PLACEMENT* placement, level_tag* lvl, ObjectPlacementType type, celglist_tag* celglist, void* a, void* b, char doCreation);


#endif // PARSEMAP_H_