// THIS FILE IS GENERATED by tools/drone_tables.py from disc/default.xbe. DO NOT MODIFY.
// Regenerate (and commit) after reimplementing a state handler or an init/control function it lists.

#ifndef DRONETABLES_H_
#define DRONETABLES_H_

#include "NDrone2.h"
#include "BOT.h"

#pragma pack(push, 1)

// A state handler: Enter, Exit and Update are messages like any other. Returns whether it handled the message.
typedef bool (*DroneStateFunc)(DCVars_tag *dcv, Drone_tag *drone, obj_tag *gameObj, MsgObject *msg);

// DroneModeSettings, indexed by DMODE (NDrone2_DoModeSettingsOLD)
typedef struct DroneModeSetting {
    uchar dtype;                // the DTYPE the mode gives
    uchar side;                 // Drone_tag.side: 1 enemy, 2 ally, 3 civilian / neutral
    ushort pad;
    float alertness;            // Drone_tag.baseAlertness1 and .alertness
    void (*init)(Drone_tag *drone);
} DroneModeSetting;

// DroneTypeSettings, indexed by DTYPE
typedef struct DroneTypeSetting {
    short initialState;         // Drone_tag.initialState; -1 = worked out (Idle, or InitPatrol for patrollers)
    short secondState;          // Drone_tag.secondState when switching to this type; 0 = the active type's
    void (*init)(Drone_tag *drone);
    void (*control)(DCVars_tag *dcv);   // per frame, instead of NDrone2_ControlSTANDARD
} DroneTypeSetting;

// Where a behaviour property lives in the three behaviour words: behaviour_util_getProperty(id, words) =
// (words[wordShift & 7] & DroneBehaviourMasks[maskIndex]) >> (wordShift >> 3)
typedef struct DroneBehaviourLayout {
    uchar wordShift;
    uchar maskIndex;
} DroneBehaviourLayout;

#pragma pack(pop)

static_assert(sizeof(DroneModeSetting) == 12, "DroneModeSetting is 12 bytes");
static_assert(sizeof(DroneTypeSetting) == 12, "DroneTypeSetting is 12 bytes");
static_assert(sizeof(DroneBehaviourLayout) == 2, "DroneBehaviourLayout is 2 bytes");

#define NUM_DSTATES 250
#define NUM_DRONE_PROPERTIES 91

// The game's tables. Each stays the game's until every function reading it is ours.
// XBE_GLOBAL(0x00177ca0, 0x3e8)
#define NDrone2_StateFuncs (*(DroneStateFunc(*)[NUM_DSTATES])0x00177ca0)
// XBE_GLOBAL(0x001776f8, 0x1b0)
#define DroneModeSettings (*(DroneModeSetting(*)[DMODE_COUNT])0x001776f8)
// XBE_GLOBAL(0x001778a0, 0x3fc)
#define DroneTypeSettings (*(DroneTypeSetting(*)[DTYPE_COUNT])0x001778a0)
// XBE_GLOBAL(0x001634e0, 0xb6)
#define DroneBehaviourLayouts (*(const DroneBehaviourLayout(*)[NUM_DRONE_PROPERTIES])0x001634e0)
// XBE_GLOBAL(0x00163598, 0x8c)
#define DroneBehaviourMasks (*(const uint32_t(*)[35])0x00163598)
// XBE_GLOBAL(0x00163628, 0x196)
#define DefaultBotStats (*(const BOT_stats_t(*)[29])0x00163628)

// The behaviour properties (docs/drone/behaviours/behaviour_properties.md). Numbered, not named: the meanings
// are inferred and some are guesses.
typedef enum {
    DRONE_PROP_00,  // word 0 bit 0           move: crouch-walk allowed (with 0x02: anim state 0xf)
    DRONE_PROP_01,  // word 0 bit 1           move: anim state 8 allowed (only if 0x02 clear)
    DRONE_PROP_02,  // word 0 bit 2           move: modifier for 0x00/0x01
    DRONE_PROP_03,  // word 0 bit 3           (no reader)
    DRONE_PROP_04,  // word 0 bit 4           (no reader)
    DRONE_PROP_05,  // word 0 bit 5           captain on difficulty 2 (Normal): upgraded skin, x DroneCaptain_Mod_*
    DRONE_PROP_06,  // word 0 bit 6           combat: may back off (anim state 4, 1.8 m clear)
    DRONE_PROP_07,  // word 0 bit 7           (no reader)
    DRONE_PROP_08,  // word 0 bit 8           captain on difficulty 3 (Hard)
    DRONE_PROP_09,  // word 0 bit 9           captain on difficulty 1 (Easy)
    DRONE_PROP_0A,  // word 0 bit 10          cover: lean (stand/crouch)
    DRONE_PROP_0B,  // word 0 bit 11          cover: stand lean variant
    DRONE_PROP_0C,  // word 0 bit 12          cover: step out
    DRONE_PROP_0D,  // word 0 bit 13          cover: stand lean variant 2
    DRONE_PROP_0E,  // word 0 bit 14          (no reader)
    DRONE_PROP_0F,  // word 0 bit 15          cover: may use crouch cover
    DRONE_PROP_10,  // word 0 bit 16          cover: force crouch-only cover (cleared when shot out of UnderCover)
    DRONE_PROP_11,  // word 0 bit 17          combat: dodge/roll move (anim state 5, target >= 6 m)
    DRONE_PROP_12,  // word 0 bit 18          (no reader)
    DRONE_PROP_13,  // word 0 bit 19          combat: strafe-dodge (anim state 0x29)
    DRONE_PROP_14,  // word 0 bit 20          doors: open behaviour A
    DRONE_PROP_15,  // word 0 bit 21          doors: open behaviour B
    DRONE_PROP_16,  // word 0 bit 22          doors: open behaviour C
    DRONE_PROP_17,  // word 0 bit 23          firing: keep firing at last-seen position when sight lost (>15 frames)
    DRONE_PROP_18,  // word 0 bit 24          on sighting: go straight to Attack
    DRONE_PROP_19,  // word 0 bit 25          on sighting: choose a combat move
    DRONE_PROP_1A,  // word 0 bit 26          on sighting: challenge/interrogate (Castle, Tower levels)
    DRONE_PROP_1B,  // word 0 bit 27          on sighting: 50/50 attack or combat move
    DRONE_PROP_1C,  // word 0 bit 28          stun grenade: resists (plays flinch anim instead of StunGrenadeImpact)
    DRONE_PROP_1D,  // word 0 bit 29          on init: take nearest AI path of type 8 (NDrone2_AssignAIPath)
    DRONE_PROP_1E,  // word 0 bit 30          (no reader)
    DRONE_PROP_1F,  // word 0 bit 31          hearing: reacts to sounds (Sound_Alertness, msg 0x14)
    DRONE_PROP_20,  // word 1 bit 0 (2 bits)  2-bit: initial alertness level -> {0, 0, 0.66, 1.0}
    DRONE_PROP_21,  // word 1 bit 2           HeardNoiseSuspect behaviour
    DRONE_PROP_22,  // word 1 bit 3           (no reader)
    DRONE_PROP_23,  // word 1 bit 4           (no reader)
    DRONE_PROP_24,  // word 1 bit 5           patrol: init to InitPatrol (with 0x25)
    DRONE_PROP_25,  // word 1 bit 6           patrol: follow patrol path
    DRONE_PROP_26,  // word 1 bit 7           contagion: alerted by seeing a drone whose cause bit 8 (saw a dead body) is set; only read in ConsiderAlerted
    DRONE_PROP_27,  // word 1 bit 8           contagion: alerted by drone-shot (msg 0x12 / cause bit 2)
    DRONE_PROP_28,  // word 1 bit 9           contagion: alerted by opponent-sighted alarm (msg 0x11 / cause bit 1)
    DRONE_PROP_29,  // word 1 bit 10          contagion: alerted by dead body (msg 0x15 / cause bit 8)
    DRONE_PROP_2A,  // word 1 bit 11          (no reader)
    DRONE_PROP_2B,  // word 1 bit 12          (no reader)
    DRONE_PROP_2C,  // word 1 bit 13          (no reader)
    DRONE_PROP_2D,  // word 1 bit 14          (no reader)
    DRONE_PROP_2E,  // word 1 bit 15          combat: roll (anim state check)
    DRONE_PROP_2F,  // word 1 bit 16          (no reader)
    DRONE_PROP_30,  // word 1 bit 17 (3 bits) cover: uses cover at all (NDrone2_CoverAvailable)
    DRONE_PROP_31,  // word 1 bit 20          death: broadcasts on death unless head-shot (DSTATE_Dead)
    DRONE_PROP_32,  // word 1 bit 21          when hurt: broadcast hurt alert 0x12 (DroneFunc_SendHurtMessage)
    DRONE_PROP_33,  // word 1 bit 22          on sighting: broadcast 0x11 alarm to others (20 m)
    DRONE_PROP_34,  // word 1 bit 23          explosives: reacts to grenades/smoke (with 0x36)
    DRONE_PROP_35,  // word 1 bit 24          (no reader)
    DRONE_PROP_36,  // word 1 bit 25          explosives: ignores smoke (with 0x34)
    DRONE_PROP_37,  // word 1 bit 26          (no reader)
    DRONE_PROP_38,  // word 1 bit 27          (no reader)
    DRONE_PROP_39,  // word 1 bit 28          (no reader)
    DRONE_PROP_3A,  // word 1 bit 29          explosives: aware of explosives A
    DRONE_PROP_3B,  // word 1 bit 30          explosives: aware B (then Attack)
    DRONE_PROP_3C,  // word 1 bit 31          vision: can spot opponents at all
    DRONE_PROP_3D,  // word 2 bit 0           (no reader)
    DRONE_PROP_3E,  // word 2 bit 1           (no reader)
    DRONE_PROP_3F,  // word 2 bit 2           (no reader)
    DRONE_PROP_40,  // word 2 bit 3           combat: no combat moves (stand and fire)
    DRONE_PROP_41,  // word 2 bit 4           combat: strafe
    DRONE_PROP_42,  // word 2 bit 5           combat: side-step
    DRONE_PROP_43,  // word 2 bit 6           may surrender (close, unarmed-ish, facing Bond)
    DRONE_PROP_44,  // word 2 bit 7 (2 bits)  2-bit: cover distance cap (cover farther than combatRange*1.5 rejected when set)
    DRONE_PROP_45,  // word 2 bit 9           (no reader)
    DRONE_PROP_46,  // word 2 bit 10          idle: look-around/fidget timer (NDrone2_SetIdleTimeOut)
    DRONE_PROP_47,  // word 2 bit 11          idle: extra idle anim variant (4 instead of 3)
    DRONE_PROP_48,  // word 2 bit 12          (no reader)
    DRONE_PROP_49,  // word 2 bit 13          (no reader)
    DRONE_PROP_4A,  // word 2 bit 14          on sighting: throw grenade (DSTATE_GrenadeThrow)
    DRONE_PROP_4B,  // word 2 bit 15          Castle Indoors 1: DTYPE 0x16 instead of 0x13
    DRONE_PROP_4C,  // word 2 bit 16          head-track the opponent/player
    DRONE_PROP_4D,  // word 2 bit 17          (no reader)
    DRONE_PROP_4E,  // word 2 bit 18          hostage-tied/run: DTYPE 5, NDrone2_FindRunToPoint
    DRONE_PROP_4F,  // word 2 bit 19          contagion: alerted by surrendered drone (msg 0x13 / cause bit 4)
    DRONE_PROP_50,  // word 2 bit 20          NDrone2_NearArmedDrone check
    DRONE_PROP_51,  // word 2 bit 21          reacts to the player even when not suspicious (<0.66)
    DRONE_PROP_52,  // word 2 bit 22          first attack: mission-fail label 0x4000033 (PartyGirl: fail reason 0xb)
    DRONE_PROP_53,  // word 2 bit 23          death: mission fail (0x4000034/33)
    DRONE_PROP_54,  // word 2 bit 24          death by player: mission fail
    DRONE_PROP_55,  // word 2 bit 25          seen player: mission fail reason 10
    DRONE_PROP_56,  // word 2 bit 26          run-to-point: flee to alarm (DTYPE 0xe) / EnemyRunToPoint
    DRONE_PROP_57,  // word 2 bit 27          on sighting: allowed while in EnemyRunToPoint/99
    DRONE_PROP_58,  // word 2 bit 28          (no reader)
    DRONE_PROP_59,  // word 2 bit 29          at goal position: delete self (DSTATE_DeleteMe)
    DRONE_PROP_5A,  // word 2 bit 30          (no reader)
} DRONE_PROP;

#endif // DRONETABLES_H_
