#ifndef DRIVING_AUDIO_MIX_H_
#define DRIVING_AUDIO_MIX_H_

// ---------------------------------------------------------------------------------------------------------------
// The audio framework's mix groups, effects and listener (engine.audio):
//
//   - AMix: a named volume, shared through URefCounter<AMix> (engine/URefCounter.h). Every sound points at one (its
//     mix); a mix may be scaled by another (its master). A mix moves to a new volume over a number of calls to
//     GetVolume (a transition). AMix::Load reads the mixes' preset volumes from an ini file and keeps the loaded
//     mixes in a list; Reset moves every one of those back to its preset.
//   - the code of URefCounter<AMix>'s tree, and two helpers every URefCounter's tree calls;
//   - AFX: the environmental effect (the reverb on the sound library's effect bus), chosen by mode, each mode with
//     a mix of its own whose volume is the effect's level;
//   - AListener: where the sounds are heard from.
//
// See Mix.cpp.
// ---------------------------------------------------------------------------------------------------------------

#include <stddef.h>
#include <stdint.h>

#include "../autogenerated_layouts.h"   // MATRIX4
#include "../data/CoordConvert.h"       // Coord3, Coord4
#include "../engine/URefCounter.h"
#include "../world/Targeting.h"         // PointerList: std::list<T *>

// A mix (0x50 bytes, from UMemory::FastAlloc "AMix").
class AMix {
public:
    AMix *master;               // +0x00 the mix this one's volume is scaled by, or NULL
    float volume;               // +0x04
    float previous;             // +0x08 the volume before the last change, Revert's target (name ours)
    float unknown0c;            // +0x0c -1 from Add; Load's volume
    float presetVolume;         // +0x10 -1 from Add; Load's volume, Reset's target
    float target;               // +0x14 where a transition ends
    float step;                 // +0x18 what a transition adds at each call to GetVolume
    bool transitioning;         // +0x1c
    uint8_t unknown1d[3];
    int32_t unknown20;          // +0x20 Load: the integer after the volume
    int32_t unknown24;          // +0x24 zero from Add; AStream::Play adds one at each play it counts
    float unknown28;            // +0x28 zero from Add; AStream::Play adds twice the play's volume
    float unknown2c;            // +0x2c 1 from Add; AStream::Play scales the play's volume by it
    char name[0x20];            // +0x30 set by Load only

    // From the current volume to `volume` (clamped to 0..1) over `steps` calls to GetVolume (at least one).
    void SetTransition(float volume, int steps);                                // 0x0011c980
    // Back to the volume before the last change, over `steps` calls.
    void Revert(int steps);                                                     // 0x0011c9e0
    // The volume times the master's (advancing a transition a step first). Unrounded, as the x87 leaves it.
    double GetVolume();                                                         // 0x0011ca10
    float GetPresetVolume();                                                    // 0x0011ca90

    // Every mix Load read moves back to its preset volume over `steps` calls.
    static void Reset(int steps);                                               // 0x0011cb80
    // The mix named `name`, made if new, with one more reference.
    static AMix* Add(const char *name);                                         // 0x0011d6a0
    // The mix named `name`; made (and referenced) only if new.
    static AMix* Get(const char *name);                                         // 0x0011d720
    // One reference fewer; the last one frees the mix and gives up its master.
    void Remove();                                                              // 0x0011d750
    // Lines of "name=volume, number" (default.ini if the file cannot be read): each mix made, preset and listed.
    static void Load(const char *path);                                         // 0x0011d790
    // Every mix released until none is registered, and the list emptied.
    static void Clear();                                                        // 0x0011d980
    void ClearMaster();                                                         // 0x0011da20
    void SetMaster(const char *name);                                           // 0x0011da60

    // A change of volume without a transition (inlined by the faders; name ours)
    void SetVolume(float to) {
        previous = volume;
        volume = to;
    }
};
static_assert(offsetof(AMix, target) == 0x14, "AMix::target is at +0x14");
static_assert(offsetof(AMix, transitioning) == 0x1c, "AMix::transitioning is at +0x1c");
static_assert(offsetof(AMix, name) == 0x30, "AMix::name is at +0x30");
static_assert(sizeof(AMix) == 0x50, "AMix is 0x50 bytes");

// The list of the mixes Load read (std::list<AMix *>, at 0x00243954), with two of its compiled functions.
struct MixList : PointerList {
    // The list's constructor (the linker shares it with SMissionManager's): the head, no nodes.
    MixList* Construct();                                                       // 0x0011cc10
    // _Incsize, a copy of PointerList::IncreaseSize.
    void IncreaseSize(uint32_t count);                                          // 0x0011cc80
};

// ---- the URefCounters' trees

// An iterator over a URefCounter's tree, and the decrement every such tree calls (inlined --iterator: the head
// goes to the rightmost node).
struct RefCounterIterator {
    RefCounterNode *node;

    void Decrement();                                                           // 0x0011caa0
};

// The tree code each URefCounter<T> compiles, written once. Every copy is the same instructions, calling the
// helpers every such tree shares (the iterator's steps, the minimum and maximum, the rotations, the node maker);
// each instantiation's copies call each other. The bodies here are those copies; MixRefTree's entries (and
// FaderRefTree's, Fader.h) call them.
class RefCounterTree : public URefCounterMap {
public:
    // The rotation every URefCounter's tree calls.
    void Lrotate(RefCounterNode *where);                                        // 0x0011cb20

protected:
    // _Erase: frees a subtree without rebalancing.
    void EraseSubtree(RefCounterNode *node);
    // erase(where): unlinks and frees the node, rebalances, answers the next one.
    RefCounterNode **EraseAt(RefCounterNode **result, RefCounterNode *where);
    // _Insert: a new red node under `where` (on its left if `addLeft`), then rebalances.
    RefCounterNode **InsertAt(RefCounterNode **result, bool addLeft, RefCounterNode *where,
                              const RefCounterValue *value);
    // erase(first, last): everything is cleared at once, otherwise one node at a time.
    RefCounterNode **EraseRange(RefCounterNode **result, RefCounterNode *first, RefCounterNode *last);
    // insert(value): where the name is, or a new node for it.
    RefCounterInsertResult *InsertUnique(RefCounterInsertResult *result, const RefCounterValue *value);
    // The static's destructor: everything erased, the head freed.
    void Destroy();
    // The same without erasing the subtree first (the copy an exception unwind calls).
    void DestroyRange();
};

// URefCounter<AMix>'s tree (MixRefCounter's map, at 0x00243944): its compiled copies.
class MixRefTree : public RefCounterTree {
public:
    void EraseSubtree(RefCounterNode *node);                                    // 0x0011cc30
    RefCounterNode** EraseAt(RefCounterNode **result, RefCounterNode *where);   // 0x0011cd30
    RefCounterNode** InsertAt(RefCounterNode **result, bool addLeft, RefCounterNode *where,
                              const RefCounterValue *value);                    // 0x0011d0a0
    RefCounterNode** EraseRange(RefCounterNode **result, RefCounterNode *first,
                                RefCounterNode *last);                          // 0x0011d290
    RefCounterInsertResult* InsertUnique(RefCounterInsertResult *result,
                                         const RefCounterValue *value);         // 0x0011d380
    void Destruct();                                                            // 0x0011d580
};

// ---- AFX

// An effect mode (0x14 bytes; the game's thirteen at 0x001d8190). Its name, with a two-character prefix, is also its
// mix's.
struct FxMode {
    const char *name;           // +0x00
    bool allVoices;             // +0x04
    uint8_t unknown05[3];
    int32_t reverb;             // +0x08 an index into the bus modes (FxBusModes)
    int32_t delay;              // +0x0c
    int32_t feedback;           // +0x10
};
static_assert(sizeof(FxMode) == 0x14, "an effect mode is 0x14 bytes");

// A request for a mode, in one of two slots; the higher priority wins (the later mode at the same).
struct FxRequest {
    int32_t mode;
    int32_t priority;           // -1: none
};

// AFX's state (0x24 bytes at 0x001d80f0, initialised data).
struct FxState {
    FxRequest requests[2];      // +0x00
    int32_t currentMode;        // +0x10 -1: off
    int32_t unknown14;          // +0x14
    int32_t busReverb;          // +0x18 what the bus was last set up with
    int32_t busDelay;           // +0x1c
    int32_t busFeedback;        // +0x20
};
static_assert(sizeof(FxState) == 0x24, "AFX's state is 0x24 bytes");

class AFX {
public:
    enum { kModeCount = 13 };

    // Each mode's mix.
    static void Init();                                                         // 0x00124790
    // Asks for `mode` in `slot` at `priority`: taken unless the slot holds a higher priority (or the same with a
    // higher mode).
    static void SetMode(int mode, int slot, int priority);                      // 0x001247d0
    // The current mode's name without its prefix, or "Off".
    static const char* GetCurrentModeName();                                    // 0x00124810
    static bool IsAllVoices();                                                  // 0x00124830
    static void Pause();                                                        // 0x00124850
    static void Resume();                                                       // 0x00124870
    static void Shutdown();                                                     // 0x00124880
    // Once per audio frame: the winning request becomes the mode (the level fading out of the old one first),
    // and the level follows the mode's mix.
    static void Update();                                                       // 0x001248b0
};

// ---- AListener

// A listener (0x78 bytes): a camera matrix's inverse, the velocity, and settings.
class AListener {
public:
    MATRIX4 matrix;             // +0x00 the inverse of the camera's: its rotation transposed, the translation
    Coord4 position;            // +0x40 w = 1
    Coord3 velocity;            // +0x50
    int32_t unknown5c;          // +0x5c the constructors' last argument
    uint8_t unknown60[0x10];
    float unknown70;            // +0x70 -100000
    uint32_t unknown74;         // +0x74 zero

    // At the origin, unrotated.
    AListener* Construct(int unknown);                                          // 0x00124ae0
    // From a camera's matrix and velocity.
    AListener* Construct(const MATRIX4 *camera, const Coord3 *velocity, int unknown);   // 0x00124b50
};
static_assert(offsetof(AListener, unknown70) == 0x70, "AListener::unknown70 is at +0x70");
static_assert(sizeof(AListener) == 0x78, "AListener is 0x78 bytes");

#endif // DRIVING_AUDIO_MIX_H_
