"""Writes src/action/ui/CreditsData.inc, the credits table the reimplemented Menu_SetupCredits reads, from
data/credits.csv (extracted from the XBE by extract_credits.py; see docs/ui/credits.md).

  python tools/ui/gen_credits_table.py            # rewrite the .inc
  python tools/ui/gen_credits_table.py --check    # exit 1 if the .inc is out of date

The .inc is checked in, so the build needs no Python. One line per credits row:
  { centred, left style, right style, left label, right label, "left text", "right text" },
a label of TXT_NONE meaning the literal is used (bank-0 label 0 is a real label, so 0 cannot mean "none").
Literals are the game's cp1252 bytes: anything outside printable ASCII is a \\xNN escape in a string piece of
its own, so a following hex digit is never read as part of it.
"""
import csv
import os
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
CSV = os.path.join(REPO, 'data', 'credits.csv')
OUT = os.path.join(REPO, 'src', 'action', 'ui', 'CreditsData.inc')


def c_string(text):
    if text is None:
        return 'NULL'
    out, piece = [], ''
    for b in text.encode('cp1252'):
        if 0x20 <= b < 0x7f and b not in (0x22, 0x5c):
            piece += chr(b)
        else:
            if piece:
                out.append('"%s"' % piece)
                piece = ''
            out.append('"\\x%02x"' % b)
    if piece or not out:
        out.append('"%s"' % piece)
    return ' '.join(out)


def cell(row, side):
    label, text = row[side + '_label'], row[side + '_text']
    if label:
        return label, 'NULL'
    return 'TXT_NONE', ('NULL' if text == '' else c_string(text))


def generate():
    rows = list(csv.DictReader(open(CSV, encoding='utf-8', newline='')))
    lines = ['// THIS FILE IS AUTOMATICALLY GENERATED from data/credits.csv by tools/ui/gen_credits_table.py. DO NOT MODIFY.',
             '// %d rows: { centred, left style, right style, left label, right label, left text, right text }' % len(rows)]
    for i, row in enumerate(rows):
        assert int(row['index']) == i, 'rows out of order at %d' % i
        ll, lt = cell(row, 'left')
        rl, rt = cell(row, 'right')
        lines.append('{ %s, %s, %s, %s, %s, %s, %s },' % (row['centred'], row['left_style'], row['right_style'],
                                                         ll, rl, lt, rt))
    return '\r\n'.join(lines) + '\r\n'


if __name__ == '__main__':
    text = generate()
    old = open(OUT, 'rb').read().decode('ascii') if os.path.exists(OUT) else None
    if '--check' in sys.argv:
        sys.exit(0 if old == text else 1)
    if old != text:
        open(OUT, 'wb').write(text.encode('ascii'))
        print('wrote', OUT)
