#pragma once

#include <stdint.h>

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"

// Game actions: the top of the input layer. IOModule polls the pads, maps each control through the current
// control configuration to an action id, and hands the result to the ActionQueueManager as an ActionData
// (action id, a source field, and the control's value). The manager copies every action into every registered
// ActionQueue; each consumer - the HUD (pause is action 0x47), the mission manager, the weapon manager, the
// world camera, the helicopter, the player's car - owns a queue and drains it in its own update with GetAction
// and PopAction.
//
// ActionData and the queue's ring buffer (ActionQueueRing, a name invented here: the PS2 build inlines it) are
// plain structs generated from Ghidra, embedded in ActionQueue, an overlay class - see src/common/xbeClass.h.

// The action ids, each named as in the game's table of action names (0x001b6ba0, getActionID's): NULL_ACTION,
// GAMEACTION_STEER, ... ACTION_PLUGUNPLUG
enum GameAction : int32_t {
    kNullAction = 0,
    kActionSteer = 1,
    kActionSteerVertical = 2,
    kActionSteerVerticalInv = 3,
    kActionSteerLeft = 4,
    kActionSteerRight = 5,
    kActionSteerUp = 6,
    kActionSteerDown = 7,
    kActionSteerLeftDigital = 8,
    kActionSteerRightDigital = 9,
    kActionSteerUpDigital = 10,
    kActionSteerDownDigital = 11,
    kActionSoundSteerLeft = 12,
    kActionSoundSteerRight = 13,
    kActionSoundSteerUp = 14,
    kActionSoundSteerDown = 15,
    kActionSoundSteerHorizontalRelease = 16,
    kActionSoundSteerVerticalRelease = 17,
    kActionSoundSteerPadLeft = 18,
    kActionSoundSteerPadRight = 19,
    kActionSoundSteerPadUp = 20,
    kActionSoundSteerPadDown = 21,
    kActionGas = 22,
    kActionGasBrake = 23,
    kActionWheelSpin = 24,
    kActionWheelSpinRelease = 25,
    kActionBrake = 26,
    kActionHandbrake = 27,
    kActionHandbrakeRelease = 28,
    kActionFirePrimary = 29,
    kActionFirePrimaryRelease = 30,
    kActionFireSecondary = 31,
    kActionFireSecondaryRelease = 32,
    kActionToggleSecondary = 33,
    kActionToggleSecondaryUp = 34,
    kActionToggleSecondaryDown = 35,
    kActionFireGadget = 36,
    kActionFireGadgetRelease = 37,
    kActionChangeCamera = 38,
    kActionChangeCameraUp = 39,
    kActionChangeCameraDown = 40,
    kActionCamLookBack = 41,
    kActionCamLookBackRelease = 42,
    kActionCamZoomButton = 43,
    kActionCamRotateX = 44,
    kActionCamRotateY = 45,
    kActionCamRotateYInv = 46,
    kActionCamRotateX2 = 47,
    kActionCamRotateY2 = 48,
    kActionCamRotateY2Inv = 49,
    kActionCamSpin = 50,
    kActionCamCentre = 51,
    kActionCamZoomInOut = 52,
    kActionCamZoomIn = 53,
    kActionCamZoomOut = 54,
    kActionAimZoomLeft = 55,
    kActionAimZoomRight = 56,
    kActionAimZoomNone = 57,
    kActionAimRelease = 58,
    kActionAutoDriveLock = 59,
    kActionAutoDriveLockRelease = 60,
    kActionLeanRight = 61,
    kActionLeanLeft = 62,
    kActionPovReload = 63,
    kActionResumeAutoDrive = 64,
    kFrontEndUp = 65,
    kFrontEndDown = 66,
    kFrontEndLeft = 67,
    kFrontEndRight = 68,
    kFrontEndAccept = 69,
    kFrontEndCancel = 70,
    kFrontEndStart = 71,
    kFrontEndScreenshot = 72,
    kFrontEndInvert = 73,
    kFrontEndSkipMovie = 74,
    kDebugAxisX = 75,
    kDebugAxisY = 76,
    kDebugAxisRX = 77,
    kDebugAxisRY = 78,
    kDebugScreenshot = 79,
    kDebugStopRecordPath = 80,
    kCheatDpadLeft = 81,
    kCheatDpadLeftRelease = 82,
    kCheatDpadUp = 83,
    kCheatDpadUpRelease = 84,
    kCheatDpadRight = 85,
    kCheatDpadRightRelease = 86,
    kCheatDpadDown = 87,
    kCheatDpadDownRelease = 88,
    kCheatButLeft = 89,
    kCheatButLeftRelease = 90,
    kCheatButUp = 91,
    kCheatButUpRelease = 92,
    kCheatButRight = 93,
    kCheatButRightRelease = 94,
    kCheatButDown = 95,
    kCheatButDownRelease = 96,
    kCheatTriggerLeft = 97,
    kCheatTriggerLeftRelease = 98,
    kCheatTriggerRight = 99,
    kCheatTriggerRightRelease = 100,
    kActionExitApplication = 101,
    kActionMinimizeApplication = 102,
    kActionRestoreApplication = 103,
    kActionMouseMoveX = 104,
    kActionMouseMoveY = 105,
    kActionMouseMove = 106,
    kActionMouseLButtonDown = 107,
    kActionMouseLButtonUp = 108,
    kActionMouseRButtonDown = 109,
    kActionMouseRButtonUp = 110,
    kActionKeyDown = 111,
    kActionKeyUp = 112,
    kActionChar = 113,
    kActionCenter = 114,
    kActionInputSync = 115,
    kActionPlugUnplug = 116,
};

struct ActionQueueManager;

// What ActionQueue::GetAction returns: a pointer to the oldest queued action, or null when the queue is empty
// (Ghidra: ActionRef, constructed by ActionRef::ActionRef at 0x000a1ec0).
struct ActionRef {
    ActionData *data;
};

// A consumer's queue of actions (Ghidra: ActionQueue, 0x974 bytes): the manager it is registered with, then a
// ring of 200 actions. A full ring drops its oldest action to make room.
class ActionQueue {
public:
    XBE_FIELDS(ActionQueue)

    // The constructor (0x0004f320): an empty ring, registered with the manager. The name is ignored on Xbox.
    ActionQueue *Construct(char *name);
    // The destructor (0x0004f1b0): unregisters the queue.
    void Destruct();

    bool IsEmpty();
    // Queues a copy of the action (the original takes an ActionData &). Always returns true.
    bool ReceiveAction(ActionData *action);
    // Drops the oldest action, if there is one.
    void PopAction();
    // Empties the queue.
    void Flush();
    // The oldest action, without removing it. MSVC returns ActionRef - a class with a constructor - through a
    // hidden result pointer, which the declaration spells out: the caller's buffer, filled and returned.
    ActionRef *GetAction(ActionRef *result);
};

// Hands every action to every registered queue (Ghidra: ActionQueueManager, 16 bytes): an MSVC
// std::vector<ActionQueue *> - the allocator's word, then begin, end and the end of the storage. There is one, a
// function-local static at 0x001e23f0, returned by GetActionQueueManager.
struct ActionQueueManager {
    uint32_t queuesAllocator;   // +0x00
    ActionQueue **queuesFirst;  // +0x04
    ActionQueue **queuesLast;   // +0x08
    ActionQueue **queuesEnd;    // +0x0c

    // The static, emptied the first time and its destructor registered with atexit.
    static ActionQueueManager *GetActionQueueManager();

    void RegisterQueue(ActionQueue *queue);
    void UnRegisterQueue(ActionQueue *queue);
    void FeedQueue(ActionData action);
    void FlushAllQueues();

    // The vector's compiled members. The linker folded identical copies, so other pointer vectors call Tidy and
    // FillQueuePointers too (the scheduler's, the collision system's, the static's destructor).
    // push_back (0x0004f830)
    void PushBack(ActionQueue *const *queue);
    // _Insert_n (0x0004f510): `count` copies of *value before `where`, growing the storage by half when full.
    void InsertN(ActionQueue **where, uint32_t count, ActionQueue *const *value);
    // _Xlen (0x0004f490): throws std::length_error("vector<T> too long").
    static void Xlen();
    // _Tidy (0x0004f400): frees the storage and empties the vector.
    void Tidy();
};
static_assert(sizeof(ActionQueueManager) == 0x10, "the manager is a vector, 16 bytes");

// std::fill over a range of pointers (Ghidra: maybe_memset_ptr2, 0x0004f3e0).
void FillQueuePointers(ActionQueue **first, ActionQueue **last, ActionQueue *const *value);
