#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"

// Game actions: the top of the input layer. IOModule polls the pads, maps each control through the current
// control configuration to an action id, and hands the result to the ActionQueueManager as an ActionData
// (action id, a source field, and the control's value). The manager copies every action into every registered
// ActionQueue; each consumer - the HUD (pause is action 0x47), the mission manager, the weapon manager, the
// world camera, the helicopter, the player's car - owns a queue and drains it in its own update with GetAction
// and PopAction.
//
// ActionData and the queue's ring buffer (ActionQueueRing, a name invented here: the PS2 build inlines it) are
// plain structs generated from Ghidra, embedded in ActionQueue. Both classes are overlay classes - see
// src/common/xbeClass.h.

class ActionQueueManager;

// What ActionQueue::GetAction returns: a pointer to the oldest queued action, or null when the queue is empty
// (Ghidra: ActionRef, constructed by ActionRef::ActionRef at 0x000a1ec0).
struct ActionRef {
    ActionData *data;
};

// A consumer's queue of actions (Ghidra: ActionQueue, 0x974 bytes): the manager it is registered with, then a
// ring of 200 actions. A full ring drops its oldest action to make room.
class ActionQueue {
public:
    XBE_FIELDS(ActionQueue)

    // The constructor (0x0004f320): an empty ring, registered with the manager. The name is ignored on Xbox.
    ActionQueue *Construct(char *name);
    // The destructor (0x0004f1b0): unregisters the queue.
    void Destruct();

    bool IsEmpty();
    // Queues a copy of the action (the original takes an ActionData &). Always returns true.
    bool ReceiveAction(ActionData *action);
    // Drops the oldest action, if there is one.
    void PopAction();
    // Empties the queue.
    void Flush();
    // The oldest action, without removing it. MSVC returns ActionRef - a class with a constructor - through a
    // hidden result pointer, which the declaration spells out: the caller's buffer, filled and returned.
    ActionRef *GetAction(ActionRef *result);
};

// Hands every action to every registered queue (Ghidra: ActionQueueManager, 16 bytes - an MSVC
// std::vector<ActionQueue *>: allocator byte, first, last, end). There is one, a function-local static at
// 0x001e23f0, returned by GetActionQueueManager.
class ActionQueueManager {
public:
    XBE_FIELDS(ActionQueueManager)

    // AUTOGEN
    static ActionQueueManager *GetActionQueueManager();

    void RegisterQueue(ActionQueue *queue);
    void UnRegisterQueue(ActionQueue *queue);
    void FeedQueue(ActionData action);
    void FlushAllQueues();

    // std::vector<ActionQueue *>::push_back, instantiated in the game (0x0004f830): grows the vector through
    // the game's allocator, which is why it is called rather than reimplemented.
    // AUTOGEN(0x0004f830)
    void PushBack(ActionQueue *const *queue);
};
