#pragma once

#include <stdint.h>

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"

// Game actions: the top of the input layer. IOModule polls the pads, maps each control through the current
// control configuration to an action id, and hands the result to the ActionQueueManager as an ActionData
// (action id, a source field, and the control's value). The manager copies every action into every registered
// ActionQueue; each consumer - the HUD (pause is action 0x47), the mission manager, the weapon manager, the
// world camera, the helicopter, the player's car - owns a queue and drains it in its own update with GetAction
// and PopAction.
//
// ActionData and the queue's ring buffer (ActionQueueRing, a name invented here: the PS2 build inlines it) are
// plain structs generated from Ghidra, embedded in ActionQueue, an overlay class - see src/common/xbeClass.h.

struct ActionQueueManager;

// What ActionQueue::GetAction returns: a pointer to the oldest queued action, or null when the queue is empty
// (Ghidra: ActionRef, constructed by ActionRef::ActionRef at 0x000a1ec0).
struct ActionRef {
    ActionData *data;
};

// A consumer's queue of actions (Ghidra: ActionQueue, 0x974 bytes): the manager it is registered with, then a
// ring of 200 actions. A full ring drops its oldest action to make room.
class ActionQueue {
public:
    XBE_FIELDS(ActionQueue)

    // The constructor (0x0004f320): an empty ring, registered with the manager. The name is ignored on Xbox.
    ActionQueue *Construct(char *name);
    // The destructor (0x0004f1b0): unregisters the queue.
    void Destruct();

    bool IsEmpty();
    // Queues a copy of the action (the original takes an ActionData &). Always returns true.
    bool ReceiveAction(ActionData *action);
    // Drops the oldest action, if there is one.
    void PopAction();
    // Empties the queue.
    void Flush();
    // The oldest action, without removing it. MSVC returns ActionRef - a class with a constructor - through a
    // hidden result pointer, which the declaration spells out: the caller's buffer, filled and returned.
    ActionRef *GetAction(ActionRef *result);
};

// Hands every action to every registered queue (Ghidra: ActionQueueManager, 16 bytes): an MSVC
// std::vector<ActionQueue *> - the allocator's word, then begin, end and the end of the storage. There is one, a
// function-local static at 0x001e23f0, returned by GetActionQueueManager.
struct ActionQueueManager {
    uint32_t queuesAllocator;   // +0x00
    ActionQueue **queuesFirst;  // +0x04
    ActionQueue **queuesLast;   // +0x08
    ActionQueue **queuesEnd;    // +0x0c

    // The static, emptied the first time and its destructor registered with atexit.
    static ActionQueueManager *GetActionQueueManager();

    void RegisterQueue(ActionQueue *queue);
    void UnRegisterQueue(ActionQueue *queue);
    void FeedQueue(ActionData action);
    void FlushAllQueues();

    // The vector's compiled members. The linker folded identical copies, so other pointer vectors call Tidy and
    // FillQueuePointers too (the scheduler's, the collision system's, the static's destructor).
    // push_back (0x0004f830)
    void PushBack(ActionQueue *const *queue);
    // _Insert_n (0x0004f510): `count` copies of *value before `where`, growing the storage by half when full.
    void InsertN(ActionQueue **where, uint32_t count, ActionQueue *const *value);
    // _Xlen (0x0004f490): throws std::length_error("vector<T> too long").
    static void Xlen();
    // _Tidy (0x0004f400): frees the storage and empties the vector.
    void Tidy();
};
static_assert(sizeof(ActionQueueManager) == 0x10, "the manager is a vector, 16 bytes");

// std::fill over a range of pointers (Ghidra: maybe_memset_ptr2, 0x0004f3e0).
void FillQueuePointers(ActionQueue **first, ActionQueue **last, ActionQueue *const *value);
