#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"
#include "InputMapping.hpp"

// The control configurations (Ghidra: InputConfigManager, 0x30 bytes; a function-local static at 0x001e455c).
// data/Control/Master.def lists the configurations of each type - one Driving (drivecfg.def) and eight POV
// (povcfg0..7.def, the shooting sections under autodrive) - and FrontEnd.def the mappings every configuration
// shares (the menus and cheats). At startup InitAndPreload loads them all, keeps each configuration's text and
// the pause menu's legend ids from its FRONTEND section, and makes the Driving mapping live on the active port's
// InputToAction. SetConfig switches it: SMissionManager::SetAutoDrive for POV and back, GHud::PauseOff for the
// choice made on the pause menu's controller page. The chosen configuration and the inversion go back to the
// action engine through the launch page. An overlay class - see src/common/xbeClass.h.

// XBE_NEEDS(ConfigInfo)

// InputConfigManager::ConfigType (the PS2 name).
enum : int {
    CONFIG_DRIVING = 0,
    CONFIG_POV     = 1,
    CONFIG_CURRENT = 2,   // GetCurrentConfig: whichever type is current
};

class InputConfigManager {
public:
    XBE_FIELDS(InputConfigManager)

    // The one manager (0x00050270).
    static InputConfigManager *Get();

    // Loads and parses every configuration and makes the Driving one live (at startup).
    void InitAndPreload();
    // Fills configInfos from Master.def.
    void ParseMasterConfigFile(char *text);
    // Reads a configuration's FRONTEND section (the pause menu's legend ids) into `info`.
    void ParseDefFileForFrontEnd(ConfigInfo *info, char *text);
    // Makes configuration `index` of `type` live (-1: the type's current one) and records it in the launch page.
    void SetConfig(int type, int index);
    // Frees the files and the configuration arrays (at the end of the mission).
    void Shutdown();

    void SetInverted(bool on);
    // Whether the player chose inverted look (read by the I and N mapping entries as they fire).
    bool IsInverted();
    int GetNumConfigs(int type);
    int GetCurrentConfig(int type);
    // The LOCALE id for a legend slot of a configuration (0..11 the buttons, 12 the description, 13 the title),
    // with the per-mission overrides the originals hard-code.
    int GetLocaleID(int type, int configIndex, int slot);
};
