#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"
#include "StringToNumber.hpp"

// A device's control mappings: one InputTable per control of the device, each a list of InputTableEntry
// {update method, threshold, action} read from the .def files (InputToAction::LoadParseDefFile). IOModule's
// SendGameMessages walks them (src/driving/engine/IOModule.cpp); InputConfigManager fills them
// (src/driving/engine/InputConfigManager.cpp). Overlay classes - see src/common/xbeClass.h.

class InputDevice;

// XBE_NEEDS(InputTableEntry)

// One control's entries (Ghidra: InputTable, 0x3c bytes): four inline, then a heap array once there are more.
class InputTable {
public:
    XBE_FIELDS(InputTable)

    // The constructor (0x000507a0) and destructor (0x000507c0).
    InputTable* Construct();
    void Destruct();
    // Room for four more entries (0x000507e0).
    void GrowArrayForOneElement();
};

// A device's mappings (Ghidra: InputToAction, 0x10 bytes).
class InputToAction {
public:
    XBE_FIELDS(InputToAction)

    // The constructor (0x00050860): a table per control of the device, and a name lookup over its controls.
    InputToAction* Construct(InputDevice *device);
    // The destructor (0x000509c0).
    void Destruct();
    // Empties every table, keeping their storage.
    void Reset();
    // Appends the mappings of a .def file to the tables: its lines after the first, up to FRONTEND or END.
    void LoadParseDefFile(char *text);
};

// The text after the next line break, or null (0x00050970).
void AdvanceFilePtr(char **text);

// The action id for a name, or 0x75 for an unknown one (0x0004f190).
int getActionID(char *name);
