#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"

// Input devices: the middle of the input layer. Each frame IOModule asks every device to poll (PollDevice), which
// copies this frame's values to the previous array and reads new ones from the pad library (src/driving/platform/
// Pad.cpp); then, for each control, it asks the device's DeviceScalars whether the control went down, came up or
// crossed a threshold, and turns the answers into actions (ActionQueueManager::FeedQueue).
//
// All three are overlay classes - see src/common/xbeClass.h.

// DeviceScalar::type (the PS2 sheet's DeviceScalarType).
enum : int {
    DEVICE_SCALAR_AXIS    = 0,   // a stick axis, -1 .. 1
    DEVICE_SCALAR_ANALOG  = 1,   // an analogue button or trigger, 0 .. 1
    DEVICE_SCALAR_DIGITAL = 2,   // a digital button, 0 or 1
};

// One control of a device (Ghidra: DeviceScalar, 0x34 bytes): its type, its name, and pointers to its value in the
// device's previous and current arrays. "Down" is 1 for a digital button and 0.5 or more otherwise; "up" is 0 for a
// digital button, under 0.5 for an analogue one and under -0.5 for an axis - so an axis is neither near the
// middle.
class DeviceScalar {
public:
    XBE_FIELDS(DeviceScalar)

    // The constructor (0x00050b80): everything zero.
    DeviceScalar* Construct();
    void InitializeDeviceScalar(int type, char *name, float *previous, float *current, float *extra1, float *extra2);

    bool isDown();
    bool isUp();
    bool isDownTransition();
    bool isUpTransition();
    bool isDownTransitionThreshold(float threshold);
    bool isUpTransitionThreshold(float threshold);
    // Whether the value has just come to rest within threshold of the middle.
    bool isCenteredTransition(float threshold);
};

// Base of the devices (Ghidra: InputDevice, 0x1c bytes, vtable 0x0018d9fc). The derived class points the scalars
// and the four value arrays at its own storage.
class InputDevice {
public:
    XBE_FIELDS(InputDevice)

    // The constructor (0x00050e10) and destructor (0x00050e30); the scalar deleting destructor (0x00050eb0).
    InputDevice* Construct(int port);
    void Destruct();
    InputDevice* DeletingDestructor(unsigned int flags);

    // Whether any control's value differs from last frame's.
    bool DeviceHasChanged();

    // Zeroes *value if it lies strictly between low and high (0x00050e80).
    static void DeadZoneChop(float *value, float low, float high);

    // The virtual methods IOModule calls, each through the device's own vtable (so reaching XBoxPadDevice's).
    // Slot 0: the scalar deleting destructor (flags bit 0: free the memory too).
    // VIRTUAL(0)
    InputDevice* Delete(unsigned int flags);
    // Slot 1: names and types the controls.
    // VIRTUAL(1)
    void Initialize();
    // Slot 2: reads the device's current values, last frame's becoming the previous ones.
    // VIRTUAL(2)
    void PollDevice();
    // Slot 3: how many controls the device has.
    // VIRTUAL(3)
    int GetNumDeviceScalar();
};

// An Xbox gamepad (Ghidra: XBoxPadDevice, 0x56c bytes, vtable 0x0018db38): 20 controls - four stick axes, eight
// analogue buttons (A, B, X, Y, black, white, the triggers), eight digital (the d-pad, START, BACK, the stick
// clicks) - and their four value arrays.
class XBoxPadDevice : public InputDevice {
public:
    XBE_FIELDS(XBoxPadDevice)

    // The constructor (0x00051d90), destructor (0x00051d80) and scalar deleting destructor (0x00051e60).
    XBoxPadDevice* Construct(int port);
    void Destruct();
    XBoxPadDevice* DeletingDestructor(unsigned int flags);

    // Names and types the 20 controls and points each at its values.
    void Initialize();
    // Last frame's values become the previous ones; this frame's are read from the pad library's record.
    void PollDevice();
    int GetNumDeviceScalar();
};
