#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"

// The input layer's manager (Ghidra: IOModule): it owns the devices and their control mappings, and each update
// polls them and turns what changed into actions for the ActionQueueManager (src/driving/engine/ActionQueue.hpp).
//
// How it is driven: Bond_StartUpSystem calls Initialize (the pad library, then the devices); InputConfigManager
// fills the mappings from Master.def and the current configuration's .def; GameLoop_StartUp calls
// EnableUpdating(true), which adds Update as a sync task run every 2 timer ticks from the main loop (25 Hz on PAL,
// 30 on NTSC). Update polls the pads, checks the active one is still plugged in, and has every device send its
// messages. Only the port in glbIFeedback (0x00244520, always 0) ever gets a device.
//
// Overlay classes - see src/common/xbeClass.h.

class InputDevice;

// The mapping entries' tables are generated from Ghidra (one InputTable per device control, each a small array
// of InputTableEntry: update method, threshold, action):
// XBE_NEEDS(InputTable)

// A device's control mappings (Ghidra: InputToAction, 0x10 bytes): one InputTable per control.
class InputToAction {
public:
    XBE_FIELDS(InputToAction)

    // The constructor (0x00050860): the tables, sized for the device's controls, and a name lookup over them.
    // AUTOGEN(0x00050860)
    InputToAction* Construct(InputDevice *device);
    // The destructor (0x000509c0).
    // AUTOGEN(0x000509c0)
    void Destruct();
};

// InputTableEntry::updateMethod - how a mapping entry decides to send its action (the table at 0x001b6fd0, the
// letters the .def files use).
enum : int {
    UPDATE_ON_CHANGE    = 0,   // U: whenever the control's value changes
    UPDATE_DOWN         = 1,   // +: on the down transition
    UPDATE_UP           = 2,   // -: on the up transition
    UPDATE_ABOVE        = 3,   // >: on crossing the entry's threshold upwards
    UPDATE_BELOW        = 4,   // <: on crossing it downwards
    UPDATE_CENTRED      = 5,   // =: on coming to rest within 0.2 of the middle
    UPDATE_IF_INVERTED  = 6,   // I: with the controls inverted
    UPDATE_NOT_INVERTED = 7,   // N: with them not inverted
    UPDATE_REPEAT_DOWN  = 8,   // R: on the down transition, then auto-repeating while down
    UPDATE_REPEAT_UP    = 9,   // M: the same on the "up" side (for an axis, below -0.5)
};

class IOModule {
public:
    XBE_FIELDS(IOModule)

    // The one IOModule, a function-local static at 0x001e45a0 (0x00051580).
    static IOModule *GetIOModule();

    void Initialize();
    void CreateDevices();
    // The sync task: a pass over the pads and devices when updating is enabled. Always returns 0.
    static int Update();
    void CheckUnplugged();
    void UpdateAllDevices();
    void SendGameMessages(InputDevice *device, InputToAction *mapping);
    // Sends every release action as if all the controls had been let go; used when the controls change hands.
    void ReleaseAllButtons();
    bool EnableUpdating(bool enable);
    void Release();
    void ReleaseDevices();
};
