#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"
#include "InputConfig.h"

// The input layer's manager (Ghidra: IOModule): it owns the devices and their control mappings, and each update
// polls them and turns what changed into actions for the ActionQueueManager (src/driving/engine/ActionQueue.hpp).
//
// How it is driven: Bond_StartUpSystem calls Initialize (the pad library, then the devices); InputConfigManager
// fills the mappings from Master.def and the current configuration's .def; GameLoop_StartUp calls
// EnableUpdating(true), which adds Update as a sync task run every 2 timer ticks from the main loop (25 Hz on PAL,
// 30 on NTSC). Update polls the pads, checks the active one is still plugged in, and has every device send its
// messages. Only the launch page's controller port (0x00244520, GameLoop.h) ever gets a device.
//
// Overlay classes - see src/common/xbeClass.h.

class InputDevice;

class IOModule {
public:
    XBE_FIELDS(IOModule)

    // The one IOModule, a function-local static at 0x001e45a0 (0x00051580).
    static IOModule *GetIOModule();

    void Initialize();
    void CreateDevices();
    // The sync task: a pass over the pads and devices when updating is enabled. Always returns 0.
    static int Update();
    void CheckUnplugged();
    void UpdateAllDevices();
    void SendGameMessages(InputDevice *device, InputToAction *mapping);
    // Sends every release action as if all the controls had been let go; used when the controls change hands.
    void ReleaseAllButtons();
    bool EnableUpdating(bool enable);
    void Release();
    void ReleaseDevices();
};
