#pragma once

#include <stdint.h>

#include "../autogenerated_layouts.h"
#include "../data/CoordConvert.h"

// ---------------------------------------------------------------------------------------------------------------
// The physics library's small helpers (the PS2 build's Util_* functions, 0x000bce10..0x000bd750): stepping and
// clamping, a basis from a direction, inertia tensors, Gaussian random numbers, perturbed directions, a
// direction's pole depth and longitude, character-map lookups, and rays against spheres - plus the two segment
// helpers the sphere test calls (which the collision queries call too), the region fit WCollider::Refresh calls
// with register arguments, and a vector's deallocation linked among them.
//
// Several return the value they leave on the x87 stack without rounding it to a float; those answer a double,
// which comes back the same way (in ST0, at double precision), so callers that keep computing see what the
// original's callers saw. The ones that return a structure by value take the caller's result pointer first and
// answer it, as the compiled code does.
// ---------------------------------------------------------------------------------------------------------------

// From current, a step of `step` towards target, not passing it (0x000bce10). Unrounded.
double Util_Step(float current, float target, float step);

// `bound` above `limit`, `-bound` below `-limit`, the value itself between (0x000bce50).
float Util_Bound(float value, float limit, float bound);

// A basis from a direction (0x000bce90): row 2 the direction normalised, row 0 the unit cross product of world up
// (0, 1, 0) with it, row 1 row 2 x row 0, row 3 (0, 0, 0, 1). Answers result.
MATRIX4* Util_GenerateMatrix(MATRIX4 *result, const Coord3 *direction);

// The inverse inertia tensor's diagonal of a body of the given mass and dimensions (0x000bcf40, Smackable's): a box,
// or, when sizeY is more than five times sizeX + sizeZ, a long cylinder. Answers result.
Coord3* Util_GenerateTensor(Coord3 *result, float mass, float sizeX, float sizeY, float sizeZ);

// The car's version (0x000bd030, PBondCar's; Ghidra: ComputeInverseInertia, the PS2 build's name is
// Util_GenerateCarTensor): a cylinder up to sizeZ 4, a box above, each halved. Answers result.
Coord3* Util_GenerateCarTensor(Coord3 *result, float mass, float sizeX, float sizeY, float sizeZ);

// A normally distributed random number, mean 0 and deviation 1, from the C runtime's rand (0x000bd130): the polar
// Box-Muller method, which makes two - the second is kept for the next call. Unrounded.
double Util_GaussRandom();

// A direction turned by yTurns about y, then by zTurns about z (0x000bd1e0). Answers result.
Coord3* Util_PerturbVector(Coord3 *result, float yTurns, float zTurns, const Coord4 *direction);

// A direction turned about y and then z by Gaussian random angles of deviation `spread` turns (0x000bd250).
// Answers result.
Coord3* Util_PerturbVector(Coord3 *result, const Coord4 *direction, float spread);

// A unit direction's depth from the top pole, 0 to 1, and its longitude in turns, 0 to 1 (0x000bd2e0).
void Util_VecToPoleDepthAndLong(const Coord3 *direction, float *depth, float *longitude);

// The character at (u, v), each 0 to 1, of a width x height map, rows of `width` characters (0x000bd390).
char Util_CharMapLookup(float u, float v, const char *map, int width, int height);

// to - from, and the inverse of its length squared (0 for a zero vector) (0x000bd3e0, no name of its own: the PS2
// build has it inline in Util_CollideRayWithSphere).
void Util_SegmentDirection(const Coord4 *from, const Coord4 *to, float *inverseLengthSquared, Coord4 *direction);

// value plus a Gaussian random fraction of it, of deviation `variance` (0x000bd450). Unrounded.
double Util_ApplyVariance(float value, float variance);

// The point of the segment start + t * direction, t in [0, 1], nearest `point`, given the direction's inverse
// length squared (0x000bd470, no name of its own; the collision queries call it too).
void Util_NearestPointOnSegment(const Coord4 *point, const Coord4 *start, float inverseLengthSquared,
                                const Coord4 *direction, Coord4 *nearest);

// Where a ray from outside a sphere first comes within it - the point of the ray's first 1000 units nearest the
// centre, when that is inside (0x000bd500). False from inside the sphere or when the ray misses.
bool Util_CollideRayWithSphere(const Coord4 *origin, const Coord4 *direction, const Coord4 *centre, float radius,
                               Coord3 *hit);

// The same against a sphere stretched by `stretch` along y (0x000bd5d0): y squeezed by 1 / stretch, tested, the hit's
// height scaled back.
bool Util_CollideRayWithStretchedSphere(const Coord4 *origin, const Coord4 *direction, const Coord4 *centre,
                                        float radius, float stretch, Coord3 *hit);

// The region a collider covers after moving (0x000bd690, WCollider::Refresh's, register arguments - FUN_000bd690
// is the adapter): not moved, the position and 1.1 x the radius; moved, the position plus 1.1 x the movement, and
// 1.1 x (radius + the movement's length, at most 1).
void Util_FitColliderRegion(uint8_t moved, const Coord4 *position, Coord4 *centre, float *regionRadius,
                            float radius, const Coord4 *previous);
void FUN_000bd690();

// std::allocator<T>::deallocate for the barrier lists' 40-byte entries (0x000bd730, BarrierList::InsertN's): back to
// the fast pool. Called as a member of the (empty) allocator; it never reads ECX.
void __stdcall BarrierList_Deallocate(void *block, int count);
