// The parts of the driving engine's static initialisation that are not generated: the weapon table's
// initialiser, the destructors the generated list registers that are more than a call, and the destructors of
// function-local statics that game code registers with atexit itself. StaticInitTable.cpp (generated by
// tools/static_init_driving.py) is the rest.
//
// None of the destructors here runs: the C runtime's exit, which calls what atexit registered, is never called.
// They are kept as the originals were so that what atexit holds means the same thing.

#include <stdint.h>
#include <string.h>

#include "../../helpers.h"
#include "StaticInit.h"
#include "UMemory.hpp"
#include "URefCounter.h"
#include "USingleton.h"
#include "../data/AttributeSet.h"
#include "../data/SymbolTable.h"
#include "../camera/CameraSpline.h"
#include "../eagl/GeoPrimState.h"
#include "../audio/Fader.h"             // FaderRefTree
#include "../audio/Mix.h"               // MixRefTree
#include "../audio/Stream.h"            // StreamRefTree
#include "../render/RSceneObj.hpp"
#include "../render/TextureContext.h"
#include "../world/RoadNav.h"
#include "../world/Targeting.h"

// ---- originals called by address


#define FUN_0004f400 ((void (__fastcall *)(void *, int))0x0004f400)
#define FUN_0012f820 ((void (__fastcall *)(void *, int))0x0012f820)

// ---- the weapon table

// The initialiser at 0x00158ef0: 658 stores of constants, which leave the table as kWeaponDefinitions. The first
// record is initialised data in the XBE, and the stores leave it as it was apart from fields they write with the
// same values, so the whole table can be written.
void InitWeaponDefinitions(void) {
    for (int i = 0; i < 32; i++)
        WeaponDefinitions[i] = kWeaponDefinitions[i];
}

// ---- destructors registered by the initialisers

void DestroyNodeList(NodeList *list, NodeListErase erase, uint32_t nodeSize) {
    void *after;
    void **head = list->head;
    erase(list, 0, &after, head != NULL ? *head : NULL, head);
    if (list->head != NULL)
        UMemory::FastFree(list->head, nodeSize);
    list->head = NULL;
    list->size = 0;
}

// The picker's target list and its ATargeting, both allocated by its constructor.
void DestroyGlobal_0023e1b0(void) {
    PointerList *list = TargetPicker.targets;
    PointerListNode *head = list->head;
    PointerListNode *after;
    list->Erase(&after, head != NULL ? head->next : NULL, head);
    list = TargetPicker.targets;
    if (list != NULL) {
        list->Destruct();
        OperatorDelete(list);
    }
    OperatorDelete(TargetPicker.targeting);
}

// ---- destructors of function-local statics, which game code registers with atexit when it first constructs them

// FUNC_AT(0x0015cd20)
void DestroyStatic_001dd9e8(void) {
    ((ModelInfoRefCounter *)0x001dd9e8)->Destruct();
}
// FUNC_AT(0x0015cd30)
void DestroyStatic_001dda04(void) {
    ((TextureInfoRefCounter *)0x001dda04)->Destruct();
}
// FUNC_AT(0x0015cd40)
void DestroyStatic_001dda14(void) {
    ((WeaponInfoRefCounter *)0x001dda14)->Destruct();
}
// FUNC_AT(0x0015cd50)
void DestroyStatic_001de820(void) {
    ((WRoadNav *)0x001de820)->Destruct();
}
// FUNC_AT(0x0015cde0)
void DestroyStatic_001e23f0(void) {
    FUN_0004f400((void *)0x001e23f0, 0);
}
// FUNC_AT(0x0015ce00)
void DestroyStatic_Empty(void) {
}
// FUNC_AT(0x0015ce10)
void DestroyStatic_001e47c0(void) {
    ((USingletonManager *)0x001e47c0)->Destruct();
}
// FUNC_AT(0x0015ce30)
void DestroyStatic_001e9294(void) {
    ((AttributeSet *)0x001e9294)->DestructThunk();
}
// FUNC_AT(0x0015ce40)
void DestroyStatic_001ebd60(void) {
    ((UCharNamespace *)0x001ebd60)->Destruct();
}
// FUNC_AT(0x0015ceb0)
void DestroyStatic_001ec4a4(void) {
    ((USingletonManager *)0x001ec4a4)->Destruct();
}
// The object at 0x001f25b0 needs no destructor: the original jumped to an empty function (dummyNullFunction).
// FUNC_AT(0x0015cec0)
void DestroyStatic_001f25b0(void) {
}
// FUNC_AT(0x0015ced0)
void DestroyStatic_001f25f4(void) {
    ((CarpFileRefTree *)0x001f25f4)->Destruct();
}
// FUNC_AT(0x0015cef0)
void DestroyStatic_001f2a34(void) {
    ((TextureContextRefTree *)0x001f2a34)->Destruct();
}
// FUNC_AT(0x0015cf60)
void DestroyStatic_00200f60(void) {
    ((EAGL::GeoPrimState *)0x00200f60)->Destruct();
}
// FUNC_AT(0x0015cfb0)
void DestroyStatic_00201790(void) {
    ((EAGL::GeoPrimState *)0x00201790)->Destruct();
}
// FUNC_AT(0x0015d070)
void DestroyStatic_0023e100(void) {
    ((RCameraSpline *)0x0023e100)->Destruct();
}
// FUNC_AT(0x0015d0d0)
void DestroyStatic_0023f330(void) {
    ((EAGL::GeoPrimState *)0x0023f330)->Destruct();
}
// FUNC_AT(0x0015d250)
void DestroyStatic_00243944(void) {
    ((MixRefTree *)0x00243944)->Destruct();
}
// FUNC_AT(0x0015d260)
void DestroyStatic_00243a88(void) {
    ((StreamRefTree *)0x00243a88)->Destruct();
}
// FUNC_AT(0x0015d2d0)
void DestroyStatic_00243af8(void) {
    ((FaderRefTree *)0x00243af8)->Destruct();
}
// FUNC_AT(0x0015d2f0)
void DestroyStatic_00243b08(void) {
    ((BankRefCounter *)0x00243b08)->Destruct();
}
// FUNC_AT(0x0015d300)
void DestroyStatic_00243b74(void) {
    FUN_0012f820((void *)0x00243b74, 0);
}
