// The parts of the driving engine's static initialisation that are not generated: the weapon table's
// initialiser, the destructors the generated list registers that are more than a call, and the destructors of
// function-local statics that game code registers with atexit itself. StaticInitTable.cpp (generated by
// tools/static_init_driving.py) is the rest.
//
// None of the destructors here runs: the C runtime's exit, which calls what atexit registered, is never called.
// They are kept as the originals were so that what atexit holds means the same thing.

#include <stdint.h>
#include <string.h>

#include "../../helpers.h"
#include "StaticInit.h"
#include "../eagl/GeoPrimState.h"

// ---- originals called by address

#define UMemory_FastFree ((void (__cdecl *)(void *block, uint32_t size))0x001147d0)
#define BuiltinDelete ((void (__cdecl *)(void *))0x001146e0)     // __builtin_delete (operator delete)
#define ListDestruct_00013540 ((void (__fastcall *)(void *, int))0x00013540)
#define ListErase_000ce900 ((void (__fastcall *)(NodeList *, int, void **, void *, void *))0x000ce900)

#define URefCounter_ModelInfo_Destruct ((void (__fastcall *)(void *, int))0x000182b0)
#define URefCounter_TextureInfo_Destruct ((void (__fastcall *)(void *, int))0x0001a880)
#define FUN_0001be60 ((void (__fastcall *)(void *, int))0x0001be60)
#define FUN_0004f400 ((void (__fastcall *)(void *, int))0x0004f400)
#define FUN_00059c30 ((void (__fastcall *)(void *, int))0x00059c30)
#define AttributeSet_Destruct ((void (__fastcall *)(void *, int))0x000752f0)
#define RCameraSpline_Destruct ((void (__fastcall *)(void *, int))0x0007a9b0)
#define FUN_000903a0 ((void (__fastcall *)(void *, int))0x000903a0)
#define FUN_00094ff0 ((void (__fastcall *)(void *, int))0x00094ff0)
#define WRoadNav_Destruct ((void (__fastcall *)(void *, int))0x000ca100)
#define UCharNamespace_Destruct ((void (__fastcall *)(void *, int))0x0011a810)
#define FUN_0011d580 ((void (__fastcall *)(void *, int))0x0011d580)
#define FUN_001235a0 ((void (__fastcall *)(void *, int))0x001235a0)
#define FUN_00125b90 ((void (__fastcall *)(void *, int))0x00125b90)
#define URefCounter_ABank_Destruct ((void (__fastcall *)(void *, int))0x001267f0)
#define FUN_0012f820 ((void (__fastcall *)(void *, int))0x0012f820)

// ---- the weapon table

// The initialiser at 0x00158ef0: 658 stores of constants, which leave the table as kWeaponDefinitions. The first
// record is initialised data in the XBE, and the stores leave it as it was apart from fields they write with the
// same values, so the whole table can be written.
void InitWeaponDefinitions(void) {
    for (int i = 0; i < 32; i++)
        WeaponDefinitions[i] = kWeaponDefinitions[i];
}

// ---- destructors registered by the initialisers

void DestroyNodeList(NodeList *list, NodeListErase erase, uint32_t nodeSize) {
    void *after;
    void **head = list->head;
    erase(list, 0, &after, head != NULL ? *head : NULL, head);
    if (list->head != NULL)
        UMemory_FastFree(list->head, nodeSize);
    list->head = NULL;
    list->size = 0;
}

// The object holds a list behind a pointer (+0x2c) and an ATargeting (+0x7c), both allocated by its constructor.
void DestroyGlobal_0023e1b0(void) {
    NodeList *list = (NodeList *)PTR_AT(0x0023e1dc);
    void **head = list->head;
    void *after;
    ListErase_000ce900(list, 0, &after, head != NULL ? *head : NULL, head);
    list = (NodeList *)PTR_AT(0x0023e1dc);
    if (list != NULL) {
        ListDestruct_00013540(list, 0);
        BuiltinDelete(list);
    }
    BuiltinDelete(PTR_AT(0x0023e22c));
}

// ---- destructors of function-local statics, which game code registers with atexit when it first constructs them

// FUNC_AT(0x0015cd20)
void DestroyStatic_001dd9e8(void) {
    URefCounter_ModelInfo_Destruct((void *)0x001dd9e8, 0);
}
// FUNC_AT(0x0015cd30)
void DestroyStatic_001dda04(void) {
    URefCounter_TextureInfo_Destruct((void *)0x001dda04, 0);
}
// FUNC_AT(0x0015cd40)
void DestroyStatic_001dda14(void) {
    FUN_0001be60((void *)0x001dda14, 0);
}
// FUNC_AT(0x0015cd50)
void DestroyStatic_001de820(void) {
    WRoadNav_Destruct((void *)0x001de820, 0);
}
// FUNC_AT(0x0015cde0)
void DestroyStatic_001e23f0(void) {
    FUN_0004f400((void *)0x001e23f0, 0);
}
// FUNC_AT(0x0015ce00)
void DestroyStatic_Empty(void) {
}
// FUNC_AT(0x0015ce10)
void DestroyStatic_001e47c0(void) {
    FUN_00059c30((void *)0x001e47c0, 0);
}
// FUNC_AT(0x0015ce30)
void DestroyStatic_001e9294(void) {
    AttributeSet_Destruct((void *)0x001e9294, 0);
}
// FUNC_AT(0x0015ce40)
void DestroyStatic_001ebd60(void) {
    UCharNamespace_Destruct((void *)0x001ebd60, 0);
}
// FUNC_AT(0x0015ceb0)
void DestroyStatic_001ec4a4(void) {
    FUN_00059c30((void *)0x001ec4a4, 0);
}
// The object at 0x001f25b0 needs no destructor: the original jumped to an empty function (dummyNullFunction).
// FUNC_AT(0x0015cec0)
void DestroyStatic_001f25b0(void) {
}
// FUNC_AT(0x0015ced0)
void DestroyStatic_001f25f4(void) {
    FUN_000903a0((void *)0x001f25f4, 0);
}
// FUNC_AT(0x0015cef0)
void DestroyStatic_001f2a34(void) {
    FUN_00094ff0((void *)0x001f2a34, 0);
}
// FUNC_AT(0x0015cf60)
void DestroyStatic_00200f60(void) {
    ((EAGL::GeoPrimState *)0x00200f60)->Destruct();
}
// FUNC_AT(0x0015cfb0)
void DestroyStatic_00201790(void) {
    ((EAGL::GeoPrimState *)0x00201790)->Destruct();
}
// FUNC_AT(0x0015d070)
void DestroyStatic_0023e100(void) {
    RCameraSpline_Destruct((void *)0x0023e100, 0);
}
// FUNC_AT(0x0015d0d0)
void DestroyStatic_0023f330(void) {
    ((EAGL::GeoPrimState *)0x0023f330)->Destruct();
}
// FUNC_AT(0x0015d250)
void DestroyStatic_00243944(void) {
    FUN_0011d580((void *)0x00243944, 0);
}
// FUNC_AT(0x0015d260)
void DestroyStatic_00243a88(void) {
    FUN_001235a0((void *)0x00243a88, 0);
}
// FUNC_AT(0x0015d2d0)
void DestroyStatic_00243af8(void) {
    FUN_00125b90((void *)0x00243af8, 0);
}
// FUNC_AT(0x0015d2f0)
void DestroyStatic_00243b08(void) {
    URefCounter_ABank_Destruct((void *)0x00243b08, 0);
}
// FUNC_AT(0x0015d300)
void DestroyStatic_00243b74(void) {
    FUN_0012f820((void *)0x00243b74, 0);
}
