#ifndef DRIVING_ENGINE_STATICINIT_H_
#define DRIVING_ENGINE_STATICINIT_H_

#include <stdint.h>

// The driving engine's C++ static initialisers: the constructors of its global objects and the globals computed
// at startup. The XBE lists them in the C++ initialiser table (0x001b3db0), which the C runtime's _cinit walked;
// RunStaticInitialisers (StaticInitTable.cpp, generated by tools/static_init_driving.py) does each entry's work
// in the same order, and our startup calls it in place of walking the table.

void RunStaticInitialisers(void);

// ---- the weapon table

// One of the driving engine's 32 weapons and gadgets (0x54 bytes, the table at 0x001c94d8). SWeaponManager::Reset
// (0x000badad) copies the table into the manager's own, then fills unk3C from the difficulty. The fields are
// named only as far as the values show.
struct WeaponDefinition {
    int32_t id;                       // +0x00, the record's index
    const char *name;                 // +0x04, "Rocket", "Q-Booster", ...
    int32_t textIds[3];               // +0x08, string ids; 0xbb8 (3000) where there is none
    uint32_t flags;                   // +0x14, SWeaponManager::Reset sets bit 0 of the first weapon's
    int32_t unk18;                    // +0x18
    int32_t unk1C;                    // +0x1c, 1 for most, 10, 30, 50 for the guns
    int32_t unk20;                    // +0x20, always unk1C's value
    int32_t unk24[4];                 // +0x24, -1000 in every record
    int32_t unk34;                    // +0x34, 10 to 5000
    uint8_t unk38;                    // +0x38, 0 or 1
    int32_t unk3C;                    // +0x3c, set by SWeaponManager::Reset
    int32_t unk40;                    // +0x40, 4 in every record
    const char *assetName;            // +0x44, "Boost", "smkscrn", "qlocate", ...; "" for some
    int32_t unk48[3];                 // +0x48
};
static_assert(sizeof(WeaponDefinition) == 0x54, "a weapon record is 0x54 bytes");

#define WeaponDefinitions ((WeaponDefinition *)0x001c94d8)   // [32]

// The table as its initialiser left it (StaticInitTable.cpp), and the initialiser that puts it in place.
extern const WeaponDefinition kWeaponDefinitions[32];
void InitWeaponDefinitions(void);

// ---- the destructors the initialisers register

// A global std::list as the game's compiler laid it out: the allocator's word, the head node (allocated by the
// list's constructor; its first word is the first element), the size.
struct NodeList {
    uint32_t allocator;
    void **head;
    uint32_t size;
};

// The list's erase(first, last), returning the iterator after the range through `result` (__thiscall).
typedef void (__fastcall *NodeListErase)(NodeList *list, int, void **result, void *first, void *last);

// A global list's destructor: erase every node, free the head node, clear the head and the size.
void DestroyNodeList(NodeList *list, NodeListErase erase, uint32_t nodeSize);

// The destructor of the object at 0x0023e1b0, built by FUN_000cebc0: the original thunk (0x0015d080) had it
// inline.
void DestroyGlobal_0023e1b0(void);

// The destructors of function-local statics that game code registers with atexit (StaticInit.cpp).
void DestroyStatic_001dd9e8(void);
void DestroyStatic_001dda04(void);
void DestroyStatic_001dda14(void);
void DestroyStatic_001de820(void);
void DestroyStatic_001e23f0(void);
void DestroyStatic_Empty(void);
void DestroyStatic_001e47c0(void);
void DestroyStatic_001e9294(void);
void DestroyStatic_001ebd60(void);
void DestroyStatic_001ec4a4(void);
void DestroyStatic_001f25b0(void);
void DestroyStatic_001f25f4(void);
void DestroyStatic_001f2a34(void);
void DestroyStatic_00200f60(void);
void DestroyStatic_00201790(void);
void DestroyStatic_0023e100(void);
void DestroyStatic_0023f330(void);
void DestroyStatic_00243944(void);
void DestroyStatic_00243a88(void);
void DestroyStatic_00243af8(void);
void DestroyStatic_00243b08(void);
void DestroyStatic_00243b74(void);

#endif // DRIVING_ENGINE_STATICINIT_H_
