#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"

// A name -> number table over a caller's array of {number, string} entries, ended by a null string (Ghidra:
// StringToNumber, 0x10 bytes; EA's SupportPS2.lib). A table of 31 entries or more keeps a copy sorted by name and
// one by number, and looks names up by binary search; a smaller one is searched in order. Names are
// case-sensitive. An overlay class - see src/common/xbeClass.h.
//
// The game has two at file scope - the action names (0x001e23e0, 117 entries, sorted) and the mapping update
// methods (0x001e4590) - and every InputToAction makes one over its device's control names.

// XBE_NEEDS(StringToNumberEntry)

class StringToNumber {
public:
    XBE_FIELDS(StringToNumber)

    // The constructor (0x00119f50) and destructor (0x0011a020, non-deleting).
    StringToNumber* Construct(StringToNumberEntry *entries);
    void Destruct();

    // The entry's number for `name`, or -1.
    int ConvertStringToNumber(char *name);
    // The index of `name` in the sorted copy, or -1 (tables of 31 or more only).
    int BinarySearch(char *name);
};

#define ActionNames ((StringToNumber *)0x001e23e0)
#define UpdateMethodNames ((StringToNumber *)0x001e4590)
