#ifndef DRIVING_ANIM_SKELETON_H_
#define DRIVING_ANIM_SKELETON_H_

// ActSkeleton and ActSkeletonDatabase: the actors' skeletons, each an EAGLAnim::Skeleton loaded from its object
// file, with the pose and matrix buffers posing it uses. See Skeleton.cpp.

#include <stddef.h>
#include <stdint.h>

#include "../autogenerated_layouts.h"   // MATRIX4
#include "../data/CoordConvert.h"       // Coord4
#include "../eagl/anim/Skeleton.h"      // Skeleton

class DynamicLoader;

class ActSkeleton {                   // 0x24 ("ActSkeleton")
public:
    void *file;                       // +0x00 the object file
    DynamicLoader *loader;            // +0x04
    Skeleton *skeleton;               // +0x08 the object's "Skeleton" symbol
    float *stillPose;                 // +0x0c 12 floats a bone
    float *pose;                      // +0x10 12 floats a bone
    MATRIX4 *matrices;                // +0x14 one a bone
    int32_t rootBone;                 // +0x18 the bone "Root.Root", or -1
    int32_t weaponBones[2];           // +0x1c "Root.Weapon" (else "Root.RWeapon") and "Root.Clip"; -1 for none

    ActSkeleton* Construct(const char *path);                                   // 0x000198b0
    void Destruct();                                                            // 0x00019c60

    // The index of the bone `name` (a "Bone" symbol of the object), or -1.
    int GetBoneIndex(const char *name);                                         // 0x000197f0
    void GetStillPose();                                                        // 0x00019820 into stillPose
    void GetStillPose(float *pose);                                             // 0x00019830
    int GetNumBones();                                                          // 0x00019ac0

    // out = from blended towards to by t, a bone at a time: the quaternions slerped, the translations lerped
    // only for the root bone unless allTranslations; the scales are left alone.
    void BlendBones(float t, const float *from, const float *to, float *out, bool allTranslations);   // 0x00019ad0

    // A quaternion, and a quaternion and translation, blended in place towards the targets.
    static void BlendQ(Coord4 *rotation, const Coord4 *target, float t);        // 0x00019850
    static void BlendQT(Coord4 *rotation, Coord4 *translation, const Coord4 *targetRotation,
                        const Coord4 *targetTranslation, float t);              // 0x00019b80
};
static_assert(sizeof(ActSkeleton) == 0x24, "an ActSkeleton is 0x24 bytes");

// out = (b - a) * t + a on three floats, the translation blend above (invented name; Ghidra never made it a
// function; EAGLAnim's pose blender called it).
void LerpTranslation(float t, const float *a, const float *b, float *out);      // 0x00019870

class ActSkeletonDatabase {           // 0x24 ("ActSkeletonDatabase")
public:
    enum { kSkeletonCount = 9 };

    ActSkeleton *skeletons[kSkeletonCount];   // +0x00 data\actors\skeleton\0skel.o .. 8skel.o

    ActSkeletonDatabase* Construct();                                           // 0x00019bd0
    void Destruct();                                                            // 0x00019cd0
};
static_assert(sizeof(ActSkeletonDatabase) == 0x24, "an ActSkeletonDatabase is 0x24 bytes");

// The skeletons' shared buffer of a matrix a bone, registered with EAGL as "EAGLAnimationBuffer" (the skin matrices
// ActPoser::Skin makes)
#define AnimationBuffer (*(MATRIX4 **)0x001dd9fc)

#endif // DRIVING_ANIM_SKELETON_H_
