#pragma fp_contract(off)

#include "Draw.h"

#include <stddef.h>
#include <bit>

#include "Materials.h"
#include "../../helpers.h"
#include "../autogenerated_layouts.h"     // MATRIX4
#include "../engine/UMemory.hpp"          // OperatorNew
#include "../platform/X87.h"              // RoundToInt

// ---------------------------------------------------------------------------------------------------------------
// ColourConvertXBoxToPS2, SimpleDraw and Draw (0x00075c40..0x00076810), ported from the listing. The x87 code keeps
// the original's order and roundings.
// ---------------------------------------------------------------------------------------------------------------

#define DrawModelMatrix (*(MATRIX4 **)0x001e92d8)
#define DrawZ FLOAT_AT(0x001c3e28)

namespace {

// A batch's vertices (the statics of a batched draw, the name is ours). The colours are a function-local static
// array constructed on first use: their guard's bit 0 says they have been.
struct VertexBatch {
    Coord4 texCoords[128];              // +0x0000
    Coord4 positions[128];              // +0x0800
    int32_t count;                      // +0x1000
    uint32_t unknown1004[3];
    EAGL::TAR *texture;                 // +0x1010 the one every vertex in the batch has
    uint32_t unknown1014[3];
    PackedColour colours[128];          // +0x1020
    uint32_t coloursGuard;              // +0x1220
};
static_assert(offsetof(VertexBatch, count) == 0x1000 && offsetof(VertexBatch, texture) == 0x1010 &&
              offsetof(VertexBatch, colours) == 0x1020 && offsetof(VertexBatch, coloursGuard) == 0x1220,
              "VertexBatch layout");

#define QuadBatch (*(VertexBatch *)0x001e9420)       // DrawBatchedTexturedQuad's
#define SpriteBatch (*(VertexBatch *)0x001ea650)     // DrawBatchedSprite's

// A batch is drawn once it holds more than this many vertices
constexpr int32_t kBatchLimit = 120;

constexpr uint32_t kAlphaBlendingOn = 1;  // GeoPrimState::SetTransparencyMethod's

constexpr float kByteToUnit = 1.0f / 255.0f;
constexpr float kLumaGain = 1.0811f;
static_assert(std::bit_cast<uint32_t>(kByteToUnit) == 0x3b808081, "1/255");
static_assert(std::bit_cast<uint32_t>(kLumaGain) == 0x3f8a617c, "1.0811");

void ConstructColours(VertexBatch &batch) {
    if (!(batch.coloursGuard & 1)) {
        batch.coloursGuard |= 1;
        for (int i = 0; i < 128; i++)
            batch.colours[i].Construct();
    }
}

// Draws the batch's vertices as triangles with its texture
void DrawBatch(VertexBatch &batch) {
    TexturedRequests[TexturedRequestIndex]->positions.SetData(batch.positions);
    TexturedRequests[TexturedRequestIndex]->colours.SetData(batch.colours);
    TexturedRequests[TexturedRequestIndex]->texCoords.SetData(batch.texCoords);
    TexturedRequests[TexturedRequestIndex]->texture.SetData(batch.texture);
    SimpleTexturedMaterial->Draw(kTriangleList, batch.count, NULL);
}

// The batch drawn and restarted for `texture` when it changes or the batch is full
void StartBatch(VertexBatch &batch, EAGL::TAR *texture) {
    if (texture != batch.texture || batch.count > kBatchLimit) {
        if (batch.texture != NULL)
            DrawBatch(batch);
        batch.count = 0;
        batch.texture = texture;
    }
}

void AddBatchVertex(VertexBatch &batch, int index, const Coord4 *position, const Coord4 *texCoord, uint32_t colour) {
    batch.positions[index] = *position;
    batch.texCoords[index] = *texCoord;
    batch.colours[index].value = colour;
}

// A screen rectangle's corners as a strip: top left, top right, bottom left, bottom right
void RectangleCorners(Vec4 *corners, float x, float y, float width, float height) {
    float right = x + width;
    float bottom = y + height;
    corners[0] = {x, y, DrawZ, 1.0f};
    corners[1] = {right, y, DrawZ, 1.0f};
    corners[2] = {x, bottom, DrawZ, 1.0f};
    corners[3] = {right, bottom, DrawZ, 1.0f};
}

}  // namespace

// FUNC_AT(0x00075c40)
uint32_t ColourConvertXBoxToPS2(uint32_t colour) {
    double r = (int32_t)((colour >> 16) & 0xff) * (double)kByteToUnit;
    double g = (int32_t)((colour >> 8) & 0xff) * (double)kByteToUnit;
    double b = (int32_t)(colour & 0xff) * (double)kByteToUnit;

    float i = (float)(r * 0.596 - g * 0.275 - b * 0.321);
    float q = (float)(r * 0.212 - g * 0.523 + b * 0.311);
    double y = (g * 0.587 + r * 0.299) + b * 0.114;
    y = y * kLumaGain - 0.075;
    if (y > 1.0)
        y = 1.0;
    if (y < 0.0)
        y = 0.0;

    double i2 = i * 1.115;
    double q2 = q * 1.115;
    float red = (float)((i2 * 0.956 + q2 * 0.621) + y);
    float green = (float)(y - i2 * 0.272 - q2 * 0.647);
    float blue = (float)((y - i2 * 1.105) + q2 * 1.702);

    // Green is kept as a float between the clamp and the scale, red and blue as doubles
    double redClamped = red > 1.0f ? 1.0 : red;
    if (redClamped < 0.0)
        redClamped = 0.0;
    float greenClamped = green > 1.0f ? 1.0f : green;
    if (greenClamped < 0.0f)
        greenClamped = 0.0f;
    double blueClamped = blue > 1.0f ? 1.0 : blue;
    if (blueClamped < 0.0)
        blueClamped = 0.0;

    uint32_t red8 = RoundToInt((float)(redClamped * 255.0f));
    uint32_t green8 = RoundToInt((float)(greenClamped * 255.0));
    uint32_t blue8 = RoundToInt((float)(blueClamped * 255.0f));
    return (((red8 << 8) | green8) << 8) | (colour & 0xff000000) | blue8;
}

// FUNC_AT(0x00075e80)
void SimpleDraw::Init() {
    void *memory = OperatorNew(sizeof(USimpleMaterial));
    SimpleMaterial = memory != NULL ? static_cast<USimpleMaterial *>(memory)->Construct() : NULL;
    memory = OperatorNew(sizeof(USimpleTexturedMaterial));
    SimpleTexturedMaterial = memory != NULL ? static_cast<USimpleTexturedMaterial *>(memory)->Construct() : NULL;
}

// FUNC_AT(0x00075f20)
void SimpleDraw::InitThunk() {
    Init();
}

// FUNC_AT(0x00075f30)
void Draw::SetModelMatrix(MATRIX4 *matrix) {
    DrawModelMatrix = matrix;
}

// FUNC_AT(0x00075f40)
void Draw::SetZDepth(float z) {
    DrawZ = z;
}

// FUNC_AT(0x00075f50)
void Draw::SetZDepthNear() {
    DrawZ = 1.0f;
}

// FUNC_AT(0x00075f60)
void Draw::DrawSprite(float x, float y, float width, float height, uint32_t colour, const SpriteTexCoords *texCoords, EAGL::TAR *texture) {
    uint32_t colours[4] = {colour, colour, colour, colour};
    Vec4 positions[4];
    RectangleCorners(positions, x, y, width, height);
    const Coord4 &topLeft = texCoords->topLeft;
    const Coord4 &bottomRight = texCoords->bottomRight;
    Vec4 uvs[4] = {
        {topLeft.x, topLeft.y, 1.0f, 1.0f},
        {bottomRight.x, topLeft.y, 1.0f, 1.0f},
        {topLeft.x, bottomRight.y, 1.0f, 1.0f},
        {bottomRight.x, bottomRight.y, 1.0f, 1.0f},
    };
    TexturedRequests[TexturedRequestIndex]->positions.SetData(positions);
    TexturedRequests[TexturedRequestIndex]->colours.SetData(colours);
    TexturedRequests[TexturedRequestIndex]->texCoords.SetData(uvs);
    TexturedRequests[TexturedRequestIndex]->texture.SetData(texture);
    SimpleTexturedMaterial->Draw(kTriangleStrip, 4, DrawModelMatrix);
}

// FUNC_AT(0x000760e0)
void Draw::DrawBox(float x, float y, float width, float height, uint32_t colour) {
    uint32_t colours[4] = {colour, colour, colour, colour};
    Vec4 positions[4];
    RectangleCorners(positions, x, y, width, height);
    SimpleRequests[SimpleRequestIndex]->positions.SetData(positions);
    SimpleRequests[SimpleRequestIndex]->colours.SetData(colours);
    SimpleMaterial->Draw(kTriangleStrip, 4, DrawModelMatrix);
}

// FUNC_AT(0x000761c0)
void Draw::DrawQuadC(const Coord4 *positions, const uint32_t *colours) {
    SimpleRequests[SimpleRequestIndex]->positions.SetData(positions);
    SimpleRequests[SimpleRequestIndex]->colours.SetData(colours);
    SimpleMaterial->Draw(kTriangleStrip, 4, DrawModelMatrix);
}

// FUNC_AT(0x00076200)
void Draw::SetNormalBlendMode(EAGL::GeoPrimState *material) {
    material->SetTransparencyMethod(kAlphaBlendingOn);
    material->SetAlphaBlendMode(kBlendNormal);
}

// FUNC_AT(0x00076220)
void Draw::SetAdditiveBlendMode(EAGL::GeoPrimState *material) {
    material->SetTransparencyMethod(kAlphaBlendingOn);
    material->SetAlphaBlendMode(kBlendAdditive);
}

// FUNC_AT(0x00076240)
PackedColour* PackedColour::Construct() {
    value = 0;
    return this;
}

// FUNC_AT(0x00076250)
void Draw::DrawSprite(float x, float y, float width, float height, uint32_t colour, EAGL::TAR *texture) {
    SpriteTexCoords whole = {{0.0f, 0.0f, 1.0f, 0.0f}, {1.0f, 1.0f, 1.0f, 0.0f}};
    DrawSprite(x, y, width, height, colour, &whole, texture);
}

// FUNC_AT(0x000762d0)
void Draw::DrawQuad(const Coord4 *positions, uint32_t colour) {
    uint32_t colours[4] = {colour, colour, colour, colour};
    SimpleRequests[SimpleRequestIndex]->positions.SetData(positions);
    SimpleRequests[SimpleRequestIndex]->colours.SetData(colours);
    SimpleMaterial->Draw(kTriangleStrip, 4, DrawModelMatrix);
}

// FUNC_AT(0x00076330)
void Draw::DrawBatchedTexturedQuad(const Coord4 *p0, const Coord4 *p1, const Coord4 *p2, const Coord4 *p3,
                                   uint32_t colour, const Coord4 *texCoords, EAGL::TAR *texture) {
    VertexBatch &batch = QuadBatch;
    ConstructColours(batch);
    StartBatch(batch, texture);
    if (texture == NULL)
        return;
    int n = batch.count;
    AddBatchVertex(batch, n, p0, &texCoords[0], colour);
    AddBatchVertex(batch, n + 1, p1, &texCoords[1], colour);
    AddBatchVertex(batch, n + 2, p2, &texCoords[2], colour);
    AddBatchVertex(batch, n + 3, p1, &texCoords[1], colour);
    AddBatchVertex(batch, n + 4, p2, &texCoords[2], colour);
    AddBatchVertex(batch, n + 5, p3, &texCoords[3], colour);
    batch.count = n + 6;
}

// Only the texture coordinates' u and v are written.
// FUNC_AT(0x000765e0)
void Draw::DrawBatchedSprite(float x, float y, float width, float height, uint32_t colour,
                             const SpriteTexCoords *texCoords, EAGL::TAR *texture) {
    VertexBatch &batch = SpriteBatch;
    ConstructColours(batch);
    StartBatch(batch, texture);
    if (texture == NULL)
        return;
    Vec4 corners[4];
    RectangleCorners(corners, x, y, width, height);
    const Coord4 &topLeft = texCoords->topLeft;
    const Coord4 &bottomRight = texCoords->bottomRight;
    const float us[4] = {topLeft.x, bottomRight.x, topLeft.x, bottomRight.x};
    const float vs[4] = {topLeft.y, topLeft.y, bottomRight.y, bottomRight.y};
    int n = batch.count;
    for (int i = 0; i < 4; i++) {
        batch.positions[n + i] = corners[i];
        batch.texCoords[n + i].x = us[i];
        batch.texCoords[n + i].y = vs[i];
        batch.colours[n + i].value = colour;
    }
    batch.count = n + 4;
}
