#include "Materials.h"

#include "../../helpers.h"
#include "../autogenerated_layouts.h"     // MATRIX4
#include "../eagl/EaglGlobals.h"          // EaglMalloc, EaglFree
#include "../eagl/Loader.h"               // DynamicLoader
#include "../eagl/Model.h"                // EAGL::DynamicModel
#include "../eagl/RenderMethod.h"
#include "../platform/RealMath.h"         // VU0_MATRIX4Init

// ---------------------------------------------------------------------------------------------------------------
// USimpleMaterial, USimpleTexturedMaterial and UVolatileMaterial (0x0011bb60..0x0011c5c0), ported from the listing.
// See Materials.h.
// ---------------------------------------------------------------------------------------------------------------

// The render methods the requests' methods are children of (static initialisers')
#define MatDebugMethod ((EAGL::RenderMethod *)0x0024b07c)               // "HB_RM = MatDebug"
#define MatVolatileTextureMethod ((EAGL::RenderMethod *)0x0024b0b0)     // "HB_RM = MatVolatileTexture"

namespace {

constexpr uint32_t kGouraud = 1;          // GeoPrimState::SetShading's

// A request is a GeoPrim: its render method, then the parameters
EAGL::GeoPrim *AsGeoPrim(void *request) {
    return static_cast<EAGL::GeoPrim *>(request);
}

EAGL::DynamicModel *NewDynamicModel() {
    void *memory = EaglMalloc(sizeof(EAGL::DynamicModel), "EAGL::DynamicModel new");
    return memory != NULL ? static_cast<EAGL::DynamicModel *>(memory)->Construct() : NULL;
}

// Draws a ring's current request and moves the ring on
void DrawRequest(EAGL::DynamicModel *model, MATRIX4 *transform) {
    if (transform == NULL) {
        model->Draw();
    } else {
        model->SetModelMatrix(transform->mtx[0]);
        model->Draw();
        VU0_MATRIX4Init(model->GetModelMatrix());
    }
}

void NextRequest(uint32_t &index) {
    if (++index >= kMaterialRequests)
        index = 0;
}

// Frees a ring's models and requests (each request with its render method)
template <class Request>
void FreeRing(EAGL::DynamicModel **models, Request **requests) {
    for (int i = 0; i < kMaterialRequests; i++) {
        EAGL::DynamicModel *model = models[i];
        if (model != NULL) {
            model->Destruct();
            EaglFree(model, sizeof(EAGL::DynamicModel));
        }
        models[i] = NULL;
        Request *request = requests[i];
        if (request != NULL) {
            EAGL::RenderMethod *method = request->method;
            if (method != NULL) {
                method->Destruct();
                EaglFree(method, sizeof(EAGL::RenderMethod));
            }
            EaglFree(request, sizeof(Request));
        }
        requests[i] = NULL;
    }
}

// The textured rings' requests are set up alike once made
void SetUpTexturedRing(EAGL::DynamicModel **models, TexturedGeoPrim **requests) {
    for (int i = 0; i < kMaterialRequests; i++) {
        requests[i]->vertexCount.count = 1;
        requests[i]->vertexCount.data = NULL;
        requests[i]->state.count = 1;
        requests[i]->state.data = NULL;
        requests[i]->texture.count = 1;
        requests[i]->texture.data = NULL;
        models[i]->AddGeoPrim(AsGeoPrim(requests[i]));
    }
}

}  // namespace

// ---- the requests

// FUNC_AT(0x0011be40)
SimpleGeoPrim* SimpleGeoPrim::Construct() {
    method = NewChildRenderMethod(MatDebugMethod);
    state.data = NULL;
    state.count = 0;
    vertexCount.data = NULL;
    vertexCount.count = 0;
    bool found;
    void *matrix = DynamicLoader::GetRegisteredVar("EAGL::ViewPort::gpModelViewProjectionMatrix", &found);
    positions.data = NULL;
    positions.count = 0;
    colours.data = NULL;
    colours.count = 0;
    modelViewProjection.SetData(matrix);
    modelViewProjection.count = 1;
    return this;
}

// FUNC_AT(0x0011c380)
TexturedGeoPrim* TexturedGeoPrim::ConstructVolatile() {
    method = NewChildRenderMethod(MatVolatileTextureMethod);
    state.data = NULL;
    state.count = 0;
    texture.data = NULL;
    texture.count = 0;
    vertexCount.data = NULL;
    vertexCount.count = 0;
    bool found;
    void *matrix = DynamicLoader::GetRegisteredVar("EAGL::ViewPort::gpModelViewProjectionMatrix", &found);
    positions.data = NULL;
    positions.count = 0;
    colours.data = NULL;
    colours.count = 0;
    texCoords.data = NULL;
    texCoords.count = 0;
    modelViewProjection.SetData(matrix);
    modelViewProjection.count = 1;
    return this;
}

// ---- USimpleMaterial

// FUNC_AT(0x0011bb60)
USimpleMaterial* USimpleMaterial::Construct() {
    GeoPrimState::Construct();
    SetCullEnable(false);
    SetShading(kGouraud);
    SetTextureEnable(false);
    SetAlphaTestEnable(false);
    SetAlphaBlendMode(kBlendNormal);
    vertexCount = 0;
    unknown54[0] = 0;
    unknown54[1] = 0;
    unknown54[2] = 0;
    return this;
}

// FUNC_AT(0x0011bbe0)
void USimpleMaterial::Destruct() {
    GeoPrimState::Destruct();
}

// FUNC_AT(0x0011bbf0)
void USimpleMaterial::Draw(int primitive, int count, MATRIX4 *transform) {
    vertexCount = count;
    SetPrimitiveType(primitive);
    SimpleGeoPrim *request = SimpleRequests[SimpleRequestIndex];
    request->colours.count = count;
    request->positions.count = count;
    request->state.SetData(this);
    request->vertexCount.SetData(&vertexCount);
    DrawRequest(SimpleModels[SimpleRequestIndex], transform);
    NextRequest(SimpleRequestIndex);
}

// FUNC_AT(0x0011bee0)
void USimpleMaterial::Init() {
    if (SimpleRequests[0] != NULL)
        return;
    for (int i = 0; i < kMaterialRequests; i++) {
        void *memory = EaglMalloc(sizeof(SimpleGeoPrim), "EAGL::GeoPrim new");
        SimpleRequests[i] = memory != NULL ? static_cast<SimpleGeoPrim *>(memory)->Construct() : NULL;
        SimpleModels[i] = NewDynamicModel();
    }
    for (int i = 0; i < kMaterialRequests; i++) {
        SimpleRequests[i]->vertexCount.count = 1;
        SimpleRequests[i]->vertexCount.data = NULL;
        SimpleRequests[i]->state.count = 1;
        SimpleRequests[i]->state.data = NULL;
        SimpleModels[i]->AddGeoPrim(AsGeoPrim(SimpleRequests[i]));
    }
}

// FUNC_AT(0x0011c100)
void USimpleMaterial::Shutdown() {
    FreeRing(SimpleModels, SimpleRequests);
}

// ---- USimpleTexturedMaterial

// FUNC_AT(0x0011bcd0)
USimpleTexturedMaterial* USimpleTexturedMaterial::Construct() {
    GeoPrimState::Construct();
    SetCullEnable(false);
    SetShading(kGouraud);
    SetTextureEnable(true);
    SetAlphaTestEnable(false);
    SetAlphaBlendMode(kBlendNormal);
    vertexCount = 0;
    unknown54[0] = 0;
    unknown54[1] = 0;
    unknown54[2] = 0;
    return this;
}

// FUNC_AT(0x0011bd50)
void USimpleTexturedMaterial::Draw(int primitive, int count, MATRIX4 *transform) {
    vertexCount = count;
    SetPrimitiveType(primitive);
    TexturedGeoPrim *request = TexturedRequests[TexturedRequestIndex];
    request->colours.count = count;
    request->positions.count = count;
    request->texCoords.count = count;
    request->state.SetData(this);
    request->vertexCount.SetData(&vertexCount);
    DrawRequest(TexturedModels[TexturedRequestIndex], transform);
    NextRequest(TexturedRequestIndex);
}

// FUNC_AT(0x0011bfe0)
void USimpleTexturedMaterial::Init() {
    if (TexturedRequests[0] != NULL)
        return;
    for (int i = 0; i < kMaterialRequests; i++) {
        void *memory = EaglMalloc(sizeof(TexturedGeoPrim), "EAGL::GeoPrim new");
        TexturedRequests[i] = memory != NULL ? static_cast<TexturedGeoPrim *>(memory)->Construct() : NULL;
        TexturedModels[i] = NewDynamicModel();
    }
    SetUpTexturedRing(TexturedModels, TexturedRequests);
}

// FUNC_AT(0x0011c180)
void USimpleTexturedMaterial::Shutdown() {
    FreeRing(TexturedModels, TexturedRequests);
}

// ---- UVolatileMaterial

// FUNC_AT(0x0011c210)
UVolatileMaterial* UVolatileMaterial::Construct() {
    GeoPrimState::Construct();
    SetCullEnable(false);
    SetShading(kGouraud);
    SetTextureEnable(true);
    SetAlphaTestEnable(false);
    SetAlphaBlendMode(kBlendNormal);
    vertexCount = 0;
    unknown54[0] = 0;
    unknown54[1] = 0;
    unknown54[2] = 0;
    return this;
}

// FUNC_AT(0x0011c290)
void UVolatileMaterial::Draw(int primitive, int count, MATRIX4 *transform) {
    vertexCount = count;
    SetPrimitiveType(primitive);
    TexturedGeoPrim *request = VolatileRequests[VolatileRequestIndex];
    request->colours.count = count;
    request->positions.count = count;
    request->texCoords.count = count;
    request->state.SetData(this);
    request->vertexCount.SetData(&vertexCount);
    DrawRequest(VolatileModels[VolatileRequestIndex], transform);
    NextRequest(VolatileRequestIndex);
}

// FUNC_AT(0x0011c430)
void UVolatileMaterial::Init() {
    if (VolatileRequests[0] != NULL)
        return;
    for (int i = 0; i < kMaterialRequests; i++) {
        void *memory = EaglMalloc(sizeof(TexturedGeoPrim), "EAGL::GeoPrim new");
        VolatileRequests[i] = memory != NULL ? static_cast<TexturedGeoPrim *>(memory)->ConstructVolatile() : NULL;
        VolatileModels[i] = NewDynamicModel();
    }
    SetUpTexturedRing(VolatileModels, VolatileRequests);
}

// FUNC_AT(0x0011c540)
void UVolatileMaterial::Shutdown() {
    FreeRing(VolatileModels, VolatileRequests);
}

// ---- all three

// FUNC_AT(0x0011c0f0)
void InitAllSimpleMaterials() {
    USimpleMaterial::Init();
    USimpleTexturedMaterial::Init();
    UVolatileMaterial::Init();
}

// FUNC_AT(0x0011c200)
void ShutdownAllSimpleMaterials() {
    USimpleMaterial::Shutdown();
    USimpleTexturedMaterial::Shutdown();
    UVolatileMaterial::Shutdown();
}
