#ifndef DRIVING_RENDER_RENDERER_H_
#define DRIVING_RENDER_RENDERER_H_

// ---------------------------------------------------------------------------------------------------------------
// The renderer (Ghidra: RRenderer, one instance at fgRenderer): EAGL's device, render context and full-screen
// viewport, the screen's resolution, the frame bracket and the screen capture, the debug font, and two draw groups
// that hold the translucent instances deferred to the end of a view. RRenderSharedData sets the lighting up per
// view port, per world instance and per scene object as the model draws ask. The instance draws pick an article's
// model by distance, set the lighting up for it and draw it with its effects, or keep it for its draw group when it
// is in another pass; their shadow maps are loaded per track. See Renderer.cpp.
// ---------------------------------------------------------------------------------------------------------------

#include <stddef.h>
#include <stdint.h>

#include "../autogenerated_layouts.h"     // MATRIX4
#include "../data/CoordConvert.h"         // Coord3, Coord4

namespace CARP {
class Instance;
struct AnimInfo;
}
namespace EAGL {
struct Device;
struct Model;
struct RenderContext;
struct ViewPort;
}
class RSceneObj;
class RViewCamera;
struct ReverseDrawEntry;                 // camera/DirectorQueue.h
struct ReverseDrawList;
struct FNTXFont;                          // eagl/EaglFont.h
struct ArticleEffect;                     // world/World.h
struct ProcAnimState;                     // world/World.h
struct WorldArticle;                      // world/World.h

// The draws a group defers (Ghidra: RDrawGroup, one word): camera/DirectorQueue.h's reverse draw list, allocated
// by the constructor under the name "RReverseDrawList".
class RDrawGroup {
public:
    ReverseDrawList *translucent;       // +0x00

    RDrawGroup* Construct();                                                                    // 0x0007cf40
    void Destruct();                                                                            // 0x0007cae0
    // Draws the kept instances in the order they came, and empties the list
    void FlushDrawLists();                                                                      // 0x0007c9e0
    void AddToTranslucentList(const ReverseDrawEntry *draw);                                      // 0x0007cfa0
};
static_assert(sizeof(RDrawGroup) == 4, "a draw group is one pointer");

// The renderer (0x90 bytes, FastAlloc'd by Init under "RRenderer").
class RRenderer {
public:
    // videoMode: ConfigureRes sets 0, or 2 for a wide screen; the constructor tests for 3
    enum VideoMode : int32_t {
        kVideoNormal = 0,
        kVideoLetterbox = 1,            // RRenderHigh: a single view's extents are the middle three quarters
        kVideoWide = 2,
        kVideoMode3 = 3,
    };

    uint32_t unknown00;
    RViewCamera *currentView;           // +0x04 the view being drawn (RViewCamera::SetRenderCamera's); EndView clears it
    RDrawGroup drawGroups[2];           // +0x08
    RDrawGroup *currentDrawGroup;       // +0x10 drawGroups[0] from the constructor on
    uint32_t cpuFeatures;               // +0x14 CPU_detect's
    uint32_t unknown18;                 // +0x18 zero
    uint8_t unknown1C;                  // +0x1c the constructor's third argument
    uint8_t screenCapturePending;       // +0x1d EndFrame saves the frame to a .tga
    uint8_t alphaWrites;                // +0x1e Enable/DisableAlphaWrites
    uint8_t unknown1F;
    uint32_t unknown20;                 // +0x20 cleared by RPlayerViewCamera::ConfigureView
    uint32_t frameCount;                // +0x24 EndFrame counts the frames; RRenderHigh::RestartTrackRender clears it
    uint8_t unknown28[8];
    Coord4 cameraPosition;              // +0x30 the view's camera's, w 1
    int32_t screenWidth;                // +0x40
    int32_t screenHeight;               // +0x44
    int32_t videoMode;                  // +0x48 VideoMode
    uint8_t widescreen;                 // +0x4c 16:9
    uint8_t presentFlag100;             // +0x4d RenderContext::SetPresentFlag100 at construction; ConfigureRes clears it
    uint8_t unknown4E[2];
    float unknown50;                    // +0x50 1; unknown50 / unknown54 scales RRenderHigh's AspectScale
    float unknown54;                    // +0x54 1
    float fieldOfViewScale;             // +0x58 1
    int32_t ps2Mipmap;                  // +0x5c "PS2 mipmap"; -128 from the constructor
    EAGL::Device *device;               // +0x60
    EAGL::RenderContext *renderContext; // +0x64
    EAGL::ViewPort *viewPort;           // +0x68 the full screen, in pixels, orthographic
    FNTXFont *debugFont;                // +0x6c FONT_create's
    void *debugFontData;                // +0x70 "data/render/debug.xfn"
    uint8_t framePending;               // +0x74 a frame has ended since the last Flush
    uint8_t unknown75[0x1b];

    // The two pointer arguments are not read; Render_InitLibRender passes an uninitialised stack buffer and 0
    RRenderer* Construct(void *unused1, int unused2, bool unknown1C);                           // 0x0007d2a0
    void Destruct();                                                                            // 0x0007d670
    static RRenderer* Init(void *unused1, int unused2, bool unknown1C);                         // 0x0007d5e0
    static void Shutdown();                                                                     // 0x0007d740

    void ConfigureRes();                                                                        // 0x0007cfb0
    void LoadDebugFont();                                                                       // 0x0007d560
    void FlushDrawLists();                                                                      // 0x0007d020
    // The view being drawn, which is forgotten
    RViewCamera* EndView();                                                                     // 0x0007d030
    void StartFrame();                                                                          // 0x0007d060
    void EndFrame();                                                                            // 0x0007d5b0
    // Two empty frames, if a frame has ended since the last Flush or `force`
    void Flush(bool force);                                                                     // 0x0007d070
    // Each answers whether alpha writes were already on
    bool EnableAlphaWrites();                                                                   // 0x0007d0b0
    bool DisableAlphaWrites();                                                                  // 0x0007d0e0
    void DoScreenCapture();                                                                     // 0x0007d110
    // The original calls FUN_00013c80, the same code as FnDefaultAnimBank::Init
    void SetCurrentView(RViewCamera *view) { currentView = view; }
};
static_assert(sizeof(RRenderer) == 0x90, "RRenderer is 0x90 bytes");
static_assert(offsetof(RRenderer, currentDrawGroup) == 0x10 && offsetof(RRenderer, alphaWrites) == 0x1e &&
              offsetof(RRenderer, cameraPosition) == 0x30 && offsetof(RRenderer, screenWidth) == 0x40 &&
              offsetof(RRenderer, widescreen) == 0x4c && offsetof(RRenderer, fieldOfViewScale) == 0x58 &&
              offsetof(RRenderer, renderContext) == 0x64 && offsetof(RRenderer, framePending) == 0x74,
              "RRenderer layout");

#define fgRenderer (*(RRenderer **)0x001ebff4)

// Makes the renderer, the simple draw's materials and the random generator
void Render_InitLibRender();                                                                    // 0x0007d710

// The lighting's per-draw setup (Ghidra: RRenderSharedData; statics only). The model draws call one of the
// SendPer*Instance functions by the article's render type before each model, through a table.
class RRenderSharedData {
public:
    static void Init();                                                                         // 0x0007e190
    // Answers the old setting
    static bool SetVehiclesAllowed(bool allowed);                                               // 0x0007e1a0
    // Forgets the scene object the lighting was last set up for
    static void MarkAsDirty();                                                                  // 0x0007e1b0
    static void SendPerViewPort();                                                              // 0x0007e1c0
    static void SendPerWorldInstance();                                                         // 0x0007e1f0
    // A world position's brightness from the track's shadow maps, by its instance's shadow record; unrounded
    static double GetShadowBrightness(Coord3 position, int instanceIndex);                      // 0x0007e200
    static void SendPerObjectInstance(CARP::Instance *instance, RSceneObj *sceneObj);           // 0x0007e2b0
    static void SendPerCarInstance(CARP::Instance *instance, RSceneObj *sceneObj);              // 0x0007e310
};

// ---- the instance draws

// What the model draws call before each model, by the article's render type
typedef void (*RenderTypeSetup)(CARP::Instance *instance, RSceneObj *sceneObj);

// The instance draws. An instance with kWorldInstanceSceneObj is skipped (its scene object draws it). `distance` is
// the view distance the model is picked by; `sceneObj` goes to the render type's setup.
//
// The model for the distance, set up for and drawn: the core of DrawGroupDrawModel, which takes the instance in EDX
// and the article in EDI (the name is ours)
void DrawArticleModel(CARP::Instance *instance, const WorldArticle *article, const MATRIX4 *transform,
                      float distance, RSceneObj *sceneObj);
// The article's effects that draw with its model (its glares): the core of DrawGroupDrawEffects, which takes the
// article in EAX and the transform in EDI (the name is ours)
void DrawArticleEffects(const WorldArticle *article, const MATRIX4 *transform, float distance);
void DrawGroupDrawModel();              // naked: EDX instance, EDI article, the rest on the stack
void DrawGroupDrawEffects();            // naked: EAX article, EDI transform, the distance on the stack
// A draw group's kept draw; `unused` is passed 0
void DrawGroupDrawInstance(const MATRIX4 *transform, CARP::Instance *instance, uint32_t distance,
                           RSceneObj *sceneObj, int unused);                                    // 0x0007ddd0
// The instance placed by its proc-anim function under `transform` and drawn, or kept for the end of the view when
// its article draws in another pass than `pass`
void DrawInstance(CARP::Instance *instance, const MATRIX4 *transform, ProcAnimState *procAnims, float distance,
                  RSceneObj *sceneObj, int pass);                                               // 0x0007de30
// The instance where it stands, at its own view distance (the world's draw passes and the sky)
void QuickDrawInstance(CARP::Instance *instance, ProcAnimState *procAnims);                     // 0x0007df10
// DrawInstance in pass 2 on `count` instances in a row, or on the ones `indices` picks
void DrawInstanceList(CARP::Instance *instances, const MATRIX4 *transform, ProcAnimState *procAnims, uint32_t count,
                      float distance, RSceneObj *sceneObj);                                     // 0x0007df90
void DrawIndexedInstanceList(CARP::Instance *instances, const uint16_t *indices, const MATRIX4 *transform,
                             ProcAnimState *procAnims, uint32_t count, float distance,
                             RSceneObj *sceneObj);                                              // 0x0007dfe0

// The distance from the view's camera to the instance less `radius`, at least 0, times the view's LOD multiplier;
// unrounded. GetInstanceViewDistance takes the radius from the instance's packed size.
double GetArticleViewDistance(const CARP::Instance *instance, float radius);                    // 0x0007dc00
double GetInstanceViewDistance(const CARP::Instance *instance);                                 // 0x0007dc40

// ---- the track's shadow maps

// A shadow map image in the track's _S.xsh file: 8-bit samples (the name is ours)
struct ShadowMapImage {
    uint32_t type;                      // +0x00
    int16_t width;                      // +0x04
    int16_t height;                     // +0x06
    uint32_t unknown08;
    uint32_t flags;                     // +0x0c
    uint8_t pixels[1];                  // +0x10 rows SHAPE_rowbytes apart
};

// A render instance's shadow record (16 bytes, the name is ours), by the high half of the instance's +0x2c word:
// where a world position falls in which shadow map.
struct ShadowMapInfo {
    float offsetU;                      // +0x00
    int32_t image;                      // +0x04 the image's index
    float offsetV;                      // +0x08
    float scale;                        // +0x0c from world units to the image's 0..1
};

// Points the instances at the track's shadow records and loads its shadow maps ("data\track\<track>_S.xsh",
// images "0000", "0001", ... up to the first missing)
void RInstanceRender_SetShadowInformation(const ShadowMapInfo *info);                           // 0x0007daf0
// No shadow maps: an all-zero record and the default texture
void RInstanceRender_SetDefaultShadowInformation();                                             // 0x0007dbc0
// A shadow map's bilinear sample at (u, v) in pixels, mapped to (sample - 1) / 14; unrounded
double GetTextureVal(float u, float v, const ShadowMapImage *image);                            // 0x0007e040


#endif // DRIVING_RENDER_RENDERER_H_
