#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"

// The glare manager (Ghidra: RGlareManager, 0x3440 bytes; one instance, made by RGlareManager::Init at
// 0x0008b850). An overlay class - see src/common/xbeClass.h. Glares are the camera-facing sprites on lights:
// brake lights, lamps, the emitters on the laser grid, the sun's flare. Each frame the model draw queues one for
// every glare node it passes (AddModelGlare), other effects queue their own (AddGlare - the sun's lens flare,
// GFX effects with a 'gg' tag), and DrawGlares draws the lot and empties the queue.
//
// Its fields are Ghidra's: the queue glares[128] and glareCount, the enabled flag, and the 80 glare types
// (types[80], loaded from the "Render:Glare" tuning database: halo and spike textures, colours, sizes, spin, Z
// bias). The first pilot of the driving-engine injection framework: see docs/driving-injection-framework.md.

struct MATRIX4;

// Glare::flags, from AddModelGlare and GlareBlinkBrightness.
enum : uint32_t {
    GLARE_DIRECTIONAL   = 0x0020,   // fades with the angle to the camera (brake lights face backwards)
    GLARE_BLINKS        = 0x0400,   // brightness follows the blink parameters
    GLARE_BLINK_SHAPED  = 0x0800,   // ... as a triangle wave rather than a sawtooth
    GLARE_BLINK_PULSE   = 0x4000,   // ... or, with GLARE_BLINK_SHAPED, a pulse with a dip at the peak
};

class RGlareManager {
public:
    XBE_FIELDS(RGlareManager)

    // Queues a glare as given - the sun's flare and effects' glares (0x000a9c10).
    void AddGlare(Glare *glare, int unused);

    // Queues a model's glare node: blinks, fades with distance and, if directional, with the angle to the
    // camera (0x000a9aa0).
    void AddModelGlare(Glare *node, MATRIX4 *transform, float distance);

    // Draws every queued glare as two camera-facing quads and empties the queue (0x000aa5d0).
    // AUTOGEN
    void DrawGlares(bool twoD);
};
