#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"

// A drawable object in the world (Ghidra: RSceneObj, 0x40 bytes; the size WWorld::Open and WWorld::Reset allocate
// under that name). An overlay class - see src/common/xbeClass.h. Virtual, with its vtable at 0x00191be0:
// slot 0 the scalar deleting destructor, slot 2 Render, slot 3 an update that re-poses it from its instance data.
//
// Of its fields only three are understood so far: the vtable, the instance data it was built from (+0x0c, a
// 64-byte record the constructor copies), and the flags byte at +0x1f, whose bit 0 is "visible". The rest are
// padding until Ghidra names them.
class RSceneObj {
public:
    XBE_FIELDS(RSceneObj)

    // Set and clear the "visible" bit (0x0008db40, 0x0008db30).
    void Show();
    void Hide();
};

// A scene object with a transform of its own (0x80 bytes; allocated under this name by Newton's constructor,
// ESpawnSmackable::Process and three others). It derives from RSceneObj and adds one MATRIX4 at +0x40: every
// allocation site copies the identity matrix there, runs RSceneObj's constructor, and replaces the vtable with its
// own (0x0018a398), which overrides only the destructor. Ghidra records the base as a first field named
// super_RSceneObj, and the generated layout checks that this class derives from it.
class RAutonomousObj : public RSceneObj {
public:
    XBE_FIELDS(RAutonomousObj)
};
