#pragma once

#include "../../common/xbeClass.h"
#include "../autogenerated_layouts.h"

// A drawable object in the world (Ghidra: RSceneObj, 0x40 bytes; the size WWorld::Open and WWorld::Reset allocate
// under that name). An overlay class - see src/common/xbeClass.h. Virtual, with its vtable at 0x00191be0 (19
// slots): slot 0 the scalar deleting destructor, 2 Render, 3 RenderSimple, 14 UpdatePosition (re-poses it from its
// instance data), 15 TriggerFX, 18 ResolveObjectData.
//
// The full 0x40-byte layout is in Ghidra (every field sits 4 bytes after its PS2 offset: GCC puts the vtable
// pointer last, MSVC first). The ones used here: the vtable, a pointer to the CARP::Instance it was built from
// (+0x0c), and the flags byte at +0x1f, whose bit 0 is "visible" (bit 3 draw-last, bit 4 is-a-vehicle).
class RSceneObj {
public:
    XBE_FIELDS(RSceneObj)

    // Set and clear the "visible" bit (0x0008db40, 0x0008db30).
    void Show();
    void Hide();
};

// A scene object with a transform of its own (0x80 bytes; allocated under this name by Newton's constructor,
// ESpawnSmackable's destructor and three others). It derives from RSceneObj and adds one MATRIX4 at +0x40: every
// allocation site copies the identity matrix there, runs RSceneObj's constructor, and replaces the vtable with its
// own (0x0018a398), which overrides only the destructor. Ghidra records the base as a first field named
// super_RSceneObj, and the generated layout checks that this class derives from it.
class RAutonomousObj : public RSceneObj {
public:
    XBE_FIELDS(RAutonomousObj)
};
