#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "../anim/AnimEngine.h"         // Handle; data/Carp.h: CARP::Instance, CARP::BaseDesc
#include "../autogenerated_layouts.h"   // MATRIX4
#include "../data/CoordConvert.h"       // Coord3, Coord4
#include "../data/RCARPFile.h"
#include "../engine/URefCounter.h"      // RefCounterTree
#include "../../common/xbeOverload.h"   // XbeVirtual
#include "../../helpers.h"

// ---------------------------------------------------------------------------------------------------------------
// RSceneObj (0x40 bytes, vtable 0x00191be0): a drawable object in the world - the proc-anim objects the world makes,
// the vehicles, weapons and the physics objects' models. It draws a list of CARP instances (an RAnimEngine handle's
// copies of them) through its source instance's frame, is filed under a node of the scene tree, which the culling
// walks, and plays its article's effects (glares, lights, the gallery's effects). RAutonomousObj (0x80 bytes) adds
// a CARP::Instance of its own for the source instance. See RSceneObj.cpp.
//
// The vtable stays the game's: RSceneObj declares no `virtual`, and calls to virtual methods go through the
// object's vtable (the *Virtual helpers). Slots: 0 the scalar deleting destructor, 2 Render, 3 RenderSimple,
// 4 RenderShadow, 5 RenderDeferredEffects, 7 TransformPointToWorldSpace, 8 TransformMatrixToWorldSpace,
// 9 GetRenderOffset, 10 SetProcAnimState, 11 SetEventDynamicData, 13 GetVelocity, 14 UpdatePosition,
// 15 TriggerFX, 17 PostLoad, 18 ResolveObjectData.
// ---------------------------------------------------------------------------------------------------------------

class UGroup;
struct ArticleEffect;
struct CachedDrawInfo;
struct PhysicsObject;
struct ProcAnimState;
struct RPathHandle;
struct WMapNode;
struct WTargetable;

// The warning beside a provisional port: code no shipped data reaches, ported from the listing without a test.
inline void SceneObjUntested(const char *what) {
    printf("[render] WARNING: %s ran - a provisional port that no shipped data reaches, UNTESTED. Check what it "
           "computes against the original.\n", what);
    fflush(stdout);
}

#define SCENEOBJ_UNTESTED(what) \
    do { \
        static bool warned_; \
        if (!warned_) { \
            warned_ = true; \
            SceneObjUntested(what); \
        } \
    } while (0)

// The vtable's slots by Ghidra's names (the game's tables: RSceneObj 0x00191be0, RAutonomousObj 0x0018a398)
struct RSceneObj_vtbl {
    void *scalar_deleting_destructor;   // 0
    void *SetViewDrawList;              // 1
    void *Render;                       // 2
    void *RenderSimple;                 // 3
    void *RenderShadow;                 // 4
    void *RenderDeferredEffects;        // 5
    void *TransformToWorldSpace;        // 6
    void *TransformPointToWorldSpace;   // 7
    void *TransformMatrixToWorldSpace;  // 8
    void *GetRenderOffset;              // 9
    void *SetProcAnimState;             // 10
    void *SetEventDynamicData;          // 11
    void *TriggerIlluminate;            // 12
    void *GetVelocity;                  // 13
    void *UpdatePosition;               // 14
    void *TriggerFX;                    // 15
    void *Debug;                        // 16
    void *PostLoad;                     // 17
    void *ResolveObjectData;            // 18
};
static_assert(sizeof(RSceneObj_vtbl) == 0x4c, "the scene object's vtable has 19 slots");

// What AddCollisionInfo gathers in one simulation tick (0x20 bytes, operator new): the sums of the two vectors
// it is handed, and how many
struct SceneObjCollisionInfo {
    Coord3 centreSum;           // +0x00
    uint32_t tick;              // +0x0c the tick the sums are of
    Coord3 extentsSum;          // +0x10
    uint32_t count;             // +0x1c
};
static_assert(sizeof(SceneObjCollisionInfo) == 0x20, "the collision sums are 0x20 bytes");

class RSceneObj {
public:
    // flags
    enum Flags : uint8_t {
        kVisible = 0x01,            // Show/Hide; only a visible object is drawn
        kFarScaled = 0x02,          // every instance has instance flag 0x01 or 0x40: the culling's far test at 0.3
        kStatic = 0x04,             // its source instance has flag 0x08: filed under the root, no far test
        kDrawLast = 0x08,           // drawn with the deferred objects; its article's byte +0x1e is 1
        kVehicle = 0x10,
    };

    // TriggerFX's types
    enum FXType : int32_t {
        kFXOn = 0,                  // TriggerEffects on, by zone
        kFXOnById = 1,              // ... by effect id
        kFXOff = 2,
        kFXOffById = 3,
        kFXSuppress = 4,
        kFXSuppressById = 5,
        kFXDamageEffects = 9,       // DamageEffects with the zones added
        kFXDamage = 10,             // the animation systems sent kStimulusDamage in the zones newly damaged
    };

    RSceneObj_vtbl *vtable;             // +0x00
    RSceneObj *next;                    // +0x04 the next object filed under the same node of the scene tree
    RSceneObj *prev;                    // +0x08
    void *sourceInstance;               // +0x0c the CARP::Instance it is placed by (Instance())
    void *baseDesc;                     // +0x10 the CARP::BaseDesc of its instances' article (Desc())
    RCARPFile *carpFile;                // +0x14 Load's, counted by URefCounter<RCARPFile>
    WMapNode *mapNode;                  // +0x18 the scene tree node it is filed under
    uint8_t renderTypeIndex;            // +0x1c
    uint8_t variation;                  // +0x1d UseArticle's and SetVariation's
    uint8_t brightness;                 // +0x1e 100 at construction
    uint8_t flags;                      // +0x1f Flags
    uint16_t damagedZones;              // +0x20 TriggerFX kFXDamage's
    uint16_t damageEffectZones;         // +0x22 TriggerFX kFXDamageEffects'
    uint32_t effectDecayTime;           // +0x24 the tick DecayEffects is due; 0 none
    PhysicsObject *physics;             // +0x28 SetPhysics's: it moves the object
    Handle *animHandle;                 // +0x2c the instances drawn, their animations and effects
    RPathHandle *pathHandle;            // +0x30 the path engine's handle of its instance
    WTargetable *target;                // +0x34 EnableTarget's
    SceneObjCollisionInfo *collisionInfo;   // +0x38
    const char *name;                   // +0x3c UseInstanceList's, "<<unknown>>" without one

    CARP::Instance *Instance() const { return static_cast<CARP::Instance *>(sourceInstance); }
    CARP::BaseDesc *Desc() const { return static_cast<CARP::BaseDesc *>(baseDesc); }
    // The article's model group (its description's first word)
    UGroup *ModelGroup() const { return reinterpret_cast<UGroup *>(uintptr_t(Desc()->model.value)); }

    RSceneObj* Construct(CARP::Instance *instance);                                             // 0x0008eec0
    void Destruct();                                                                            // 0x000905a0
    RSceneObj* Delete(unsigned flags);          // the scalar deleting destructor, vtable slot 0 // 0x000908b0

    // ---- loading
    // The symbol callback Load and PreLoad register: the loading object's ResolveObjectData
    static void* ResolveData(const char *name, bool *found);                                    // 0x0008d6b0
    // vtable slot 18: answers nothing
    void* ResolveObjectData(const char *name, bool *found);                                     // 0x0008d6d0
    // Loads the CARP file (once for all its users) and uses its article
    void Load(const char *directory, const char *file, const char *label, uint32_t article);    // 0x00090a60
    static void PreLoad(const char *directory, const char *file, const char *label);            // 0x000904c0
    static void PurgePreloaded(const char *directory, const char *file);                        // 0x00090560
    // The model's instance list 'in  ' of the index (or the first), or a copy of the source instance; false if
    // neither has an article
    bool UseArticle(UGroup *model, uint32_t article);                                           // 0x000908d0
    void UseInstanceList(CARP::Instance *instances, int count, ProcAnimState *states, bool initialEffects,
                         const char *name);                                                     // 0x00090660
    // One instance of another object's list, placed at `transform`
    void UseInstance(RSceneObj *source, uint32_t index, const MATRIX4 *transform, uint8_t procAnimType,
                     uint16_t procAnimIndex);                                                   // 0x00090820
    // The article again, at the same variation
    void Reset();                                                                               // 0x00090a40
    // The model's instance list of the variation copied over the handle's, keeping their proc-anim fields
    bool SetVariation(uint32_t variation);                                                      // 0x0008d760

    // ---- the scene tree and the culling
    void SetMapNode(WMapNode *node);                                                            // 0x0008dc00
    // Starts the culling's walk over the scene objects filed under a list's visible nodes
    static void PrepareSceneObjsForCulling(CachedDrawInfo *list);                               // 0x0008d830
    // The walk's next object (its address; -1 at the end), its bounding circle and the culling's tests
    static int GetNextSceneObjCullInfo(Coord4 *sphere, float *height, bool *checkFar, float *farScale);   // 0x0008d860
    static void SetSceneObjectCull(int item, bool culled, float distance);                      // 0x0008f000
    // Into this frame's draw lists, if visible and the lists are not full
    void SetNowVisible();                                                                       // 0x0008dbc0
    static void RenderAllNormal();                                                              // 0x0008d9f0
    static void RenderAllDrawLast();                                                            // 0x0008da30
    static void RenderAllDeferredEffects();                                                     // 0x0008da60
    // Deletes every object filed under the node
    static void DestroySceneObjectList(WMapNode *node);                                         // 0x0008da90
    static void DestroyAll();                                                                   // 0x0008dac0
    void InitializeLighting();                                                                  // 0x0008f050
    static void InitializeSceneObjectListLighting(WMapNode *node);                              // 0x0008fac0
    static void InitializeAllLighting();                                                        // 0x0008fae0

    // ---- drawing
    void Render();                      // vtable slot 2                                        // 0x0008f9f0
    void RenderSimple();                // vtable slot 3                                        // 0x0008f930
    double GetViewDistance();           // answered unrounded                                   // 0x0008ed50
    // The model's view draw list 'vd  ' of the index (its data and count), NULL if none
    void* GetViewDrawList(uint32_t index, uint32_t *count);                                     // 0x0008db50

    // ---- position
    void GetTransform(MATRIX4 *transform);                                                      // 0x0008dc60
    void GetPosition(Coord3 *position);                                                         // 0x0008dc90
    void SetTransform(const MATRIX4 *transform);    // only without physics                     // 0x0008dcb0
    float GetRenderOffset();            // vtable slot 9: none                                  // 0x0008dce0
    // vtable slot 14: follows the physics, refiles the object and relights it
    void UpdatePosition(bool update);                                                           // 0x0008f270
    void SetPhysics(PhysicsObject *physics);                                                    // 0x0008f580
    Coord3* GetVelocity();              // vtable slot 13; NULL if neither physics nor path      // 0x0008e1a0
    void EnableTarget();                                                                        // 0x0008f160
    // The instance's article's animation system id, 0 for none
    uint32_t GetInstanceSystemID(uint32_t index);                                               // 0x0008dcf0
    // The instance's frame (in the world's with `world`) and its system id
    uint32_t GetInstancePosition(uint32_t index, MATRIX4 *transform, bool world);               // 0x0008dd20
    uint32_t TransformPointByInstancePosition(uint32_t index, Coord4 *point, bool world);       // 0x0008ddf0
    uint32_t TransformMatrixByInstancePosition(uint32_t index, MATRIX4 *transform, bool world); // 0x0008dee0
    // The instance among the object's that `instance` (an instance of its model's list) corresponds to
    CARP::Instance* ConvertInstanceToLocal(CARP::Instance *instance);                           // 0x0008edd0

    // ---- size and collision
    void GetBoundingDimensions(Coord4 *halfExtents);    // x, y and z                            // 0x0008dfd0
    float ComputeBoundingRadius();                                                              // 0x0008e010
    float GetBoundingRadius();                                                                  // 0x0008f500
    void ScaleBoundingRadius(float scale);                                                      // 0x0008f550
    void* GetCollisionGeometry(uint32_t *count);                                                // 0x0008e060
    uint32_t GetNumBones();                                                                     // 0x0008e080
    // The bone's index plus one, 0 if the skeleton has no such bone
    int GetBoneIndex(const char *name);                                                         // 0x0008e0c0
    void AddCollisionInfo(const Coord3 *centre, const Coord3 *extents);                         // 0x0008e1f0
    // This tick's average, else the instance's position and the velocity
    void GetCollisionInfo(Coord4 *centre, Coord4 *extents);                                     // 0x0008e2d0

    // ---- effects
    void InitEffects(bool initial);                                                             // 0x0008f690
    void ToggleEffect(bool on, uint32_t index, ArticleEffect *effect, float intensity);         // 0x0008e430
    void DecayEffects();                                                                        // 0x0008e580
    void TriggerEffects(bool on, bool byId, uint32_t which, float intensity);                   // 0x0008e6a0
    void SuppressEffects(bool byId, uint32_t which);                                            // 0x0008e7d0
    void DamageEffects(uint32_t zones);                                                         // 0x0008e900
    // vtable slot 15; the third to fifth arguments are not read
    void TriggerFX(int type, uint32_t which, uint32_t unused3, uint32_t unused4, uint32_t unused5,
                   float intensity);                                                            // 0x0008ea70
    void StopFX();                                                                              // 0x0008eb60
    ArticleEffect* LookupFXHandle(const char *name, int instance);                              // 0x0008ec20
    void LocateFX(const ArticleEffect *effect, MATRIX4 *transform, bool world);                 // 0x0008eca0
    // brightness from a level clamped to 0..1 (the linker placed it among the characters' code)
    void SetBrightness(float level);                                                            // 0x000143e0
    // Draws one effect; false if it is not drawn this way (it is then switched off)
    bool RenderEffect(ArticleEffect *effect, MATRIX4 *transform);                               // 0x0008ea20
    void RenderEffects(bool glaresOnly);                                                        // 0x0008f740
    // vtable slot 11
    void SetEventDynamicData();                                                                 // 0x0008dae0

    // Set and clear the "visible" bit (0x0008db40, 0x0008db30).
    void Show();
    void Hide();

    // ---- calls through the vtable
    RSceneObj* DeleteVirtual(unsigned flags) {                                                  // slot 0
        typedef RSceneObj *(RSceneObj::*Method)(unsigned flags);
        return (this->*XbeVirtual<Method>(this, 0))(flags);
    }
    void RenderVirtual() { CallSlot(2); }
    void RenderShadowVirtual() { CallSlot(4); }
    void RenderDeferredEffectsVirtual() { CallSlot(5); }
    void TransformPointToWorldSpaceVirtual(Coord4 *point) {                                     // slot 7
        typedef void (RSceneObj::*Method)(Coord4 *point);
        (this->*XbeVirtual<Method>(this, 7))(point);
    }
    void TransformMatrixToWorldSpaceVirtual(MATRIX4 *transform) {                               // slot 8
        typedef void (RSceneObj::*Method)(MATRIX4 *transform);
        (this->*XbeVirtual<Method>(this, 8))(transform);
    }
    double GetRenderOffsetVirtual() {   // slot 9, read unrounded
        typedef double (RSceneObj::*Method)();
        return (this->*XbeVirtual<Method>(this, 9))();
    }
    void SetProcAnimStateVirtual() { CallSlot(10); }
    Coord3* GetVelocityVirtual() {                                                              // slot 13
        typedef Coord3 *(RSceneObj::*Method)();
        return (this->*XbeVirtual<Method>(this, 13))();
    }
    void UpdatePositionVirtual(bool update) {                                                   // slot 14
        typedef void (RSceneObj::*Method)(bool update);
        (this->*XbeVirtual<Method>(this, 14))(update);
    }
    void PostLoadVirtual() { CallSlot(17); }
    void* ResolveObjectDataVirtual(const char *name, bool *found) {                             // slot 18
        typedef void *(RSceneObj::*Method)(const char *name, bool *found);
        return (this->*XbeVirtual<Method>(this, 18))(name, found);
    }

private:
    void CallSlot(int slot) {
        typedef void (RSceneObj::*Method)();
        (this->*XbeVirtual<Method>(this, slot))();
    }
};
static_assert(sizeof(RSceneObj) == 0x40, "a scene object is 64 bytes");
static_assert(offsetof(RSceneObj, sourceInstance) == 0x0c && offsetof(RSceneObj, mapNode) == 0x18 &&
              offsetof(RSceneObj, flags) == 0x1f && offsetof(RSceneObj, effectDecayTime) == 0x24 &&
              offsetof(RSceneObj, animHandle) == 0x2c && offsetof(RSceneObj, collisionInfo) == 0x38 &&
              offsetof(RSceneObj, name) == 0x3c, "RSceneObj layout");

// A scene object with a source instance of its own (0x80 bytes; allocated under this name by Newton's constructor,
// ESpawnSmackable's destructor and three others): every allocation site copies the identity matrix into
// `instance`, runs RSceneObj's constructor on it, and replaces the vtable with its own (0x0018a398), which
// overrides only the destructor.
class RAutonomousObj : public RSceneObj {
public:
    CARP::Instance instance;            // +0x40

    void Destruct();                    // RSceneObj's (a jump to it)                           // 0x0001aa70
    RAutonomousObj* Delete(unsigned flags);     // the scalar deleting destructor, vtable slot 0 // 0x0001b180
};
static_assert(sizeof(RAutonomousObj) == 0x80, "an autonomous scene object is 128 bytes");

// ---- helpers the linker placed among the scene objects' code (the names are ours)

// The renderer's random sequence's state (RRandom::StartUp seeds it)
#define RandomSeed U32_AT(0x001c45c4)
#define RandomMultiplier U32_AT(0x001c45c8)
// FUN_0001aab0: the next 16 bits of the sequence; the game's code inlines it in many places
uint32_t RandomShort();                                                                         // 0x0001aab0
// FUN_0001aae0: RandomShort scaled into [0, scale), answered unrounded
double RandomScaled(float scale);                                                               // 0x0001aae0

// URefCounter<RCARPFile>'s tree (CarpFileRefCounter's map, at 0x001f25f4): its compiled copies
class CarpFileRefTree : public RefCounterTree {
public:
    void EraseSubtree(RefCounterNode *node);                                                    // 0x0008fb00
    RefCounterNode** EraseAt(RefCounterNode **result, RefCounterNode *where);                   // 0x0008fb50
    RefCounterNode** InsertAt(RefCounterNode **result, bool addLeft, RefCounterNode *where,
                              const RefCounterValue *value);                                    // 0x0008fec0
    RefCounterNode** EraseRange(RefCounterNode **result, RefCounterNode *first,
                                RefCounterNode *last);                                          // 0x000900b0
    RefCounterInsertResult* InsertUnique(RefCounterInsertResult *result,
                                         const RefCounterValue *value);                         // 0x000901a0
    // The destructor's erase and free, without its subtree erase (only an exception unwind calls it)
    void DestroyRange();                                                                        // 0x00090360
    // The static's destructor (its atexit thunk calls it)
    void Destruct();                                                                            // 0x000903a0
};
