#ifndef DRIVING_RENDER_SHADOWMAP_H_
#define DRIVING_RENDER_SHADOWMAP_H_

// ---------------------------------------------------------------------------------------------------------------
// RShadowMap (one instance, 0x58 bytes): the cars' shadows. Projected: the car's shadow geometry drawn into a
// 512 x 512 texture from straight along the light, through a view (RShadowMap is an RViewCamera) whose matrix fits
// the car's box, and a matrix kept for the world's render methods to project the texture by ("GAME::ShadowMatrix",
// "GAME::ShadowTexture"). Simple: a dark quad under the car, its size per car from the "Shadow width" and "Shadow
// length" tuning, fading as the wheels leave the ground. See ShadowMap.cpp.
// ---------------------------------------------------------------------------------------------------------------

#include <stddef.h>
#include <stdint.h>

#include "../autogenerated_layouts.h"     // MATRIX4
#include "../camera/Camera.h"             // RViewCamera
#include "../data/CoordConvert.h"         // Coord4
#include "../engine/USingleton.h"

namespace EAGL {
struct TAR;
struct TextureRenderContext;
struct ViewPort;
}
class RSceneObj;

// RShadowMap's private data (Ghidra: RShadowMap::ShadowPrivateData, 0x60 bytes)
struct ShadowPrivateData {
    MATRIX4 matrix;                     // +0x00 the world to the shadow texture's coordinates
    EAGL::TextureRenderContext *context;    // +0x40
    EAGL::TAR *colourTarget;            // +0x44 512 x 512, 16 bits
    EAGL::TAR *depthTarget;             // +0x48
    EAGL::TAR *texture;                 // +0x4c 'cshd', the simple shadow's
    uint8_t unknown50[0x10];

    ShadowPrivateData* Construct();                                                             // 0x000a5a50
};
static_assert(sizeof(ShadowPrivateData) == 0x60, "the shadow map's data is 0x60 bytes");
static_assert(offsetof(ShadowPrivateData, context) == 0x40 && offsetof(ShadowPrivateData, texture) == 0x4c,
              "ShadowPrivateData layout");

class RShadowMap;

// RShadowMap's second base, USingleton, at +0x4c: its vtable (0x00192fc8) reaches the deleting destructor through
// a thunk that steps back to the whole object
struct ShadowMapSingleton {
    USingleton base;

    RShadowMap* Delete(unsigned flags);                                                         // 0x000a5c00
};

// A car's simple shadow, "Shadow width" and "Shadow length" (the name is ours)
struct CarShadowSize {
    float width;
    float length;
};

class RShadowMap : public RViewCamera {
public:
    ShadowMapSingleton singleton;       // +0x4c
    ShadowPrivateData *data;            // +0x50
    EAGL::ViewPort *savedViewPort;      // +0x54 the view's own viewport, put back by the destructor

    RShadowMap* Construct();                                                                    // 0x000a5ac0
    void Destruct();                                                                            // 0x000a5c10
    RShadowMap* Delete(unsigned flags);     // the scalar deleting destructor, vtable slot 0     // 0x000a6670
    static void Kill();                     // the USingleton vtable's slot 2                    // 0x000a5be0
    static void LoadAttributes();                                                               // 0x000a5820
    static bool ProjectedShadowsEnabled();                                                      // 0x000a5950
    // The shadow texture's targets made the render targets again (FUN_000a5930, the name is ours)
    void SetupFrameBuffers();                                                                   // 0x000a5930
    void ClearShadowMap();                                                                      // 0x000a5960
    // The view along `direction` fitted to the car's box, and the texture matrix with it
    void SetCamera(RSceneObj *vehicle, const Coord4 *direction);                                // 0x000a5c90
    void Begin(RSceneObj *vehicle, const Coord4 *direction);                                    // 0x000a6050
    void Draw(RSceneObj *vehicle, const Coord4 *direction);                                     // 0x000a60b0
    void DrawSimpleShadow(RSceneObj *vehicle);                                                  // 0x000a60f0
    // The world's render methods' "GAME::" variables (the loader's lookup callback; Ghidra has no function there,
    // the name is ours)
    static void* LookupVariable(const char *name, bool *found);                                 // 0x000a59c0
};
static_assert(sizeof(RShadowMap) == 0x58, "RShadowMap is 0x58 bytes");

#define TheShadowMap (*(RShadowMap **)0x0020176c)          // RShadowMap::Init's instance

#endif // DRIVING_RENDER_SHADOWMAP_H_
