#ifndef DRIVING_RENDER_SKYWATER_H_
#define DRIVING_RENDER_SKYWATER_H_

// ---------------------------------------------------------------------------------------------------------------
// The sky, the water's tuning and the broken windows (0x000a6690-0x000a6810, 0x000a8460-0x000a8f10), with the
// compiled library code the linker put among them. See SkyWater.cpp.
//
//   RSky: the track's sky instances drawn round the eye, and the sun's lens flare placed from the light's angle.
//   RWater (0x120 bytes): four layers of scale and scroll for the water's render methods ("Water layer"), and the
//     sun's direction over the water as a rotation.
//   RWindow: the cracked panes the collision manager keeps for the instances near the eye, drawn as textured
//     quads in batches.
// ---------------------------------------------------------------------------------------------------------------

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "../autogenerated_layouts.h"     // MATRIX4
#include "../data/CoordConvert.h"         // Coord4
#include "../engine/USingleton.h"
#include "../world/CollisionManager.h"    // WindowPaneNode, WindowPaneIterator
#include "../world/CollisionTypes.h"      // InstanceList

namespace CARP {
class Instance;
}

// The warning beside a provisional port: code no shipped data reaches (the STL's "too long" throw), ported from
// the listing without a test. Once.
inline void SkyWaterUntested(const char *what) {
    printf("[skywater] WARNING: %s ran - a provisional port that no shipped data reaches, UNTESTED. Check what it "
           "computes against the original.\n", what);
    fflush(stdout);
}

#define SKYWATER_UNTESTED(what) \
    do { \
        static bool warned_; \
        if (!warned_) { \
            warned_ = true; \
            SkyWaterUntested(what); \
        } \
    } while (0)

class RSky {
public:
    // The sky instances at the start of the array (kInstanceSky), each moved to the eye and drawn without fog or
    // positional lights; then the sun's flare. With skipSun (the world's draws pass false) depth writes are left on
    // and the flare is not placed.
    static void Draw(CARP::Instance *instances, bool skipSun);                                  // 0x000a6690
};

constexpr int kWaterLayers = 4;

class RWater {
public:
    USingleton singleton;               // +0x00 the base, its vtable pointer: RWater's (0x001930b8)
    uint8_t unknown04[0xc];
    MATRIX4 sunRotation;                // +0x10 about y by sunDirection degrees
    Coord4 scales[kWaterLayers];        // +0x50 "Water scale X", "Water scale Y"
    uint8_t unknown90[0x20];
    Coord4 scrolls[kWaterLayers];       // +0xb0 "Water scroll U", "Water scroll V"
    uint8_t unknownF0[0x20];
    float sunDirection;                 // +0x110 "Water sun dir", degrees
    uint8_t unknown114[0xc];

    RWater* Construct();                                                                        // 0x000a8460
    static void Kill();                     // vtable slot 2                                     // 0x000a8470
    void LoadAttributes();                                                                      // 0x000a8490
};
static_assert(sizeof(RWater) == 0x120, "RWater is 0x120 bytes");
static_assert(offsetof(RWater, scales) == 0x50 && offsetof(RWater, scrolls) == 0xb0 &&
              offsetof(RWater, sunDirection) == 0x110, "RWater layout");

#define TheWater (*(RWater **)0x00201844)                   // RWater::Init's instance

class RWindow {
public:
    static void Init();                                                                         // 0x000a8780
    // The cracked panes of the instances within `radius` of the eye
    static void DrawBrokenWindows(float radius);                                                // 0x000a8c10
};

// One cracked pane's two triangles (a, b, c) and (b, c, d) into the window batch, drawn first when full; with
// `flush`, only the batch drawn. The core of FUN_000a87e0, which takes `a` in EAX (the name is ours).
void QueueBrokenWindowQuad(const Coord4 *a, const Coord4 *b, const Coord4 *c, const Coord4 *d, uint32_t colour,
                           const Coord4 *uvs, bool flush);
void FUN_000a87e0();                    // naked: EAX a, the rest on the stack

// The data of RDebris's draws scaled once, by RDebris's constructor (FUN_000a8e80, the name is ours)
void ScaleDebrisTables();                                                                       // 0x000a8e80

// Among RWindow's code the linker placed compiled library code too: WindowPaneMap::Min,
// WindowPaneIterator::Increment (world/CollisionManager.h) and InstanceList's Deallocate, Tidy and Xlen
// (world/CollisionTypes.h), ported in SkyWater.cpp.

#endif // DRIVING_RENDER_SKYWATER_H_
