#pragma once

#include "../autogenerated_layouts.h"

// The game's vector and matrix routines, each calling the original. Most are four-wide - SSE, ported from the
// PS2's VU0 code - and read and write four floats, keeping the destination's fourth; so every vector handed to
// them is a 16-byte-aligned Vec4, as the originals' callers' locals are. All are __cdecl.

struct alignas(16) Vec4 {
    float x, y, z, w;
};

// A rotation of `degrees` about the axis (x, y, z) (0x00114c60).
// AUTOGEN
void BuildRotate(MATRIX4 *out, float degrees, float axisX, float axisY, float axisZ);

// out = in (x, y, z) through m, translation included (0x00116240).
// AUTOGEN
void VU0_MATRIX4_vect3mult(const void *in, const MATRIX4 *m, Vec4 *out);

// out = in scaled to unit length in x, y, z, by the SSE reciprocal square root estimate (0x00115e20).
// AUTOGEN
void VU0_v4unitxyz(const Vec4 *in, Vec4 *out);

// out = in * scale (0x00115f00).
// AUTOGEN
void VU0_v4scale(const Vec4 *in, float scale, Vec4 *out);

// out = a - b (0x00115ad0).
// AUTOGEN
void VU0_v4sub(const Vec4 *a, const void *b, Vec4 *out);

// out = a * scale + b (0x00115f80).
// AUTOGEN
void VU0_v4scaleadd(const Vec4 *a, float scale, const Vec4 *b, Vec4 *out);

// The distance between two points, x87 (0x00116020).
// AUTOGEN
float vec3distance(const void *a, const void *b);
