#pragma once

#include "../autogenerated_layouts.h"

// EA's pad library (librealinputz on the PS2; the Xbox's version is built on XAPI): the bottom of the game's
// input layer, just above the XAPI entry points that src/driving/platform/XboxInput.cpp answers from Win32 XInput.
//
// It keeps one record per controller port - PadData, four of them at 0x00241c50 - which PAD_update refreshes:
// pads plugged in or pulled out since the last poll are opened or closed, and every open pad's state is read into
// its record. XBoxPadDevice::PollDevice (src/driving/engine/InputDevice.cpp) reads the records.

// PadData (a name invented here; 0x90 bytes) is asked of the layout generator:
// XBE_NEEDS(PadData)

// The record for a port (0x00108480).
PadData *PAD_getdataptr(int port);

// Polls every port (0x00108490). A sync task, added by PAD_init; IOModule::Update calls it too.
void PAD_update();

// Once: clears the records, opens every pad that is plugged in, and adds PAD_update as a sync task (0x001086c0).
void PAD_init();
