#ifndef DRIVING_GAME_BONDCAR_H_
#define DRIVING_GAME_BONDCAR_H_

// ---------------------------------------------------------------------------------------------------------------
// PBondCar (0x420 bytes, Simulation::SpawnCarObject's "PBondCar"): every car, the player's and the AI's, and the
// other ground vehicles the game drives with the same code (snowmobiles, the submarine, spline-driven vehicles). A
// PVehicle with four wheels on the world's surface, its controls, damage zones, tyre tracks, weapons state and the
// render, audio and feedback objects it owns. Its vtable is 0x0018f580 (84 slots: PVehicle's 83 and one more).
//
// The methods are split by package: BondCarSimulate.cpp (construction, Simulate, ApplyDamage, InitAudioObject) and
// the other BondCar*.cpp files.
// ---------------------------------------------------------------------------------------------------------------

#include <stddef.h>
#include <stdint.h>

#include "Vehicle.h"
#include "../../common/xbeClass.h"      // offsetof on a derived class without clang's warning
#include "../autogenerated_layouts.h"   // MATRIX4
#include "../data/CoordConvert.h"       // Coord3, Coord4
#include "../world/WorldPos.h"

class ABaseSound;
class ActionQueue;
class AIGroundVehicle;
class RTyreTrack;
struct RigidBodyInfo;
struct WTargetable;

constexpr int kCarWheels = 4;

// The car classes (carClass): 0 the player's; the constructor makes class 4 class 2 with unknown375 set
enum CarClass : int32_t {
    kPlayerCar = 0,
    kCarClass1 = 1,
    kCarClass2 = 2,
    kCarClass3 = 3,
    kCarClass4 = 4,
};
constexpr uint32_t kPBondCarVtable = 0x0018f580;
constexpr uint32_t kTyreTrackSize = 0x920;         // sizeof(RTyreTrack), the tracks' FastAlloc size

// What the wheel-force methods work from at each wheel (AddWheelForces, AddSimpleWheelForces, AddSnowmobileForces;
// the names are ours)
struct BondCarWheelInput {
    float grip;                 // +0x00 scales the tyre's sideways slip into a force
    float drive;                // +0x04 the push along the wheel's heading (negative: braking)
    float frictionLimit;        // +0x08 the most sideways force the tyre holds
    float handbrake;            // +0x0c a drag against the wheel's travel
};
static_assert(sizeof(BondCarWheelInput) == 0x10, "a wheel's input is 16 bytes");

// Simulate's scratch pad: a block of its stack frame (0x450 bytes, 16-byte aligned, not initialised) whose address
// it leaves in BondCarScratchPad for the Process*Physics methods it calls, their wheel-force methods and
// ImproveLanding. Simulate itself writes none of it. The names are ours.
struct BondCarScratch {
    uint8_t unknown000[0x100];
    MATRIX4 steeredOrientation;         // +0x100 the body's orientation turned by the steering
    Coord4 wheelHeading[2];             // +0x140 the front wheels' heading, the rear's
    Coord4 rollingResistance4;          // +0x160 rollingResistance as a Coord4
    BondCarWheelInput wheelInput[kCarWheels];   // +0x170
    float wheelSlip[kCarWheels];        // +0x1b0 the wheel forces' sideways force against its limit, 0 to 1
    Coord3 velocity;                    // +0x1c0 the body's, y cleared
    float forwardSpeed;                 // +0x1cc along the body's heading
    Coord3 rollingResistance;           // +0x1d0 velocity scaled by ROLLING_RESISTANCE (ProcessPhysics)
    float driveForce;                   // +0x1dc
    Coord3 forward;                     // +0x1e0 the body's heading (its orientation's row 2)
    float handbrake;                    // +0x1ec
    Coord3 steeredForward;              // +0x1f0 the front wheels' heading
    float frontGrip;                    // +0x1fc the front axle's share of the grip
    Coord3 position;                    // +0x200 the body's
    float rearGrip;                     // +0x20c the rear axle's
    MATRIX4 steeringTurn;               // +0x210 the steering's turn about y
    // The wheel-force methods' working vectors
    Coord4 lever;                       // +0x250 the wheel from the body's centre
    Coord4 lateral;                     // +0x260 across the wheel, then the sideways force
    Coord4 force;                       // +0x270 the wheel's force
    Coord4 axle;                        // +0x280 along the axle, then the suspension's force
    Coord4 pointVelocity;               // +0x290 the body's velocity at the wheel
    Coord4 rolling;                     // +0x2a0 along the wheel's heading on the ground, then the drive's force
    Coord4 torque;                      // +0x2b0
    Coord4 drag;                        // +0x2c0 the hand brake's drag
    uint8_t unknown2D0[0xc];
    RigidBodyInfo *forceInfo;           // +0x2dc the body's (the wheel-force methods'; ImproveLanding reads it)
    uint8_t unknown2E0[0xc];
    float compression;                  // +0x2ec the wheel's spring's
    Coord3 heading;                     // +0x2f0 the body's heading, level
    float compressionChange;            // +0x2fc
    Coord3 groundNormal;                // +0x300 the ground's normal, level
    float springForce;                  // +0x30c
    Coord3 spin;                        // +0x310 the body's spin at the wheel
    float lateralExcess;                // +0x31c the sideways force past the limit
    float lateralForce;                 // +0x320
    float liftAboveGround;              // +0x324 the most compression of a wheel off the ground
    uint8_t unknown328[8];
    int32_t wheelsOnGround;             // +0x330 the wheels whose springs pushed
    uint8_t unknown334[4];
    float slipFraction;                 // +0x338
    uint8_t unknown33C[4];
    MATRIX4 landing;                    // +0x340 ImproveLanding's level orientation
    MATRIX4 noseRotation;               // +0x380 NOSE_JUMP_ANGLE about x
    Coord4 up;                          // +0x3c0 (0, 1, 0)
    uint8_t unknown3D0[0x20];
    Coord4 landingQuat;                 // +0x3f0
    uint8_t unknown400[0x10];
    RigidBodyInfo *info;                // +0x410 the body's (the Process*Physics methods')
    float steeringInput;                // +0x414 the steering within -1..1 (ProcessSimplePhysics: pulled by
                                        //        shredded tyres)
    float shreddedDrag;                 // +0x418 ProcessSimplePhysics': with one tyre shredded 0.5, else 1
    float maxAcc;                       // +0x41c MAXACC by the gear's ratio
    float maxRevAcc;                    // +0x420 MAXREVACC, cut above the reversing speed
    float wheelSpeed;                   // +0x424 the wheels' turns per step at the body's speed, at most 1
    float boostAcc;                     // +0x428 BOOST_EXTRA_ACC while the boost lasts
    float scale42C;                     // +0x42c the steering's speed scale, then the friction's
    float unknown430;                   // +0x430
    float blend;                        // +0x434 1 / NUM_BLEND_STEPS (ImproveLanding)
    float boostGrip;                    // +0x438 the friction limits' scale while the boost lasts
    float counterSteer;                 // +0x43c the rear friction limit's scale when counter-steering
    uint8_t handbrakeOn;                // +0x440 the hand brake's force applied
    uint8_t shreddedTyres;              // +0x441 ProcessSimplePhysics'
    uint8_t wheelSpin;                  // +0x442
    uint8_t limited;                    // +0x443 the wheel's sideways force was cut to its limit
    uint8_t onGround;                   // +0x444 the wheel's
    uint8_t unknown445[0xb];
};
static_assert(sizeof(BondCarScratch) == 0x450, "Simulate's scratch pad is 0x450 bytes");
static_assert(offsetof(BondCarScratch, steeredOrientation) == 0x100 && offsetof(BondCarScratch, wheelInput) == 0x170 &&
              offsetof(BondCarScratch, velocity) == 0x1c0 && offsetof(BondCarScratch, steeringTurn) == 0x210 &&
              offsetof(BondCarScratch, lever) == 0x250 && offsetof(BondCarScratch, forceInfo) == 0x2dc &&
              offsetof(BondCarScratch, compression) == 0x2ec && offsetof(BondCarScratch, spin) == 0x310 &&
              offsetof(BondCarScratch, wheelsOnGround) == 0x330 && offsetof(BondCarScratch, slipFraction) == 0x338 &&
              offsetof(BondCarScratch, landing) == 0x340 && offsetof(BondCarScratch, landingQuat) == 0x3f0 &&
              offsetof(BondCarScratch, info) == 0x410 && offsetof(BondCarScratch, blend) == 0x434 &&
              offsetof(BondCarScratch, boostGrip) == 0x438 && offsetof(BondCarScratch, onGround) == 0x444,
              "scratch pad layout");

#define BondCarScratchPad (*(BondCarScratch **)0x001e7a88)

class PBondCar : public PVehicle {
public:
    RTyreTrack *tyreTracks[kCarWheels];         // +0x074
    uint8_t unknown084[0xc];
    WWorldPos wheels[kCarWheels];               // +0x090 the ground under each wheel
    Coord4 wheelRoadNormal[kCarWheels];         // +0x190 w: the road's height
    Coord4 wheelPos[kCarWheels];                // +0x1d0
    float suspensionCompression[kCarWheels];    // +0x210
    float wheelSlip[kCarWheels];                // +0x220
    float wheelSpinAngle[2];                    // +0x230 the front wheels', the rear wheels'
    float unknown238;                           // +0x238 CalculateRPM's
    CarPhysics *physics;                        // +0x23c PVehicle::CarPhysicsAttrib of the attributes
    BondCarControl control;                     // +0x240
    float unknown260;
    float unknown264;
    float unknown268;
    ActionQueue *actionQueue;                   // +0x26c "CarQ", the player's car only
    float yDrawModifier;                        // +0x270
    float carWheelSpeed;                        // +0x274
    float unknown278;                           // +0x278 cleared by InitializeCarControls, with the next three
    float unknown27C;
    float unknown280;
    float unknown284;
    float carSpeed;                             // +0x288
    float carSteer;                             // +0x28c
    float unknown290;
    int32_t rocketBoost;                        // +0x294 steps of boost left (EnableRocketBoost: 4 x BOOST_TIME)
    uint8_t unknown298;
    int8_t numWheelsOnGround;                   // +0x299
    int8_t reverseTimer;                        // +0x29a
    uint8_t unknown29B;
    uint8_t reversing;                          // +0x29c
    int8_t inShock;                             // +0x29d steps of shock left
    uint8_t againstWall;                        // +0x29e
    uint8_t unknown29F;
    uint32_t tyreDamagePoints[kCarWheels];      // +0x2a0 TYRE_DAMAGE_POINTS each; 0: shredded
    uint8_t unknown2B0;
    uint8_t unknown2B1;
    uint8_t twoWheelMode;                       // +0x2b2
    uint8_t unknown2B3;
    float twoWheelStuntTimer;                   // +0x2b4
    uint8_t unknown2B8[4];
    float targetGas;                            // +0x2bc
    float targetBrake;                          // +0x2c0
    float unknown2C4;
    int32_t carClass;                           // +0x2c8 a CarClass
    const char *carType;                        // +0x2cc the attribute set's name
    uint32_t carColour;                         // +0x2d0
    uint8_t unknown2D4;
    uint8_t unknown2D5;
    uint8_t subRolling;                         // +0x2d6
    uint8_t gearChangeTimer;                    // +0x2d7 15 at a gear change, then counted down (name ours)
    int8_t gear;                                // +0x2d8 CalculateRPM's
    int8_t previousGear;                        // +0x2d9 kept while gearChangeTimer runs; -1 at first (name ours)
    uint8_t unknown2DA;
    uint8_t landingFlag;                        // +0x2db
    float unknown2DC;                           // +0x2dc -1 at construction
    WTargetable *targetBeacon;                  // +0x2e0 classes 0 and 2
    AIGroundVehicle *aiGroundVehicle;           // +0x2e4
    float unknown2E8;
    float unknown2EC;
    DamageZone damageZones[kDamageZoneCount];   // +0x2f0
    float damageByPlayer;                       // +0x370
    uint8_t damageByPlayerTimer;                // +0x374
    uint8_t unknown375;
    uint8_t tyreBlowOuts;                       // +0x376 the tyres can be shot out (DisableTyreBlowOuts clears it)
    uint8_t empActive;                          // +0x377
    int32_t empTimer;                           // +0x378
    ABaseSound *audio;                          // +0x37c the engine sound InitAudioObject makes (an AVehicle)
    int32_t turnSignalStart;                    // +0x380 the step the signal's period is counted from
    int32_t turnSignalPeriod;                   // +0x384 in steps; 60 at construction
    float turnSignalLit;                        // +0x388 the lit fraction, at the period's end; 0.4 at construction
    float turnSignalSteering;                   // +0x38c the steering past which the signal goes off
    int32_t turnSignalMode;                     // +0x390
    uint8_t laserActive;                        // +0x394
    uint8_t unknown395[3];
    int32_t laserTimer;                         // +0x398 120 when FireLaser starts it
    uint8_t glareOn[16];                        // +0x39c
    int32_t resetAvailable;                     // +0x3ac
    Coord3 resetDirection;                      // +0x3b0 the constructor's direction
    BondCarControl lockedControl;               // +0x3bc
    int32_t controlLockTimer;                   // +0x3dc 0x7fffffff: LockCarControlForever; -1 none
    float bob;                                  // +0x3e0
    float bobAngle;                             // +0x3e4 random at InitializeCarVariables
    float unknown3E8;
    float hitPoints;                            // +0x3ec 700 (SetHitPointLoc's)
    uint8_t immunity;                           // +0x3f0
    uint8_t unknown3F1[3];
    float *shieldPointLoc;                      // +0x3f4
    float unknown3F8;
    uint8_t oilSlick;                           // +0x3fc
    uint8_t unknown3FD;
    uint8_t unknown3FE;
    uint8_t scoreable;                          // +0x3ff
    float unknown400;
    float unknown404;
    uint8_t unknown408;
    int8_t forceRollDirection;                  // +0x409 0: free; else its sign
    uint8_t forceStop;                          // +0x40a flags (ForceStopOn/Off)
    int8_t rollSub;                             // +0x40b the roll RollSub set, in degrees
    const char *secondaryType;                  // +0x40c SECONDARY_TYPE
    uint8_t unknown410;
    uint8_t wasInAir;                           // +0x411
    uint8_t unknown412[0xe];

    // ---- construction (BondCarSimulate.cpp)
    PBondCar* Construct(int carClass, const char *carType, uint32_t colour, const Coord3 *direction,
                        const Coord3 *position);                                                // 0x0006d350
    void Destruct();                                                                            // 0x00065c70
    PBondCar* Delete(unsigned flags);           // the scalar deleting destructor, vtable slot 0 // 0x0006a810
    static void InitializeBondCarGlobals();                                                     // 0x00061ae0
    void InitTyreTracks();                                                                      // 0x00062120
    void InitializeCarVariables(bool initializeControls);                                      // 0x00062440
    void InitAudioObject(int carClass);                                                         // 0x0006cc20

    // ---- virtual (the slot in the vtable)
    void SetInShock(float shock);                                           // 1                 // 0x00062740
    // Damage along the segment from-to (world points); the answer is a set of flags (0x10, 0x70, 0x80, 0x90)
    int ApplyDamage(const Coord3 *from, const Coord3 *to, float amount, float split, int kind,
                    const uint32_t *sourceSig);                             // 2                 // 0x0006b6f0
    DamageZone* GetDamageZones(uint32_t *count);                            // 3                 // 0x00062a40
    void Simulate();                                                        // 4                 // 0x0006a840
    void DebugObject();                                                     // 5                 // 0x00065ba0
    ABaseSound* GetAudio();                                                 // 7                 // 0x00065d50
    void SetAudio(ABaseSound *audio);                                       // 8                 // 0x00065d60
    void SetAIGroundVehicle(AIGroundVehicle *vehicle);                      // 9                 // 0x00065d70
    AIGroundVehicle* GetAIGroundVehiclePtr();                               // 10                // 0x00065d80
    void* GetSplinePath();                                                  // 11                // 0x00062c40
    int GetResetAvailable();                                                // 12                // 0x00065d90
    void EnableTargetBeacon(bool enable);                                   // 13                // 0x00062c60
    void DisableTargetBeacon();                                             // 14                // 0x00062cf0
    const char* GetCarType();                                               // 15                // 0x00065da0
    void ChangeCarType(const char *carType, bool purgeModel);               // 16                // 0x0006a460
    void SetCarClass(int carClass);                                         // 17                // 0x00065db0
    int GetCarClass();                                                      // 18                // 0x00065dc0
    uint32_t GetCarColour();                                                // 19                // 0x00065dd0
    float GetCarSpeed();                                                    // 20                // 0x00065ef0
    void InitializeCarControls();                                           // 21                // 0x000623b0
    void FlushCarControls();                                                // 22                // 0x00062430
    void GetControllerInput();                                              // 23                // 0x00066640
    float GetCarSteer();                                                    // 24                // 0x00065f90
    void SetCarControlSteering(float steering);                             // 25                // 0x00065de0
    void SetCarControlSteeringVertical(float steering);                     // 26                // 0x00065df0
    void SetCarControlStrafeHorizontal(float strafe);                       // 27                // 0x00065e00
    void SetCarControlStrafeVertical(float strafe);                         // 28                // 0x00065e10
    void SetCarControlGas(float gas);                                       // 29                // 0x00065e20
    void SetCarControlBrake(float brake);                                   // 30                // 0x00065e30
    void SetCarControlHandBrake(bool handBrake);                            // 31                // 0x00065e40
    uint8_t GetCarControlHandBrake();       // the byte, raw                // 32                // 0x00065e50
    void SetCarControlFirePrimary(bool fire);                               // 33                // 0x00065e60
    void LockCarControlForever();                                           // 34                // 0x00065e70
    void SetTargetGas(float gas);                                           // 35                // 0x00065ea0
    void SetTargetBrake(float brake);                                       // 36                // 0x00065eb0
    // The controls are returned by value: the caller's record, filled and answered
    BondCarControl* GetCarControl(BondCarControl *result);                  // 37                // 0x00065ec0
    int GetNumTires();                                                      // 38                // 0x000626e0
    uint8_t EmpActive();                    // the byte, raw                // 39                // 0x00065ee0
    bool IsTyreShredded(int8_t wheel);                                      // 40                // 0x00065f00
    RTyreTrack* GetTyreTrackPtr(int wheel);                                 // 41                // 0x00065f20
    void ResetCar(Coord3 *position, const Coord3 *direction);   // its y set // 42                // 0x000627c0
    void ResetCar(bool unused);                                             // 43                // 0x00066390
    void SetScoreable(bool scoreable);                                      // 44                // 0x00065f30
    void GlareOn(int glare);                                                // 45                // 0x00062d00
    int InShock();                          // 0 or 1 in all of EAX         // 46                // 0x00065f40
    void SetOilSlick(bool oilSlick);                                        // 47                // 0x00065f50
    int GetNumWheelsOnGround();                                             // 48                // 0x00065f60
    float GetCarWheelSpinAngle(int8_t axle);    // 0 front, 1 rear          // 49                // 0x00065f80
    void ResetDamage();                                                     // 50                // 0x00062600
    void SetVisualDamage(float fromA, float toA, float fromB, float toB);   // 51                // 0x00066180
    void AddDamageByPlayer(float damage);                                   // 52                // 0x00062660
    uint8_t GetDamageByPlayerTimer();                                       // 53                // 0x00065f70
    void ClearEMPState();                                                   // 54                // 0x00062ec0
    void EnableTwoWheelStunt();                                             // 55                // 0x00062f50
    void DisableTwoWheelStunt();                                            // 56                // 0x00062f60
    CarPhysics* GetPhysics();                                               // 57                // 0x00061a50
    int IsReversing();                      // 0 or 1 in all of EAX         // 58                // 0x00065fb0
    void SetAgainstWallFlag(bool against);                                  // 59                // 0x00065fc0
    float GetSuspensionCompression(int wheel);                              // 60                // 0x00065fa0
    float GetWheelRoadHeight(int wheel);                                    // 61                // 0x00065fd0
    int GetWheelRoadSurface(int wheel);     // the face's type, zero-extended // 62              // 0x00065ff0
    Coord4* GetWheelRoadNormal(int wheel);                                  // 63                // 0x00066010
    void SetShieldPointLoc(float *shieldPoints);                            // 64                // 0x00066020
    int IsWheelOnGround(int8_t wheel);      // 0 or 1 in all of EAX         // 65                // 0x00066030
    float GetCarWheelSlip(int wheel);                                       // 66                // 0x00066070
    void DisableTyreBlowOuts();                                             // 67                // 0x00066080
    bool GetIsInTwoWheelMode();                                             // 68                // 0x00066090
    bool EnableRocketBoost();                                               // 69                // 0x00062ee0
    uint8_t GetWasInAir();                                                  // 70                // 0x000660a0
    void SetWasInAir(bool wasInAir);                                        // 71                // 0x000660b0
    void FireLaser();                                                       // 72                // 0x00062b70
    void AttackWithEmp();                                                   // 73                // 0x00062b90
    Coord4* GetWheelPos(int wheel);                                         // 74                // 0x000660d0
    uint8_t GetForceStop();             // the flags                        // 75                // 0x000660e0
    void SetImmunity(bool immunity);                                        // 76                // 0x000660c0
    void ForceStopOn(uint8_t flags);                                        // 77                // 0x000660f0
    void ForceStopOff(uint8_t flags);                                       // 78                // 0x00066110
    void ForceRollDirection(int8_t direction);                              // 79                // 0x00066130
    void RollSub(int8_t degrees, bool subRolling);                          // 80                // 0x00066140
    const char* GetSecondaryType();                                         // 81                // 0x00066160
    WTargetable* GetTargetBeacon();                                         // 82                // 0x00066170
    float* GetSuspensionCompression();          // all four                 // 83                // 0x00066060

    // ---- the rest
    void GlareOff(int glare);                                                                   // 0x00062d70
    void HandleTurnSignals();                                                                   // 0x00062de0
    double CalculateRPM();                                                                      // 0x00062a60
    void ImproveLanding();                                                                      // 0x00062fe0
    int AddSnowmobileForces(const BondCarWheelInput *inputs, const Coord4 *axes, const Coord4 *roadNormals,
                            const Coord4 *wheelPos, float *loads);                              // 0x000632a0
    void ProcessSnowmobilePhysics();                                                            // 0x00063ad0
    void ProcessSubmarinePhysics();                                                             // 0x000644c0
    void ProcessSplinePhysics();                                                                // 0x00065740
    void TwoWheelStunt();                                                                       // 0x00066c90
    void ControlTyreTracks();                                                                   // 0x00066ee0
    int8_t AddWheelForces(BondCarWheelInput *input, float *slips, const Coord4 *headings,
                          const Coord4 *roadNormals, const Coord4 *wheelPos, const Coord4 *rollingResistance,
                          bool wheelSpin);                                                      // 0x000670e0
    void ProcessPhysics();                                                                      // 0x00067bd0
    int8_t AddSimpleWheelForces(BondCarWheelInput *input, const Coord4 *headings, const Coord4 *roadNormals,
                                const Coord4 *wheelPos, float *slips);                          // 0x000690a0
    void ProcessSimplePhysics();                                                                // 0x00069710
};
static_assert(sizeof(PBondCar) == 0x420, "a PBondCar is 0x420 bytes");
static_assert(offsetof(PBondCar, tyreTracks) == 0x74 && offsetof(PBondCar, wheels) == 0x90 &&
              offsetof(PBondCar, wheelRoadNormal) == 0x190 && offsetof(PBondCar, wheelPos) == 0x1d0 &&
              offsetof(PBondCar, suspensionCompression) == 0x210 && offsetof(PBondCar, physics) == 0x23c &&
              offsetof(PBondCar, control) == 0x240 && offsetof(PBondCar, actionQueue) == 0x26c &&
              offsetof(PBondCar, carSpeed) == 0x288 && offsetof(PBondCar, numWheelsOnGround) == 0x299 &&
              offsetof(PBondCar, tyreDamagePoints) == 0x2a0 && offsetof(PBondCar, carClass) == 0x2c8 &&
              offsetof(PBondCar, targetBeacon) == 0x2e0 && offsetof(PBondCar, damageZones) == 0x2f0 &&
              offsetof(PBondCar, damageByPlayer) == 0x370 && offsetof(PBondCar, audio) == 0x37c &&
              offsetof(PBondCar, glareOn) == 0x39c && offsetof(PBondCar, resetDirection) == 0x3b0 &&
              offsetof(PBondCar, lockedControl) == 0x3bc && offsetof(PBondCar, hitPoints) == 0x3ec &&
              offsetof(PBondCar, shieldPointLoc) == 0x3f4 && offsetof(PBondCar, secondaryType) == 0x40c &&
              offsetof(PBondCar, wasInAir) == 0x411, "PBondCar layout");

#endif // DRIVING_GAME_BONDCAR_H_
