"""Generates the drone system's static tables from the XBE (docs/drone/README.md, step 0).

    python tools/drone_tables.py            write src/action/game/drone/DroneTables.h and DroneTables.inc
    python tools/drone_tables.py --check    fail if either is out of date

Needs disc/default.xbe. The tables stay the game's, reached through the typed #defines in DroneTables.h, until every
function that reads one is ours (then it becomes a definition from DroneTables.inc). Until then DroneTables.inc is
compiled only into devtools/DroneTablesCheck.cpp, which compares it with the game's copies at start
(MenuCheckLists=on). A function pointer is written as the original's address, or as our function when that is
tagged AUTOINJECT in src/action - either way the same code runs, since the original's entry jumps to ours.

Tables: NDrone2_StateFuncs (250 state handlers), DroneModeSettings (36), DroneTypeSettings (85), the behaviour
property layout (91) and its masks (35), and default_bot_stats (29). The animation tables (DroneAnimStates,
Drone_AnimInfo, Drone_AnimTables, the cover lists) are left for when the animation layer is reimplemented.
"""
import json
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import global_coverage as gc  # noqa: E402

OUT_H = os.path.join(REPO, 'src', 'action', 'game', 'drone', 'DroneTables.h')
OUT_INC = os.path.join(REPO, 'src', 'action', 'game', 'drone', 'DroneTables.inc')

STATE_FUNCS = (0x00177ca0, 250)
MODE_SETTINGS = (0x001776f8, 36)
TYPE_SETTINGS = (0x001778a0, 85)
PROP_LAYOUT = (0x001634e0, 91)      # 2 bytes each: word | shift << 3, then a mask index
PROP_MASKS = (0x00163598, 35)       # u32
BOT_STATS = (0x00163628, 29)        # 14 bytes each
EMPTY_STUB = 0x000e0ec0             # a bare RET the linker shares between every empty function

HEADER = '''// THIS FILE IS GENERATED by tools/drone_tables.py from disc/default.xbe. DO NOT MODIFY.
// Regenerate (and commit) after reimplementing a state handler or an init/control function it lists.
'''


def load():
    nonzero, read, entry = gc.read_xbe()
    funcs = {int(f['address'], 16): f['name'] for f in json.load(open(os.path.join(HERE, 'functions_action.json')))}
    ours = set()
    for root, _, files in os.walk(os.path.join(REPO, 'src', 'action')):
        if 'devtools' in root:
            continue
        for fn in files:
            if not fn.endswith(('.c', '.cpp')):
                continue
            lines = open(os.path.join(root, fn), encoding='utf-8', errors='replace').read().split('\n')
            for i, line in enumerate(lines[:-1]):
                if line.strip() == '// AUTOINJECT':
                    m = re.search(r'(\w+)\s*\(', lines[i + 1])
                    if m:
                        ours.add(m.group(1))
    return read, funcs, ours


def fn_ref(addr, funcs, ours, cast, decls, proto):
    """A function pointer entry: ours by name, else the original's address with its name as a comment"""
    if addr == 0:
        return 'NULL'
    name = funcs.get(addr)
    if name and name in ours:
        decls.add(proto % name)
        return name
    if addr == EMPTY_STUB:
        return '(%s)0x%08x /* empty function */' % (cast, addr)
    return '(%s)0x%08x /* %s */' % (cast, addr, name or 'no function in Ghidra')


def prop_meanings():
    """Property id -> meaning, from docs/drone/behaviours/behaviour_properties.md"""
    out = {}
    path = os.path.join(REPO, 'docs', 'drone', 'behaviours', 'behaviour_properties.md')
    if os.path.exists(path):
        for line in open(path, encoding='utf-8'):
            m = re.match(r'\| 0x([0-9a-f]+) \| [^|]+\| ([^|]+)\|', line)
            if m:
                out[int(m.group(1), 16)] = m.group(2).strip()
    return out


def bot_names():
    out = {}
    path = os.path.join(REPO, 'docs', 'drone', 'bots-and-navigation', 'appendix-tables.md')
    if os.path.exists(path):
        for line in open(path, encoding='utf-8'):
            m = re.match(r'\| (\d+) \| (\w+) \| [0-9a-f]{28} \|', line)
            if m:
                out[int(m.group(1))] = m.group(2)
    return out


def dstate_names():
    s = open(os.path.join(REPO, 'src', 'action', 'game', 'drone', 'NDrone2.h'), encoding='utf-8').read()
    body = re.search(r'typedef enum \{\n(.*?)\n\}\s*DSTATE\s*;', s, re.S).group(1)
    names = []
    for line in body.split('\n'):
        t = line.split('//')[0].strip().rstrip(',')
        if t:
            names.append(t.split('=')[0].strip())
    return names


def generate():
    read, funcs, ours = load()
    decls = set()
    states = dstate_names()
    assert len(states) == STATE_FUNCS[1], len(states)

    # ---------------------------------------------------------------- the header
    meanings = prop_meanings()
    layout = [read(PROP_LAYOUT[0] + 2 * i, 2) for i in range(PROP_LAYOUT[1])]
    masks = struct.unpack('<%dI' % PROP_MASKS[1], read(PROP_MASKS[0], 4 * PROP_MASKS[1]))
    h = [HEADER, '#ifndef DRONETABLES_H_', '#define DRONETABLES_H_', '',
         '#include "NDrone2.h"', '#include "BOT.h"', '',
         '#pragma pack(push, 1)', '',
         '// A state handler: Enter, Exit and Update are messages like any other. Returns whether it handled the message.',
         'typedef bool (*DroneStateFunc)(DCVars_tag *dcv, Drone_tag *drone, obj_tag *gameObj, MsgObject *msg);', '',
         '// DroneModeSettings, indexed by DMODE (NDrone2_DoModeSettingsOLD)',
         'typedef struct DroneModeSetting {',
         '    uchar dtype;                // the DTYPE the mode gives',
         '    uchar side;                 // Drone_tag.side: 1 enemy, 2 ally, 3 civilian / neutral',
         '    ushort pad;',
         '    float alertness;            // Drone_tag.baseAlertness1 and .alertness',
         '    void (*init)(Drone_tag *drone);',
         '} DroneModeSetting;', '',
         '// DroneTypeSettings, indexed by DTYPE',
         'typedef struct DroneTypeSetting {',
         '    short initialState;         // Drone_tag.initialState; -1 = worked out (Idle, or InitPatrol for patrollers)',
         '    short secondState;          // Drone_tag.secondState when switching to this type; 0 = the active type\'s',
         '    void (*init)(Drone_tag *drone);',
         '    void (*control)(DCVars_tag *dcv);   // per frame, instead of NDrone2_ControlSTANDARD',
         '} DroneTypeSetting;', '',
         '// Where a behaviour property lives in the three behaviour words: behaviour_util_getProperty(id, words) =',
         '// (words[wordShift & 7] & DroneBehaviourMasks[maskIndex]) >> (wordShift >> 3)',
         'typedef struct DroneBehaviourLayout {',
         '    uchar wordShift;',
         '    uchar maskIndex;',
         '} DroneBehaviourLayout;', '',
         '#pragma pack(pop)', '',
         'static_assert(sizeof(DroneModeSetting) == 12, "DroneModeSetting is 12 bytes");',
         'static_assert(sizeof(DroneTypeSetting) == 12, "DroneTypeSetting is 12 bytes");',
         'static_assert(sizeof(DroneBehaviourLayout) == 2, "DroneBehaviourLayout is 2 bytes");', '',
         '#define NUM_DSTATES %d' % STATE_FUNCS[1],
         '#define NUM_DRONE_PROPERTIES %d' % PROP_LAYOUT[1], '',
         '// The game\'s tables. Each stays the game\'s until every function reading it is ours.']
    h += ['// XBE_GLOBAL(0x%08x, 0x%x)' % (STATE_FUNCS[0], 4 * STATE_FUNCS[1]),
          '#define NDrone2_StateFuncs (*(DroneStateFunc(*)[NUM_DSTATES])0x%08x)' % STATE_FUNCS[0],
          '// XBE_GLOBAL(0x%08x, 0x%x)' % (MODE_SETTINGS[0], 12 * MODE_SETTINGS[1]),
          '#define DroneModeSettings (*(DroneModeSetting(*)[DMODE_COUNT])0x%08x)' % MODE_SETTINGS[0],
          '// XBE_GLOBAL(0x%08x, 0x%x)' % (TYPE_SETTINGS[0], 12 * TYPE_SETTINGS[1]),
          '#define DroneTypeSettings (*(DroneTypeSetting(*)[DTYPE_COUNT])0x%08x)' % TYPE_SETTINGS[0],
          '// XBE_GLOBAL(0x%08x, 0x%x)' % (PROP_LAYOUT[0], 2 * PROP_LAYOUT[1]),
          '#define DroneBehaviourLayouts (*(const DroneBehaviourLayout(*)[NUM_DRONE_PROPERTIES])0x%08x)' % PROP_LAYOUT[0],
          '// XBE_GLOBAL(0x%08x, 0x%x)' % (PROP_MASKS[0], 4 * PROP_MASKS[1]),
          '#define DroneBehaviourMasks (*(const uint32_t(*)[%d])0x%08x)' % (PROP_MASKS[1], PROP_MASKS[0]),
          '// XBE_GLOBAL(0x%08x, 0x%x)' % (BOT_STATS[0], 14 * BOT_STATS[1]),
          '#define DefaultBotStats (*(const BOT_stats_t(*)[%d])0x%08x)' % (BOT_STATS[1], BOT_STATS[0]), '',
          '// The behaviour properties (docs/drone/behaviours/behaviour_properties.md). Numbered, not named: the meanings',
          '// are inferred and some are guesses.',
          'typedef enum {']
    for i, (b0, b1) in enumerate(layout):
        word, shift, mask = b0 & 7, b0 >> 3, masks[b1]
        width = bin(mask >> shift).count('1') if mask else 0
        where = 'word %d bit %d%s' % (word, shift, '' if width == 1 else ' (%d bits)' % width)
        h.append('    DRONE_PROP_%02X,  // %-22s %s' % (i, where, meanings.get(i, '')))
    h += ['} DRONE_PROP;', '', '#endif // DRONETABLES_H_', '']

    # ---------------------------------------------------------------- the initialisers
    inc = [HEADER,
           '// The initialisers of the tables in DroneTables.h, as the XBE has them. Include once, where the table is defined.',
           '']
    body = []
    ptrs = struct.unpack('<%dI' % STATE_FUNCS[1], read(STATE_FUNCS[0], 4 * STATE_FUNCS[1]))
    body.append('#define DRONE_STATE_FUNCS_INIT { \\')
    for i, p in enumerate(ptrs):
        ref = fn_ref(p, funcs, ours, 'DroneStateFunc', decls, 'bool %s(DCVars_tag *, Drone_tag *, obj_tag *, MsgObject *);')
        body.append('    /* %3d %-34s */ %s, \\' % (i, states[i], ref))
    body.append('}')
    body.append('')

    body.append('#define DRONE_MODE_SETTINGS_INIT { \\')
    for i in range(MODE_SETTINGS[1]):
        dtype, side, pad, alert, init = struct.unpack('<BBHfI', read(MODE_SETTINGS[0] + 12 * i, 12))
        ref = fn_ref(init, funcs, ours, 'void (*)(Drone_tag *)', decls, 'void %s(Drone_tag *);')
        a = '%.9g' % alert
        a = a if ('.' in a or 'e' in a) else a + '.0'
        body.append('    /* %2d */ { %d, %d, %d, %sf, %s }, \\' % (i, dtype, side, pad, a, ref))
    body.append('}')
    body.append('')

    body.append('#define DRONE_TYPE_SETTINGS_INIT { \\')
    for i in range(TYPE_SETTINGS[1]):
        s0, s1, init, ctrl = struct.unpack('<hhII', read(TYPE_SETTINGS[0] + 12 * i, 12))
        ri = fn_ref(init, funcs, ours, 'void (*)(Drone_tag *)', decls, 'void %s(Drone_tag *);')
        rc = fn_ref(ctrl, funcs, ours, 'void (*)(DCVars_tag *)', decls, 'void %s(DCVars_tag *);')
        body.append('    /* %2d */ { %d, %d, %s, %s }, \\' % (i, s0, s1, ri, rc))
    body.append('}')
    body.append('')

    body.append('#define DRONE_BEHAVIOUR_LAYOUTS_INIT { \\')
    for i, (b0, b1) in enumerate(layout):
        body.append('    /* 0x%02x */ { 0x%02x, %d }, \\' % (i, b0, b1))
    body.append('}')
    body.append('')
    body.append('#define DRONE_BEHAVIOUR_MASKS_INIT { \\')
    for i in range(0, len(masks), 6):
        body.append('    ' + ', '.join('0x%08x' % m for m in masks[i:i + 6]) + ', \\')
    body.append('}')
    body.append('')

    names = bot_names()
    body.append('#define DEFAULT_BOT_STATS_INIT { \\')
    for i in range(BOT_STATS[1]):
        f = struct.unpack('<BBBBHBBBBBBBB', read(BOT_STATS[0] + 14 * i, 14))
        body.append('    /* %2d %-12s */ { %s }, \\' % (i, names.get(i, ''), ', '.join(str(x) for x in f)))
    body.append('}')
    body.append('')

    if decls:
        inc += ['// The functions of ours the tables point at'] + sorted(decls) + ['']
    inc += body
    return '\n'.join(h), '\n'.join(inc)


def main():
    h, inc = generate()
    if '--check' in sys.argv:
        stale = [p for p, text in ((OUT_H, h), (OUT_INC, inc))
                 if not os.path.exists(p) or open(p, encoding='utf-8', newline='').read().replace('\r\n', '\n') != text]
        for p in stale:
            print('out of date: %s (run python tools/drone_tables.py)' % os.path.relpath(p, REPO))
        sys.exit(1 if stale else 0)
    for p, text in ((OUT_H, h), (OUT_INC, inc)):
        open(p, 'w', encoding='utf-8', newline='\n').write(text)
    print('wrote %s and %s' % (os.path.relpath(OUT_H, REPO), os.path.relpath(OUT_INC, REPO)))


if __name__ == '__main__':
    main()
