# Generates src/loader/kernel_ordinals.inc - the xboxkrnl ordinal-to-name table the loader uses to say which
# kernel import a stub belongs to. Names come from Cxbx-Reloaded's EXPORTNUM annotations, the same source
# tools/kernel_imports.py uses.
#
# Usage: python tools/gen_kernel_ordinals.py [<path to a Cxbx-Reloaded checkout>]
#
# The table is committed, so this only needs rerunning if the kernel headers change.
import os, re, sys

cxbx = sys.argv[1] if len(sys.argv) > 1 else 'Cxbx-Reloaded'
root = os.path.join(cxbx, 'src', 'core', 'kernel')
if not os.path.isdir(root):
    raise SystemExit('no kernel headers under %s' % root)

text = ''
for dirpath, dirnames, filenames in os.walk(root):
    for fn in filenames:
        if fn.endswith('.h'):
            text += open(os.path.join(dirpath, fn), encoding='utf-8', errors='replace').read() + '\n'

names = {}
for m in re.finditer(r'EXPORTNUM\((\d+)\)([^;(]*)', text):
    words = [w for w in re.findall(r'\w+', m.group(2)) if not w.isdigit()]
    if words:
        names[int(m.group(1))] = words[-1]

out = os.path.join('src', 'loader', 'kernel_ordinals.inc')
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, 'w', newline='\n') as f:
    f.write('// Generated by tools/gen_kernel_ordinals.py - do not edit.\n')
    f.write('// xboxkrnl ordinal -> name, for the loader\'s import diagnostics.\n')
    f.write('// Names from Cxbx-Reloaded\'s EXPORTNUM annotations.\n\n')
    f.write('static const char *KernelOrdinalName(unsigned ordinal) {\n')
    f.write('    switch (ordinal) {\n')
    for ordinal in sorted(names):
        f.write('        case %d: return "%s";\n' % (ordinal, names[ordinal]))
    f.write('        default: return "?";\n')
    f.write('    }\n}\n')

print('wrote %s (%d ordinals)' % (out, len(names)))
