# Generates src/loader/kernel_ordinals.inc - the xboxkrnl ordinal-to-name table the loader uses to say which
# kernel import a stub belongs to.
#
# Names come from Cxbx-Reloaded's kernel thunk table (src/core/kernel/exports/KernelThunk.cpp), which is the
# array the emulator itself indexes by ordinal, so it is the one place where the numbering is necessarily
# right. The EXPORTNUM annotations in the headers were the source before, and they are not: NtProtectVirtualMemory
# is annotated EXPORTNUM(205) there, the same number as NtPulseEvent, and 204 - its real ordinal - had no name
# at all. That mislabelled every diagnostic in the range and, worse, was copied into the loader's own table of
# implementations, where a call to NtPulseEvent would have landed in NtProtectVirtualMemory.
#
# Usage: python tools/gen_kernel_ordinals.py [<path to a Cxbx-Reloaded checkout>]
#
# The table is committed, so this only needs rerunning if the kernel headers change.
import os, re, sys

cxbx = sys.argv[1] if len(sys.argv) > 1 else 'Cxbx-Reloaded'
table = os.path.join(cxbx, 'src', 'core', 'kernel', 'exports', 'KernelThunk.cpp')
if not os.path.isfile(table):
    raise SystemExit('no kernel thunk table at %s' % table)

text = open(table, encoding='utf-8', errors='replace').read()

# Each entry is one line of the array: a name wrapped in FUNC/VARIABLE/KRNL, and its ordinal in the trailing
# comment. Taking the ordinal from the comment rather than counting lines means a reordering or a stray line
# cannot silently shift the whole table by one.
names = {}
for m in re.finditer(r'(?:FUNC|VARIABLE|KRNL)\(\s*&?(?:xbox::)?(\w+)\s*\)[^/]*//\s*0x[0-9A-Fa-f]+\s*\((\d+)\)', text):
    names[int(m.group(2))] = m.group(1)

if len(names) < 300:
    raise SystemExit('only %d ordinals parsed from %s - has its format changed?' % (len(names), table))

out = os.path.join('src', 'loader', 'kernel_ordinals.inc')
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, 'w', newline='\n') as f:
    f.write('// Generated by tools/gen_kernel_ordinals.py - do not edit.\n')
    f.write('// xboxkrnl ordinal -> name, for the loader\'s import diagnostics.\n')
    f.write('// Names from Cxbx-Reloaded\'s kernel thunk table, which is indexed by ordinal.\n\n')
    f.write('static const char *KernelOrdinalName(unsigned ordinal) {\n')
    f.write('    switch (ordinal) {\n')
    for ordinal in sorted(names):
        f.write('        case %d: return "%s";\n' % (ordinal, names[ordinal]))
    f.write('        default: return "?";\n')
    f.write('    }\n}\n')

print('wrote %s (%d ordinals)' % (out, len(names)))
