#!/usr/bin/env python3
"""List the action engine's clears of global memory, and our code's raw-address accesses inside each one.

A memset of a constant address is the best evidence there is for where a global struct or array starts and how
big it is: MSVC inlines memset(&thing, 0, sizeof(thing)) as MOV EDI, &thing / MOV ECX, sizeof/4 / REP STOSD.
Before a global can move into the DLL, every function that touches it has to be ours, and ours has to reach it
through a type of the right size - not through U32_AT(address) somewhere inside it, which nothing ties to the
region. This finds both halves:

  - every REP STOS in the XBE whose destination is a constant address in the data sections, with its byte
    count and fill value, and the function it is in (disassembled from tools/functions_action.json's entry
    points, linearly to the next one, tracking constants loaded into EDI/ECX/EAX);
  - every hex literal in src/action that falls inside one of those ranges, with its line - so a U8_AT or a
    pointer cast into the middle of a struct stands out beside the one #define of the struct itself.

A clearing function marked * is already reimplemented (it has an AUTOINJECT). docs/global-clears.md has the
results and what each region is.

    python tools/global_clears.py            # every region, with the source lines inside it
    python tools/global_clears.py --overlaps # only regions where our code has more than the one definition
"""

import json
import os
import re
import struct
import sys
from collections import defaultdict

try:
    import capstone
    from capstone import x86
except ImportError:
    sys.exit("capstone is needed: python -m pip install capstone")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
XBE = os.path.join(ROOT, "disc", "default.xbe")
SYMBOLS = os.path.join(ROOT, "tools", "functions_action.json")
INJECTIONS = os.path.join(ROOT, "src", "action", "autogenerated_injections.inc")
DATA_START, DATA_END = 0x150000, 0x400000   # the XBE's data sections
LIBRARY_START = 0xee000                     # the CRT and the Xbox libraries, not the game's own code


def load_sections(data):
    base = struct.unpack_from("<I", data, 0x104)[0]
    count = struct.unpack_from("<I", data, 0x11C)[0]
    headers = struct.unpack_from("<I", data, 0x120)[0] - base
    return [struct.unpack_from("<IIIII", data, headers + i * 0x38)[1:] for i in range(count)]


def read_at(data, sections, address, length):
    for va, vs, ra, rs in sections:
        if va <= address < va + vs:
            offset = address - va
            return data[ra + offset: ra + min(rs, offset + length)]
    return None


def find_clears():
    data = open(XBE, "rb").read()
    sections = load_sections(data)
    funcs = sorted((int(f["address"], 16), f["name"]) for f in json.load(open(SYMBOLS)))
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    md.detail = True
    clears = []   # (dst, bytes or None, fill or None, function, site)
    for i, (start, name) in enumerate(funcs):
        if start >= LIBRARY_START:
            break
        end = min(funcs[i + 1][0] if i + 1 < len(funcs) else start + 0x1000, start + 0x20000)
        code = read_at(data, sections, start, end - start)
        if not code:
            continue
        regs = {}
        for ins in md.disasm(code, start):
            m, ops = ins.mnemonic, ins.operands
            dest = ins.reg_name(ops[0].reg) if ops and ops[0].type == x86.X86_OP_REG else None
            if m in ("rep stosd", "rep stosw", "rep stosb"):
                unit = {"rep stosd": 4, "rep stosw": 2, "rep stosb": 1}[m]
                dst, n = regs.get("edi"), regs.get("ecx")
                if dst is not None and DATA_START <= dst < DATA_END:
                    clears.append((dst, n * unit if n is not None else None, regs.get("eax"), name, ins.address))
                regs.pop("edi", None)
                regs.pop("ecx", None)
            elif m == "mov" and dest and ops[1].type == x86.X86_OP_IMM:
                regs[dest] = ops[1].imm & 0xFFFFFFFF
            elif m == "mov" and dest and ops[1].type == x86.X86_OP_REG and ins.reg_name(ops[1].reg) in regs:
                regs[dest] = regs[ins.reg_name(ops[1].reg)]
            elif m == "lea" and dest and ops[1].mem.base == 0 and ops[1].mem.index == 0:
                regs[dest] = ops[1].mem.disp & 0xFFFFFFFF
            elif m == "xor" and dest and ops[1].type == x86.X86_OP_REG and ops[1].reg == ops[0].reg:
                regs[dest] = 0
            elif m == "call":
                for r in ("eax", "ecx", "edx"):
                    regs.pop(r, None)
            elif dest and m not in ("cmp", "test", "push"):
                regs.pop(dest, None)
    return clears


def source_literals():
    found = []
    for folder, _, files in os.walk(os.path.join(ROOT, "src", "action")):
        for f in files:
            if not f.endswith((".c", ".cpp", ".h", ".inc")) or f.startswith("autogenerated"):
                continue
            path = os.path.join(folder, f)
            rel = os.path.relpath(path, ROOT).replace("\\", "/")
            for number, line in enumerate(open(path, encoding="utf-8", errors="replace"), 1):
                for m in re.finditer(r"0x([0-9a-fA-F]{5,8})(?![0-9a-fA-F])", line):
                    address = int(m.group(1), 16)
                    if DATA_START <= address < DATA_END:
                        found.append((address, rel, number, line.strip()))
    return found


def main():
    overlaps_only = "--overlaps" in sys.argv
    injected = set(re.findall(r"XbeAddress\(&(\w+)\)", open(INJECTIONS).read()))
    regions = defaultdict(set)
    for dst, n, fill, name, site in find_clears():
        regions[(dst, n if n is not None else 4)].add((name, fill))
    literals = source_literals()
    for (dst, n), who in sorted(regions.items()):
        inside = [l for l in literals if dst <= l[0] < dst + n]
        if overlaps_only and len(inside) <= 1:
            continue
        names = ", ".join(sorted({w + ("*" if w in injected else "") for w, _ in who}))
        fills = {f for _, f in who}
        fill = "" if fills == {0} else "  fill " + ", ".join("?" if f is None else "%#x" % f for f in fills)
        print("%08x +%-8s %s%s" % (dst, hex(n), names, fill))
        for address, path, number, text in inside:
            print("    %08x  %s:%d  %s" % (address, path, number, text[:120]))


if __name__ == "__main__":
    main()
