#!/usr/bin/env python3
"""Coverage of the action engine's globals: which ones only our code touches now, and what else still does.

A global can move into the DLL - its `#define Name (*(T*)address)` becoming a definition of our own - once no
game code that can still run touches it. This works that out from Ghidra's references (tools/xrefs_action.json,
written by ghidra/NightfireSync.py) and our source:

  - the globals are the ones src/action defines at a fixed address. The size comes from a tag on the line
    before (`// XBE_GLOBAL(0x002c5750, 0x39ce4)`), or else from the definition itself: U32_AT and its
    siblings, `(*(T*)address)` and `(*(T(*)[n])address)` where T is a plain type or one with a
    `static_assert(sizeof(T) == n)` in the source. Globals it cannot size are listed, to be tagged.
  - a global we own keeps the tag, followed by our definition instead of the #define. The tag is what lets this
    go on checking it. A tag ending in `readonly` says our copy holds the same values as the game's and neither
    is ever written, so originals that still read the game's copy are harmless (a lookup table, say); a write
    from live code is still an error.
  - every reference into a global's range comes from a function (or from data: a pointer in a table). The
    function is REPLACED when an AUTOINJECT (or inject_action.cpp) jumps from its entry to ours, DEAD when
    nothing that can still run reaches it any more, and LIVE otherwise.
  - LIVE is worked out from the call graph - Ghidra's calls, plus every direct CALL/JMP found by disassembling
    each function (Ghidra misses a few, where it never disassembled the caller). It starts from the XBE's entry point, every original our code still
    calls (AUTOGEN), every function whose address sits in data, and every function with no known caller at all
    (Ghidra may have missed an indirect one - so these count as live rather than risk being wrong), and follows
    calls and address-taking from every live function that is not replaced.

    python tools/global_coverage.py              # summary: owned, ready to own, and still in use
    python tools/global_coverage.py Gfx MPGame   # what still touches these, function by function
    python tools/global_coverage.py --all        # every global, one line each
    python tools/global_coverage.py --check      # fail if a global we own is still touched by live code

A global that has initial data in the XBE (anything non-zero in the section's file data) needs that data
copied into our definition when it is owned; the summary says which. Hex literals in our source that fall
inside a tracked global (a U32_AT into the middle of a struct, say) are listed too: those should go through
the global's type instead. docs/global-coverage.md describes the workflow.
"""

import json
import os
import re
import struct
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "action")
XBE = os.path.join(ROOT, "disc", "default.xbe")
FUNCTIONS = os.path.join(ROOT, "tools", "functions_action.json")
XREFS = os.path.join(ROOT, "tools", "xrefs_action.json")
PATCH_FILES = [os.path.join(SRC, "autogenerated_injections.inc"), os.path.join(ROOT, "src", "inject_action.cpp")]
SKIP_DIRS = {"devtools"}   # test code: it runs originals on purpose, and defines nothing the game uses
DATA_START, DATA_END = 0x15D160, 0x300CC8   # .rdata to the end of .data
RETAIL_ENTRY_KEY = 0xA8FC57AB
# Code images kept in the data sections. Ghidra types a word in them as a pointer when its value happens to
# land on something - "pointers" into Gfx inside vertex shader microcode, say - so references from here are
# not references.
NOT_POINTERS = [(0x0019CD08, 0x001B4D78, "vertex shader microcode (VtxShaderFunctionTokenTable's programs)"),
                (0x00300CE0, 0x00307E60, "the DOLBY section's DSP image")]

AT_SIZES = {"U8": 1, "I8": 1, "BOOL8": 1, "U16": 2, "I16": 2, "U32": 4, "I32": 4, "FLOAT": 4, "PTR": 4,
            "DOUBLE": 8}
PLAIN_SIZES = {
    1: "char uchar byte bool BOOL8 uint8_t int8_t undefined undefined1 signed_char unsigned_char",
    2: "short ushort uint16_t int16_t undefined2 wchar_t",
    4: "int uint uint32_t int32_t float long ulong undefined4 HASHCODE DWORD BOOL size_t unsigned signed",
    8: "double longlong ulonglong uint64_t int64_t undefined8",
}
PLAIN = {t: n for n, names in PLAIN_SIZES.items() for t in names.split()}
HEX = r"0x([0-9a-fA-F]{5,8})u?"


# ------------------------------------------------------------------------------------------------ the source

def source_files():
    for folder, dirs, files in os.walk(SRC):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in files:
            if f.endswith((".c", ".cpp", ".h")) and not f.startswith("autogenerated"):
                yield os.path.join(folder, f)


def rel(path):
    return os.path.relpath(path, ROOT).replace("\\", "/")


def type_size(spec, struct_sizes):
    """Size of a C type as written in a cast ("GameState_t", "obj_tag *", "char"), or None."""
    spec = re.sub(r"\b(const|volatile|struct|unsigned)\b", lambda m: "unsigned" if m.group(1) == "unsigned" else "",
                  spec).strip()
    if spec.endswith("*"):
        return 4
    spec = spec.replace("unsigned int", "uint").replace("unsigned char", "uchar").replace("unsigned short", "ushort")
    return PLAIN.get(spec) or struct_sizes.get(spec)


def parse_define(body, struct_sizes):
    """(address, size or None) for a #define body that names a fixed address in the data sections."""
    m = re.fullmatch(r"\(?\s*(\w+)_AT\(\s*" + HEX + r"\s*\)\s*\)?", body)
    if m and m.group(1) in AT_SIZES:
        return int(m.group(2), 16), AT_SIZES[m.group(1)]
    # (*(T(*)[n])address)
    m = re.fullmatch(r"\(\s*\*\s*\(\s*([\w\s\*]+?)\s*\(\s*\*\s*\)\s*\[\s*(\w+)\s*\]\s*\)\s*\(?\s*" + HEX + r"\s*\)?\s*\)", body)
    if m:
        element, count = type_size(m.group(1), struct_sizes), m.group(2)
        count = int(count, 0) if re.fullmatch(r"0x[0-9a-fA-F]+|\d+", count) else struct_sizes.get("#" + count)
        return int(m.group(3), 16), element * count if element and count else None
    # (*(T*)address) / (*((T*)address)) / (*(T*)(address))
    m = re.fullmatch(r"\(\s*\*\s*\(*\s*([\w\s\*]+?)\s*\*\s*\)\s*\(?\s*" + HEX + r"\s*\)?\s*\)*", body)
    if m:
        return int(m.group(2), 16), type_size(m.group(1), struct_sizes)
    # ((T*)address): a pointer to however many T - sized only by a tag
    m = re.fullmatch(r"\(\s*\(\s*[\w\s\*]+?\*\s*\)\s*\(?\s*" + HEX + r"\s*\)?\s*\)", body)
    if m:
        return int(m.group(1), 16), None
    return None


def read_source():
    """Globals our source defines at a fixed address, and every data-range hex literal (for the overlap check)."""
    struct_sizes = {}
    texts = {}
    for path in source_files():
        text = open(path, encoding="utf-8", errors="replace").read()
        texts[path] = text.splitlines()
        for m in re.finditer(r"static_assert\s*\(\s*sizeof\s*\(\s*(\w+)\s*\)\s*==\s*(0x[0-9a-fA-F]+|\d+)", text):
            struct_sizes[m.group(1)] = int(m.group(2), 0)
        for m in re.finditer(r"#define\s+(\w+)\s+(0x[0-9a-fA-F]+|\d+)\b", text):
            struct_sizes["#" + m.group(1)] = int(m.group(2), 0)   # for array counts spelt as a macro

    globals_, literals = [], []
    for path, lines in texts.items():
        tag = None
        for i, line in enumerate(lines, 1):
            m = re.search(r"//\s*XBE_GLOBAL\(\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+|\d+)\s*\)(.*)", line)
            if m:
                tag = (int(m.group(1), 16), int(m.group(2), 0), i, "readonly" in m.group(3).split())
                continue
            d = re.match(r"\s*#define\s+(\w+)\s+(.*?)\s*(//.*)?$", line)
            parsed = parse_define(d.group(2), struct_sizes) if d else None
            if tag and line.strip():
                if parsed:                                   # still the game's, with its size given
                    globals_.append(dict(name=d.group(1), address=tag[0], size=tag[1], file=rel(path), line=i,
                                         owned=False, tagged=True))
                else:                                        # our own definition
                    n = re.search(r"(\w+)\s*(\[[^\]]*\])*\s*(=[^;]*)?[;{]", line)
                    globals_.append(dict(name=n.group(1) if n else "?", address=tag[0], size=tag[1], file=rel(path),
                                         line=i, owned=True, tagged=True, readonly=tag[3]))
                tag = None
                continue
            if parsed and DATA_START <= parsed[0] < DATA_END:
                globals_.append(dict(name=d.group(1), address=parsed[0], size=parsed[1], file=rel(path), line=i,
                                     owned=False, tagged=False))
            if not line.lstrip().startswith("//"):
                code = re.sub(r'"(\\.|[^"\\])*"', '""', line).split("//")[0]   # not inside strings
                for m in re.finditer(HEX, code):
                    a = int(m.group(1), 16)
                    if DATA_START <= a < DATA_END:
                        literals.append((a, rel(path), i, line.strip()))
    return globals_, literals


def originals_we_call():
    """Entry points of originals our code still calls: every AUTOGEN declaration outside the test code."""
    names = set()
    for path in source_files():
        lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
        for i, line in enumerate(lines):
            if re.match(r"\s*//\s*AUTOGEN\b", line):
                for nxt in lines[i + 1:i + 4]:
                    m = re.search(r"(\w+)\s*\(", nxt)
                    if m:
                        names.add(m.group(1))
                        break
    return names


# ------------------------------------------------------------------------------------------------ the binary

def read_xbe():
    data = open(XBE, "rb").read()
    base = struct.unpack_from("<I", data, 0x104)[0]
    count = struct.unpack_from("<I", data, 0x11C)[0]
    headers = struct.unpack_from("<I", data, 0x120)[0] - base
    entry = struct.unpack_from("<I", data, 0x128)[0] ^ RETAIL_ENTRY_KEY
    sections = [struct.unpack_from("<IIIII", data, headers + i * 0x38)[1:] for i in range(count)]

    def nonzero(address, size):
        for va, vs, ra, rs in sections:
            if va <= address < va + vs:
                lo, hi = address - va, min(address - va + size, rs)
                return hi > lo and any(data[ra + lo: ra + hi])
        return False

    def read(address, size):
        for va, vs, ra, rs in sections:
            if va <= address < va + vs:
                return data[ra + address - va: ra + min(rs, address - va + size)]
        return None
    return nonzero, read, entry


def direct_calls(funcs, read):
    """(caller, callee) for every direct CALL or JMP from one function's code to another's entry."""
    import capstone
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    entries = sorted(funcs)
    found = set()
    for i, start in enumerate(entries):
        end = entries[i + 1] if i + 1 < len(entries) else start + 0x1000
        code = read(start, min(end - start, 0x20000))
        if not code:
            continue
        for address, size, mnemonic, operand in md.disasm_lite(code, start):
            if mnemonic in ("call", "jmp") and operand.startswith("0x"):
                target = int(operand, 16)
                if target != start and target in funcs:
                    found.add((start, target))
    return found


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a for a in sys.argv[1:] if a.startswith("--")}
    if not os.path.exists(XREFS):
        sys.exit("%s is missing: run ghidra/NightfireSync.py in Ghidra on default.xbe" % rel(XREFS))

    funcs = {int(f["address"], 16): f["name"] for f in json.load(open(FUNCTIONS))}
    by_name = {n: a for a, n in funcs.items()}
    replaced = set()
    for p in PATCH_FILES:
        for m in re.finditer(r"WriteJmpTo\(\s*(0x[0-9a-fA-F]+)", open(p, encoding="utf-8", errors="replace").read()):
            replaced.add(int(m.group(1), 16))

    xrefs = [(int(t, 16), int(f, 16), int(fn, 16) if fn else None, k) for t, f, fn, k in json.load(open(XREFS))]
    ignored = [x for x in xrefs if x[2] is None and any(lo <= x[1] < hi for lo, hi, _ in NOT_POINTERS)]
    xrefs = [x for x in xrefs if not (x[2] is None and any(lo <= x[1] < hi for lo, hi, _ in NOT_POINTERS))]
    nonzero, read, entry = read_xbe()

    # The call graph, and liveness over it.
    edges = defaultdict(set)      # function -> functions it calls or takes the address of
    referenced = set()
    roots = {entry} | {by_name[n] for n in originals_we_call() if n in by_name}
    for to, frm, fn, kind in xrefs:
        if to in funcs:
            referenced.add(to)
            if fn is None:
                roots.add(to)                                # a pointer in data
            else:
                edges[fn].add(to)
    for caller, callee in direct_calls(funcs, read):
        edges[caller].add(callee)
        referenced.add(callee)
    roots |= {f for f in funcs if f not in referenced}       # no known caller: assume something reaches it
    live, work = set(), [f for f in roots if f not in replaced]
    while work:
        f = work.pop()
        if f in live or f in replaced:
            continue
        live.add(f)
        work.extend(edges[f])

    def status(fn):
        if fn is None:
            return "LIVE"
        return "REPLACED" if fn in replaced else "LIVE" if fn in live else "DEAD"

    # The globals.
    globals_, literals = read_source()
    by_address = defaultdict(list)
    for g in globals_:
        by_address[(g["address"], g["size"], g["owned"])].append(g)
    merged = []
    for (address, size, owned), gs in by_address.items():
        g = dict(gs[0])
        g["also"] = ["%s:%d" % (x["file"], x["line"]) for x in gs[1:]]
        merged.append(g)
    unsized = [g for g in merged if g["size"] is None]
    sized = sorted((g for g in merged if g["size"]), key=lambda g: g["address"])
    xrefs.sort()
    tos = [x[0] for x in xrefs]
    import bisect
    for g in sized:
        lo, hi = bisect.bisect_left(tos, g["address"]), bisect.bisect_left(tos, g["address"] + g["size"])
        g["refs"] = xrefs[lo:hi]
        g["initialised"] = nonzero(g["address"], g["size"])
        g["inside"] = [o["name"] for o in sized if o is not g and o["address"] <= g["address"] and
                       g["address"] + g["size"] <= o["address"] + o["size"] and o["size"] > g["size"]]
        g["literals"] = [l for l in literals if g["address"] <= l[0] < g["address"] + g["size"] and
                         not (l[1] == g["file"] and l[2] == g["line"]) and
                         "%s:%d" % (l[1], l[2]) not in g["also"]]

    # Live references. One from data - a pointer stored in a table - counts only while the table holding it can
    # still be used: a pointer inside the game's copy of a table we own, or of one nothing live reads any more,
    # is never followed. That can cascade (a pane list pointing at panes pointing at sprite tables), so repeat
    # until nothing changes.
    def holder(address):
        for o in sized:
            if o["address"] <= address < o["address"] + o["size"]:
                return o
        return None
    for g in sized:
        g["holders"] = {x[1]: holder(x[1]) for x in g["refs"] if x[2] is None}
    unused = set()
    while True:
        for g in sized:
            g["live"] = sorted({(x[2], x[1] if x[2] is None else None) for x in g["refs"]
                                if status(x[2]) == "LIVE" and not
                                (x[2] is None and g["holders"][x[1]] is not None and
                                 id(g["holders"][x[1]]) in unused and g["holders"][x[1]] is not g)},
                               key=lambda t: (t[0] or 0, t[1] or 0))
        now = {id(g) for g in sized if g["owned"] or not g["live"]}
        if now == unused:
            break
        unused = now

    def describe(g):
        return "%-28s %08x +%-7s %s:%d" % (g["name"], g["address"], hex(g["size"]), g["file"], g["line"])

    def live_list(g, limit=None):
        out = []
        for fn, frm in g["live"][:limit]:
            if fn is None:
                out.append("data at %08x" % frm)
            else:
                n = sum(1 for x in g["refs"] if x[2] == fn)
                out.append("%s (%08x, %d ref%s)" % (funcs.get(fn, "?"), fn, n, "s" if n > 1 else ""))
        return out

    def live_writes(g):
        return [x for x in g["refs"] if x[3] == "W" and status(x[2]) == "LIVE"]
    owned_bad = [g for g in sized if g["owned"] and g["live"] and (not g.get("readonly") or live_writes(g))]
    shared = [g for g in sized if g["owned"] and g["live"] and g not in owned_bad]
    if "--check" in flags:
        for g in owned_bad:
            print("OWNED BUT STILL IN USE: " + describe(g))
            for s in live_list(g):
                print("    " + s)
        sys.exit(1 if owned_bad else 0)

    if args:
        for g in sized + unsized:
            if g["name"] not in args:
                continue
            print(describe(g) if g["size"] else "%s: size unknown, tag it with // XBE_GLOBAL(address, size)" % g["name"])
            if not g["size"]:
                continue
            print("  %s; %d references, %d from live code%s%s" % (
                "owned" if g["owned"] else "the game's", len(g["refs"]), len(g["live"]),
                "; has initial data in the XBE" if g["initialised"] else "",
                "; inside " + ", ".join(g["inside"]) if g["inside"] else ""))
            by_fn = defaultdict(list)
            for to, frm, fn, kind in g["refs"]:
                by_fn[fn].append((to, frm, kind))
            for fn, rs in sorted(by_fn.items(), key=lambda t: (status(t[0]), t[0] or 0)):
                name = "data" if fn is None else "%s (%08x)" % (funcs.get(fn, "?"), fn)
                print("    %-8s %-48s %s" % (status(fn), name,
                                            " ".join("%s+%x%s" % ("", to - g["address"], k) for to, frm, k in rs[:8]) +
                                            (" ..." if len(rs) > 8 else "")))
            for a, path, line, text in g["literals"]:
                print("    SOURCE   %s:%d  %s" % (path, line, text[:100]))
        return

    owned = [g for g in sized if g["owned"]]
    ready = [g for g in sized if not g["owned"] and not g["live"] and not g["inside"]]
    in_use = [g for g in sized if not g["owned"] and g["live"]]
    print("%d globals: %d owned, %d ready to own, %d still used by game code, %d of unknown size" % (
        len(merged), len(owned), len(ready), len(in_use), len(unsized)))
    print("functions: %d replaced, %d dead, %d live; %d \"pointers\" inside code images ignored" % (
        len(replaced & set(funcs)), len(set(funcs) - replaced - live), len(live), len(ignored)))
    if owned_bad:
        print("\nOWNED BUT STILL IN USE - these read and write the game's copy, not ours:")
        for g in owned_bad:
            print("  " + describe(g) + "   " + ", ".join(live_list(g, 4)))
    if shared:
        print("\nOwned, identical read-only copies the game's code still reads (harmless):")
        for g in shared:
            print("  " + describe(g) + "   " + ", ".join(live_list(g, 3)))
    print("\nReady to own (nothing live touches them):")
    for g in ready:
        print("  " + describe(g) + ("   [has initial data]" if g["initialised"] else "") +
              ("   [raw addresses in our source: %d]" % len(g["literals"]) if g["literals"] else ""))
    limit = None if "--all" in flags else 25
    print("\nStill used by game code (fewest live functions first):")
    for g in sorted(in_use, key=lambda g: len(g["live"]))[:limit]:
        more = len(g["live"]) - 3
        print("  %s   %d: %s%s" % (describe(g), len(g["live"]), ", ".join(live_list(g, 3)),
                                  " +%d more" % more if more > 0 else ""))
    if limit and len(in_use) > limit:
        print("  ... %d more (--all)" % (len(in_use) - limit))
    overlapping = [g for g in sized if g["literals"] or g["inside"]]
    if overlapping:
        print("\nReached through a raw address or a second definition inside another global:")
        for g in overlapping:
            why = (["inside " + ", ".join(g["inside"])] if g["inside"] else []) + \
                  ["%s:%d" % (l[1], l[2]) for l in g["literals"]]
            print("  %-28s %s" % (g["name"], "; ".join(why)))
    if unsized:
        print("\nUnknown size (tag with // XBE_GLOBAL(address, size) on the line before):")
        for g in unsized:
            print("  %-28s %08x %s:%d" % (g["name"], g["address"], g["file"], g["line"]))


if __name__ == "__main__":
    main()
