#!/usr/bin/env python3
"""Coverage of the game's globals (the action engine's, or with --driving the driving engine's): which ones only
our code touches now, and what else still does.

A global can move into the DLL - its `#define Name (*(T*)address)` becoming a definition of our own - once no
game code that can still run touches it. This works that out from Ghidra's references (tools/xrefs_action.json,
written by ghidra/NightfireSync.py) and our source:

  - the globals are the ones src/action defines at a fixed address. The size comes from a tag on the line
    before (`// XBE_GLOBAL(0x002c5750, 0x39ce4)`), or else from the definition itself: U32_AT and its
    siblings, `(*(T*)address)` and `(*(T(*)[n])address)` where T is a plain type or one with a
    `static_assert(sizeof(T) == n)` in the source. Globals it cannot size are listed, to be tagged.
  - a global we own keeps the tag, followed by our definition instead of the #define. The tag is what lets this
    go on checking it. A tag ending in `readonly` says our copy holds the same values as the game's and neither
    is ever written, so originals that still read the game's copy are harmless (a lookup table, say); a write
    from live code is still an error.
  - every reference into a global's range comes from a function (or from data: a pointer in a table). The
    function is REPLACED when an AUTOINJECT (or inject_action.cpp) jumps from its entry to ours, DEAD when
    nothing that can still run reaches it any more, and LIVE otherwise.
  - LIVE is worked out from the call graph - Ghidra's calls, plus every direct CALL/JMP found by disassembling
    each function (Ghidra misses a few, where it never disassembled the caller). It starts from the XBE's entry point, every original our code still
    calls (AUTOGEN), every function whose address sits in data, and every function with no known caller at all
    (Ghidra may have missed an indirect one - so these count as live rather than risk being wrong), and follows
    calls and address-taking from every live function that is not replaced.

    python tools/global_coverage.py              # summary: owned, ready to own, and still in use
    python tools/global_coverage.py Gfx MPGame   # what still touches these, function by function
    python tools/global_coverage.py --all        # every global, one line each
    python tools/global_coverage.py --check      # fail if a global we own is still touched by live code
    python tools/global_coverage.py --driving    # the same for the driving engine (with any of the above)

A global that has initial data in the XBE (anything non-zero in the section's file data) needs that data
copied into our definition when it is owned; the summary says which. Hex literals in our source that fall
inside a tracked global (a U32_AT into the middle of a struct, say) are listed too: those should go through
the global's type instead. docs/global-coverage.md describes the workflow.
"""

import json
import os
import re
import struct
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "action")
XBE = os.path.join(ROOT, "disc", "default.xbe")
FUNCTIONS = os.path.join(ROOT, "tools", "functions_action.json")
XREFS = os.path.join(ROOT, "tools", "xrefs_action.json")
PATCH_FILES = [os.path.join(SRC, "autogenerated_injections.inc"), os.path.join(ROOT, "src", "inject_action.cpp")]
SKIP_DIRS = {"devtools"}   # test code: it runs originals on purpose, and defines nothing the game uses
DATA_START, DATA_END = 0x15D160, 0x300CC8   # .rdata to the end of .data
RETAIL_ENTRY_KEY = 0xA8FC57AB
# Code images kept in the data sections. Ghidra types a word in them as a pointer when its value happens to
# land on something - "pointers" into Gfx inside vertex shader microcode, say - so references from here are
# not references.
NOT_POINTERS = [(0x0019CD08, 0x001B4D78, "vertex shader microcode (VtxShaderFunctionTokenTable's programs)"),
                (0x00300CE0, 0x00307E60, "the DOLBY section's DSP image")]
# Pairs of 16-bit values Ghidra typed as a pointer because together they land inside FileSystem (0x002cxxxx) or
# LaunchInfoData (0x0030xxxx): the menu's item tables at 0x179000-0x17c000 are runs of shorts, and 0x1d5c90 is two
# shorts in a record. (One of them is not even word-aligned.)
# The initialiser tables _rtinit and _cinit walk (__xi/__xc). Our startup (engine/XboxStartup.cpp) calls their
# entries by name instead, leaving out DSOUND's, so a function being listed here no longer makes it run.
NOT_POINTERS += [(0x00163100, 0x00163170, "the C runtime's initialiser tables, which our startup no longer walks")]
NOT_POINTERS += [(a, a + 4, "two 16-bit values, not a pointer") for a in
                 (0x00179050, 0x00179224, 0x0017929C, 0x00179320, 0x0017A8E4, 0x0017AAFA, 0x0017BEBC, 0x0017BF4C,
                  0x001D5C90)]
# Generated entry-point tables of a seam that patches every library entry point it lists, implemented or stubbed
# (src/common/xbeEntrySeam.cpp): each XBE_ENTRY's address counts as replaced. The action engine's seams sit above
# its libraries instead, so it has none.
SEAM_TABLES = []
# Generated files whose XbeOriginal<...>(0x...) calls are originals our code still calls, by address (the driving
# engine's AUTOGEN bodies; its C++ names and overloads make the address the reliable key). The action engine's are
# found by name from the AUTOGEN declarations.
ORIGINAL_CALL_FILES = []
# Code that is not part of the function Ghidra put it in, whose calls and references are not that function's:
# (start, end, why). The driving engine has a this-adjusting thunk of DSOUND's inside an XAPI function's body.
NOT_CALLS = []
# Functions with no known caller that research has shown are never called (so they need not count as live, the
# safe default for "no known caller"): (start, end, why).
KNOWN_UNCALLED = []
GAP_RULE = True


def use_engine(engine):
    """Points this module at the driving engine's binary, exports and source instead of the action engine's (the
    default). tools/function_coverage.py --driving uses it; the globals report itself is the action engine's."""
    global SRC, XBE, FUNCTIONS, XREFS, PATCH_FILES, DATA_START, DATA_END, NOT_POINTERS, SEAM_TABLES, ORIGINAL_CALL_FILES,         NOT_CALLS, KNOWN_UNCALLED
    if engine != "driving":
        return
    SRC = os.path.join(ROOT, "src", "driving")
    XBE = os.path.join(ROOT, "disc", "Driving.xbe")
    FUNCTIONS = os.path.join(ROOT, "tools", "functions_driving.json")
    XREFS = os.path.join(ROOT, "tools", "xrefs_driving.json")
    PATCH_FILES = [os.path.join(SRC, "autogenerated_injections.inc"), os.path.join(ROOT, "src", "inject_driving.cpp")]
    DATA_START, DATA_END = 0x189BE0, 0x24B5BC   # .rdata to the end of .data
    NOT_POINTERS = [(0x0024B5C0, 0x00252740, "the DOLBY section's DSP image"),
                    (0x001B3DB0, 0x001B4904, "the C++ initialiser table, which our startup no longer walks: "
                                             "RunStaticInitialisers (src/driving/engine/StaticInitTable.cpp) does "
                                             "its entries' work, leaving out DSOUND's"),
                    (0x001D18B8, 0x001D1950, "a software vertex-transform library's function tables, which nothing "
                                             "references (docs/driving/maths.md, section 6)")]
    SEAM_TABLES = [os.path.join(SRC, "gfx", "d3d8Entries.inc"), os.path.join(SRC, "gfx", "d3d8EntriesUnnamed.inc"),
                   os.path.join(SRC, "sound", "dsoundEntries.inc")]
    ORIGINAL_CALL_FILES = [os.path.join(SRC, "autogenerated_functions.inc")]
    KNOWN_UNCALLED = [(0x00156C00, 0x0015CD20, "the C++ static initialisers, reached only through the initialiser "
                                               "table our startup no longer walks"),
                      (0x00108F70, 0x0010A5A1, "the software vertex-transform library behind the unreferenced tables at "
                                               "0x001d18b8 (docs/driving/maths.md, section 6)")]
    NOT_CALLS = [(0x0014BFE1, 0x0014BFE9, "SUB ECX,8 / JMP 0x17d475: a this-adjusting thunk in a DSOUND vtable "
                                          "(0x001a7630), inside FUN_0014bfd3's body")]

AT_SIZES = {"U8": 1, "I8": 1, "BOOL8": 1, "U16": 2, "I16": 2, "U32": 4, "I32": 4, "FLOAT": 4, "PTR": 4,
            "DOUBLE": 8}
PLAIN_SIZES = {
    1: "char uchar byte bool BOOL8 uint8_t int8_t undefined undefined1 signed_char unsigned_char",
    2: "short ushort uint16_t int16_t undefined2 wchar_t",
    4: "int uint uint32_t int32_t float long ulong undefined4 HASHCODE DWORD BOOL size_t unsigned signed",
    8: "double longlong ulonglong uint64_t int64_t undefined8",
}
PLAIN = {t: n for n, names in PLAIN_SIZES.items() for t in names.split()}
HEX = r"0x([0-9a-fA-F]{5,8})u?"


# ------------------------------------------------------------------------------------------------ the source

def source_files():
    for folder, dirs, files in os.walk(SRC):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in files:
            if f.endswith((".c", ".cpp", ".h", ".hpp")) and not f.startswith("autogenerated"):
                yield os.path.join(folder, f)


def rel(path):
    return os.path.relpath(path, ROOT).replace("\\", "/")


def type_size(spec, struct_sizes):
    """Size of a C type as written in a cast ("GameState_t", "obj_tag *", "char"), or None."""
    spec = re.sub(r"\b(const|volatile|struct|unsigned)\b", lambda m: "unsigned" if m.group(1) == "unsigned" else "",
                  spec).strip()
    if spec.endswith("*"):
        return 4
    spec = spec.replace("unsigned int", "uint").replace("unsigned char", "uchar").replace("unsigned short", "ushort")
    return PLAIN.get(spec) or struct_sizes.get(spec) or struct_sizes.get(spec.split("::")[-1])


def parse_define(body, struct_sizes):
    """(address, size or None) for a #define body that names a fixed address in the data sections."""
    m = re.fullmatch(r"\(?\s*(\w+)_AT\(\s*" + HEX + r"\s*\)\s*\)?", body)
    if m and m.group(1) in AT_SIZES:
        return int(m.group(2), 16), AT_SIZES[m.group(1)]
    # (*(T(*)[n])address)
    m = re.fullmatch(r"\(\s*\*\s*\(\s*([\w:\s\*]+?)\s*\(\s*\*\s*\)\s*\[\s*(\w+)\s*\]\s*\)\s*\(?\s*" + HEX + r"\s*\)?\s*\)", body)
    if m:
        element, count = type_size(m.group(1), struct_sizes), m.group(2)
        count = int(count, 0) if re.fullmatch(r"0x[0-9a-fA-F]+|\d+", count) else struct_sizes.get("#" + count)
        return int(m.group(3), 16), element * count if element and count else None
    # (*(T*)address) / (*((T*)address)) / (*(T*)(address))
    m = re.fullmatch(r"\(\s*\*\s*\(*\s*([\w:\s\*]+?)\s*\*\s*\)\s*\(?\s*" + HEX + r"\s*\)?\s*\)*", body)
    if m:
        return int(m.group(2), 16), type_size(m.group(1), struct_sizes)
    # ((T*)address): a pointer to however many T - sized only by a tag
    m = re.fullmatch(r"\(\s*\(\s*[\w:\s\*]+?\*\s*\)\s*\(?\s*" + HEX + r"\s*\)?\s*\)", body)
    if m:
        return int(m.group(1), 16), None
    return None


def read_source():
    """Globals our source defines at a fixed address, and every data-range hex literal (for the overlap check)."""
    struct_sizes = {}
    texts = {}
    for path in source_files():
        text = open(path, encoding="utf-8", errors="replace").read()
        texts[path] = text.splitlines()
        for m in re.finditer(r"static_assert\s*\(\s*sizeof\s*\(\s*([\w:]+)\s*\)\s*==\s*(0x[0-9a-fA-F]+|\d+)", text):
            struct_sizes[m.group(1)] = int(m.group(2), 0)
            struct_sizes.setdefault(m.group(1).split("::")[-1], int(m.group(2), 0))   # EAGL::Foo also as Foo
        for m in re.finditer(r"#define\s+(\w+)\s+(0x[0-9a-fA-F]+|\d+)\b", text):
            struct_sizes["#" + m.group(1)] = int(m.group(2), 0)   # for array counts spelt as a macro

    globals_, literals = [], []
    casts = []   # (name, path, line, text): &name cast to another pointer type
    for path, lines in texts.items():
        for i, line in enumerate(lines, 1):
            for m in re.finditer(r"\(\s*[\w\s]+\*\s*\)\s*&\s*(\w+)\b(?!\s*(\.|\[|->))", line.split("//")[0]):
                casts.append((m.group(1), rel(path), i, line.strip()))
    for path, lines in texts.items():
        tag = None
        for i, line in enumerate(lines, 1):
            m = re.search(r"//\s*XBE_GLOBAL\(\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+|\d+)\s*\)(.*)", line)
            if m:
                tag = (int(m.group(1), 16), int(m.group(2), 0), i, "readonly" in m.group(3).split())
                continue
            d = re.match(r"\s*#define\s+(\w+)\s+(.*?)\s*(//.*)?$", line)
            parsed = parse_define(d.group(2), struct_sizes) if d else None
            if tag and line.strip():
                if parsed:                                   # still the game's, with its size given
                    globals_.append(dict(name=d.group(1), address=tag[0], size=tag[1], file=rel(path), line=i,
                                         owned=False, tagged=True))
                else:                                        # our own definition
                    n = re.search(r"(\w+)\s*(\[[^\]]*\])*\s*(=[^;]*)?[;{]", line)
                    globals_.append(dict(name=n.group(1) if n else "?", address=tag[0], size=tag[1], file=rel(path),
                                         line=i, owned=True, tagged=True, readonly=tag[3]))
                tag = None
                continue
            if parsed and DATA_START <= parsed[0] < DATA_END:
                globals_.append(dict(name=d.group(1), address=parsed[0], size=parsed[1], file=rel(path), line=i,
                                     owned=False, tagged=False))
            if not line.lstrip().startswith("//"):
                code = re.sub(r'"(\\.|[^"\\])*"', '""', line).split("//")[0]   # not inside strings
                if re.fullmatch(r"\s*(0x[0-9a-fA-F]+u?,?\s*)+", code):
                    continue   # a row of a data table (shader tokens, say), not addresses
                for m in re.finditer(HEX, code):
                    a = int(m.group(1), 16)
                    if DATA_START <= a < DATA_END:
                        literals.append((a, rel(path), i, line.strip()))
    read_source.casts = casts
    return globals_, literals


def functions_our_code_points_at(funcs):
    """Originals our code calls by address: a function's address cast to a function pointer
    (reinterpret_cast<void (*)(void)>(0x...), (int (*)(char*))(0x...)) or loaded into a register in inline asm
    (mov eax, 0x... then call eax). The game's own reference to such a function may have been in code we replaced,
    so without this it could look dead and the globals it touches ownable when they are not - as InputEventList
    and Borders once were. Any other raw function address in the source is not counted: many are patch targets
    or plain constants."""
    cast = re.compile(r"\(\s*(?:__cdecl|__stdcall|__fastcall|__thiscall)?\s*\*\s*\)")
    asm = re.compile(r"\bmov\s+e[abcd]x\s*,\s*0x([0-9a-fA-F]{5,8})\b")
    out = set()
    for path in source_files():
        for line in open(path, encoding="utf-8", errors="replace"):
            code = re.sub(r'"(\\.|[^"\\])*"', '""', line).split("//")[0]
            hits = [m.group(1) for m in asm.finditer(code)]
            if cast.search(code):
                hits += [m.group(1) for m in re.finditer(HEX, code)]
            for h in hits:
                if int(h, 16) in funcs:
                    out.add(int(h, 16))
    return out


def addresses_our_code_names():
    """Every hex address in our source outside comments and strings, as a set of ints."""
    out = set()
    for path in source_files():
        for line in open(path, encoding="utf-8", errors="replace"):
            code = re.sub(r'"(\\.|[^"\\])*"', '""', line).split("//")[0]
            out.update(int(m.group(1), 16) for m in re.finditer(HEX, code))
    return out


def originals_we_call():
    """Entry points of originals our code still calls: every AUTOGEN declaration outside the test code."""
    names = set()
    for path in source_files():
        lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
        for i, line in enumerate(lines):
            if re.match(r"\s*//\s*AUTOGEN\b", line):
                for nxt in lines[i + 1:i + 4]:
                    m = re.search(r"(\w+)\s*\(", nxt)
                    if m:
                        names.add(m.group(1))
                        break
    return names


# ------------------------------------------------------------------------------------------------ the binary

def read_xbe():
    data = open(XBE, "rb").read()
    base = struct.unpack_from("<I", data, 0x104)[0]
    count = struct.unpack_from("<I", data, 0x11C)[0]
    headers = struct.unpack_from("<I", data, 0x120)[0] - base
    entry = struct.unpack_from("<I", data, 0x128)[0] ^ RETAIL_ENTRY_KEY
    sections = [struct.unpack_from("<IIIII", data, headers + i * 0x38)[1:] for i in range(count)]

    def nonzero(address, size):
        for va, vs, ra, rs in sections:
            if va <= address < va + vs:
                lo, hi = address - va, min(address - va + size, rs)
                return hi > lo and any(data[ra + lo: ra + hi])
        return False

    def read(address, size):
        for va, vs, ra, rs in sections:
            if va <= address < va + vs:
                return data[ra + address - va: ra + min(rs, address - va + size)]
        return None
    return nonzero, read, entry


def section_named(name):
    """(start, end) of the XBE section with this name, or None."""
    data = open(XBE, "rb").read()
    base = struct.unpack_from("<I", data, 0x104)[0]
    count = struct.unpack_from("<I", data, 0x11C)[0]
    headers = struct.unpack_from("<I", data, 0x120)[0] - base
    for i in range(count):
        flags, va, vs, ra, rs, name_at = struct.unpack_from("<IIIIII", data, headers + i * 0x38)
        at = name_at - base
        if data[at:data.index(b"\0", at)].decode("ascii", "replace") == name:
            return va, va + vs
    return None


def executable_ranges():
    """(start, end) of every executable section of the XBE (section flag 4)."""
    data = open(XBE, "rb").read()
    base = struct.unpack_from("<I", data, 0x104)[0]
    count = struct.unpack_from("<I", data, 0x11C)[0]
    headers = struct.unpack_from("<I", data, 0x120)[0] - base
    ranges = []
    for i in range(count):
        flags, va, vs = struct.unpack_from("<III", data, headers + i * 0x38)
        if flags & 4:
            ranges.append((va, va + vs))
    return ranges


def touches_memory(address, read, md):
    """False only for a reference hung on an instruction that cannot be using the address: MOV reg, imm where the
    immediate is not a data address - it reads nothing and overwrites the register. Ghidra's analysis now and then
    leaves a data reference on one (a MOV AL, 1 in C_RBMPCNAME_Handler pointed into ds_gadgets). Anything else is
    kept, including PUSH reg, ADD reg, imm and CALL: Ghidra follows an address through a register by constant
    propagation, and those references are real."""
    from capstone import x86
    code = read(address, 16)
    for ins in md.disasm(code or b"", address, 1):
        ops = ins.operands
        return not (ins.mnemonic == "mov" and len(ops) == 2 and ops[0].type == x86.X86_OP_REG and
                    ops[1].type == x86.X86_OP_IMM and not DATA_START <= (ops[1].imm & 0xFFFFFFFF) < DATA_END)
    return True


def direct_calls(funcs, read):
    """(caller, callee) for every direct CALL or JMP from one function's code to another's entry."""
    import capstone
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    entries = sorted(funcs)
    found = set()
    for i, start in enumerate(entries):
        end = entries[i + 1] if i + 1 < len(entries) else start + 0x1000
        code = read(start, min(end - start, 0x20000))
        if not code:
            continue
        for address, size, mnemonic, operand in md.disasm_lite(code, start):
            if any(lo <= address < hi for lo, hi, _ in NOT_CALLS):
                continue
            if mnemonic in ("call", "jmp") and operand.startswith("0x"):
                target = int(operand, 16)
                if target != start and target in funcs:
                    found.add((start, target))
    return found


class CallGraph:
    """Every function, which are replaced, and who calls or points at whom (tools/function_coverage.py uses it too)."""

    def __init__(self):
        self.funcs = {int(f["address"], 16): f["name"] for f in json.load(open(FUNCTIONS))}
        self.by_name = {n: a for a, n in self.funcs.items()}
        self.replaced = set()
        for p in PATCH_FILES:
            for m in re.finditer(r"WriteJmpTo\(\s*(0x[0-9a-fA-F]+)", open(p, encoding="utf-8", errors="replace").read()):
                self.replaced.add(int(m.group(1), 16))
        # The seams' own patches of XDK entry points (engine/XboxStartup.cpp, sound/dsndStream.cpp), made with a
        # local WriteJump rather than through the generated table
        for p in source_files():
            for m in re.finditer(r"WriteJump\(\s*(0x[0-9a-fA-F]+)", open(p, encoding="utf-8", errors="replace").read()):
                self.replaced.add(int(m.group(1), 16))
        for p in SEAM_TABLES:
            for m in re.finditer(r"^XBE_ENTRY\w*\(\s*\w+\s*,\s*(0x[0-9a-fA-F]+)", open(p, encoding="utf-8").read(), re.M):
                self.replaced.add(int(m.group(1), 16))

        xrefs = [(int(t, 16), int(f, 16), int(fn, 16) if fn else None, k) for t, f, fn, k in json.load(open(XREFS))]
        self.ignored = [x for x in xrefs if x[2] is None and any(lo <= x[1] < hi for lo, hi, _ in NOT_POINTERS)]
        self.xrefs = [x for x in xrefs if not (x[2] is None and any(lo <= x[1] < hi for lo, hi, _ in NOT_POINTERS))]
        self.nonzero, self.read, self.entry = read_xbe()

        self.edges = defaultdict(set)      # function -> functions it calls or takes the address of
        self.pointed_at = defaultdict(set) # function -> where in data its address is stored
        referenced = set()
        self.vtable_owner = self._vtable_owners()
        self.vtable_edges = defaultdict(set)   # installer -> (method, the vtable slot holding it)
        for to, frm, fn, kind in self.xrefs:
            if fn is not None and any(lo <= frm < hi for lo, hi, _ in NOT_CALLS):
                continue
            if to in self.funcs:
                if fn is None and self.vtable_owner.get(frm) == {to}:
                    continue                   # its own body referring to itself: not a caller
                referenced.add(to)
                if fn is None and frm in self.vtable_owner:
                    for owner in self.vtable_owner[frm]:
                        self.vtable_edges[owner].add((to, frm))
                elif fn is None:
                    self.pointed_at[to].add(frm)
                else:
                    self.edges[fn].add(to)
        for caller, callee in direct_calls(self.funcs, self.read):
            self.edges[caller].add(callee)
            referenced.add(callee)
        # MSVC's exception funclets - "<owner>_Unwind_<n>" and "<owner>_Frame_Handler", the owner's name with "::" as
        # "__" - are reached only through their owner's prologue and the unwind map it hands __CxxFrameHandler, which
        # sits in data. They belong to their owner: live with it and dead with it, not roots of their own.
        by_flat = {n.replace("::", "__"): a for a, n in self.funcs.items()}
        for f, name in self.funcs.items():
            m = re.match(r"(.+?)_(?:Unwind_\d+|Frame_Handler)$", name)
            owner = by_flat.get(m.group(1)) if m else None
            if owner is not None and owner != f:
                self.edges[owner].add(f)
                self.pointed_at.pop(f, None)
                referenced.add(f)
        self.no_caller = {f for f in self.funcs if f not in referenced and
                          not any(lo <= f < hi for lo, hi, _ in KNOWN_UNCALLED)}
        self.ours_points_at = functions_our_code_points_at(self.funcs)   # e.g. Drone_SM_InitObject storing 0x4e180
        self.autogen = {self.by_name[n] for n in originals_we_call() if n in self.by_name}
        for p in ORIGINAL_CALL_FILES:
            for m in re.finditer(r"XbeOriginal<.*?>\((0x[0-9a-fA-F]+)\)", open(p, encoding="utf-8").read()):
                if int(m.group(1), 16) in self.funcs:
                    self.autogen.add(int(m.group(1), 16))

    def _vtable_owners(self):
        """For a slot of a vtable, the functions that install that vtable, so that a method only it points at is
        reachable through them (and dead with them) rather than counting as a root. A vtable here is a run of
        function addresses in data whose start (or the dword or two before it) every reference reaches by a vptr
        store - MOV dword ptr [reg + disp], vtable - in a constructor or destructor. Anything else - a table also
        referenced from data, read by other instructions, or named in our source (our own constructors install
        some) - stays a root."""
        import capstone
        from capstone import x86
        md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
        md.detail = True
        ours = addresses_our_code_names()
        refs_to = defaultdict(list)
        for to, frm, fn, kind in self.xrefs:
            refs_to[to].append((frm, fn))

        def entry_at(address):
            raw = self.read(address, 4)
            return raw is not None and len(raw) == 4 and struct.unpack("<I", raw)[0] in self.funcs

        def vptr_store(frm, base):
            code = self.read(frm, 15)
            for insn in md.disasm(code or b"", frm, 1):
                ops = insn.operands
                return (insn.mnemonic == "mov" and len(ops) == 2 and ops[0].type == x86.X86_OP_MEM and
                        ops[1].type == x86.X86_OP_IMM and ops[1].imm & 0xffffffff == base)
            return False

        owners, verdict = {}, {}
        # Code Ghidra left outside any function (a body it cut short, a method it never made a function) belongs to
        # the function whose entry comes before it, as direct_calls() already assumes for its CALLs. Only in .text,
        # the section the entry point is in: the XDK sections keep data among their code.
        import bisect
        entries = sorted(self.funcs)
        text = [(lo, hi) for lo, hi in executable_ranges() if lo <= self.entry < hi]
        for to, frm, fn, kind in self.xrefs if GAP_RULE else []:
            if fn is None and to in self.funcs and any(lo <= frm < hi for lo, hi in text):
                if entry_at(frm):
                    # a table of addresses among the code (a jump or dispatch table): reached through the functions
                    # that index it, when only functions do and our code does not name it
                    start = frm
                    while frm - start < 0x800 and entry_at(start - 4):
                        start -= 4
                    base = [a for a in range(start, frm + 1, 4) if a in refs_to][-1:]
                    if base and base[0] not in ours and all(f is not None for r, f in refs_to[base[0]]):
                        owners[frm] = {f for r, f in refs_to[base[0]]}
                    continue
                i = bisect.bisect_right(entries, frm) - 1
                if i >= 0:
                    owners[frm] = {entries[i]}
        for to, frm, fn, kind in self.xrefs:
            if fn is not None or to not in self.funcs or frm in owners or not (DATA_START <= frm < DATA_END):
                continue
            if not entry_at(frm):
                continue
            start = frm
            while frm - start < 0x800 and entry_at(start - 4):
                start -= 4
            bases = [a for a in range(start - 8, frm + 1, 4) if a in refs_to][-1:]   # adjacent vtables share a run
            if not bases or any(a in ours for a in bases):
                continue
            ok = True
            for a in bases:
                if a not in verdict:
                    verdict[a] = all(f is not None and vptr_store(r, a) for r, f in refs_to[a])
                ok = ok and verdict[a]
            if ok:
                owners[frm] = {f for a in bases for r, f in refs_to[a]}
        return owners

    def live(self, counts_as_pointer=lambda function, holder: True, no_caller=None):
        """Functions that can still run. The roots: the entry point, the originals our code calls, functions whose
        address sits in data (where counts_as_pointer agrees), and functions with no known caller (all of them,
        unless no_caller gives a subset) - Ghidra may have missed an indirect call, so those count as live rather
        than risk calling a live function dead."""
        roots = {self.entry} | self.autogen | self.ours_points_at
        roots |= {f for f, holders in self.pointed_at.items() if any(counts_as_pointer(f, h) for h in holders)}
        roots |= self.no_caller if no_caller is None else no_caller
        live, work = set(), [f for f in roots if f not in self.replaced]
        while work:
            f = work.pop()
            if f in live or f in self.replaced:
                continue
            live.add(f)
            work.extend(self.edges[f])
            work.extend(to for to, holder in self.vtable_edges[f] if counts_as_pointer(to, holder))
        return live


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a for a in sys.argv[1:] if a.startswith("--")}
    if "--driving" in flags:
        use_engine("driving")
    if not os.path.exists(XREFS):
        sys.exit("%s is missing: run ghidra/NightfireSync.py in Ghidra on the XBE" % rel(XREFS))

    graph = CallGraph()
    funcs, by_name, replaced = graph.funcs, graph.by_name, graph.replaced
    xrefs, ignored = graph.xrefs, graph.ignored
    nonzero, read, entry = graph.nonzero, graph.read, graph.entry
    live = graph.live()

    def status(fn):
        if fn is None:
            return "LIVE"
        return "REPLACED" if fn in replaced else "LIVE" if fn in live else "DEAD"

    # The globals.
    globals_, literals = read_source()
    by_address = defaultdict(list)
    for g in globals_:
        by_address[(g["address"], g["size"], g["owned"])].append(g)
    merged = []
    for (address, size, owned), gs in by_address.items():
        g = dict(gs[0])
        g["also"] = ["%s:%d" % (x["file"], x["line"]) for x in gs[1:]]
        merged.append(g)
    unsized = [g for g in merged if g["size"] is None]
    sized = sorted((g for g in merged if g["size"]), key=lambda g: g["address"])
    xrefs.sort()
    tos = [x[0] for x in xrefs]
    import bisect
    import capstone
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    md.detail = True
    spurious = 0
    for g in sized:
        lo, hi = bisect.bisect_left(tos, g["address"]), bisect.bisect_left(tos, g["address"] + g["size"])
        g["refs"] = [x for x in xrefs[lo:hi] if x[2] is None or x[3] == "C" or touches_memory(x[1], read, md)]
        spurious += hi - lo - len(g["refs"])
        g["initialised"] = nonzero(g["address"], g["size"])
        g["inside"] = [o["name"] for o in sized if o is not g and o["address"] <= g["address"] and
                       g["address"] + g["size"] <= o["address"] + o["size"] and o["size"] > g["size"]]
        g["literals"] = [l for l in literals if g["address"] <= l[0] < g["address"] + g["size"] and
                         not (l[1] == g["file"] and l[2] == g["line"]) and
                         "%s:%d" % (l[1], l[2]) not in g["also"]]

    # Live references. One from data - a pointer stored in a table - counts only while the table holding it can
    # still be used: a pointer inside the game's copy of a table we own, or of one nothing live reads any more,
    # is never followed. That can cascade (a pane list pointing at panes pointing at sprite tables), so repeat
    # until nothing changes.
    def holder(address):
        for o in sized:
            if o["address"] <= address < o["address"] + o["size"]:
                return o
        return None
    for g in sized:
        g["holders"] = {x[1]: holder(x[1]) for x in g["refs"] if x[2] is None}
    unused = set()
    while True:
        for g in sized:
            g["live"] = sorted({(x[2], x[1] if x[2] is None else None) for x in g["refs"]
                                if status(x[2]) == "LIVE" and not
                                (x[2] is None and g["holders"][x[1]] is not None and
                                 id(g["holders"][x[1]]) in unused and g["holders"][x[1]] is not g)},
                               key=lambda t: (t[0] or 0, t[1] or 0))
        now = {id(g) for g in sized if g["owned"] or not g["live"]}
        if now == unused:
            break
        unused = now

    def describe(g):
        return "%-28s %08x +%-7s %s:%d" % (g["name"], g["address"], hex(g["size"]), g["file"], g["line"])

    def live_list(g, limit=None):
        out = []
        for fn, frm in g["live"][:limit]:
            if fn is None:
                out.append("data at %08x" % frm)
            else:
                n = sum(1 for x in g["refs"] if x[2] == fn)
                out.append("%s (%08x, %d ref%s)" % (funcs.get(fn, "?"), fn, n, "s" if n > 1 else ""))
        return out

    def live_writes(g):
        return [x for x in g["refs"] if x[3] == "W" and status(x[2]) == "LIVE"]
    owned_bad = [g for g in sized if g["owned"] and g["live"] and (not g.get("readonly") or live_writes(g))]
    # Our own code still reaching into an owned global at the game's address: a second #define of it (in another
    # file, or of one of its fields) that was not converted with it, or a raw address. That code reads and writes
    # the game's copy, which nothing else uses any more.
    stale = []
    for g in sized:
        if not g["owned"]:
            continue
        for o in globals_:
            if not o["owned"] and g["address"] <= o["address"] < g["address"] + g["size"]:
                stale.append((g, "%s (%s:%d)" % (o["name"], o["file"], o["line"])))
        for a, path, line, text in g["literals"]:
            stale.append((g, "a raw address at %s:%d" % (path, line)))
    shared = [g for g in sized if g["owned"] and g["live"] and g not in owned_bad]
    if "--check" in flags:
        for g in owned_bad:
            print("OWNED BUT STILL IN USE: " + describe(g))
            for s in live_list(g):
                print("    " + s)
        for g, what in stale:
            print("OWNED BUT OUR CODE STILL USES THE GAME'S COPY: %s - %s" % (describe(g), what))
        sys.exit(1 if owned_bad or stale else 0)

    if args:
        for g in sized + unsized:
            if g["name"] not in args:
                continue
            print(describe(g) if g["size"] else "%s: size unknown, tag it with // XBE_GLOBAL(address, size)" % g["name"])
            if not g["size"]:
                continue
            print("  %s; %d references, %d from live code%s%s" % (
                "owned" if g["owned"] else "the game's", len(g["refs"]), len(g["live"]),
                "; has initial data in the XBE" if g["initialised"] else "",
                "; inside " + ", ".join(g["inside"]) if g["inside"] else ""))
            by_fn = defaultdict(list)
            for to, frm, fn, kind in g["refs"]:
                by_fn[fn].append((to, frm, kind))
            for fn, rs in sorted(by_fn.items(), key=lambda t: (status(t[0]), t[0] or 0)):
                name = "data" if fn is None else "%s (%08x)" % (funcs.get(fn, "?"), fn)
                print("    %-8s %-48s %s" % (status(fn), name,
                                            " ".join("%s+%x%s" % ("", to - g["address"], k) for to, frm, k in rs[:8]) +
                                            (" ..." if len(rs) > 8 else "")))
            for a, path, line, text in g["literals"]:
                print("    SOURCE   %s:%d  %s" % (path, line, text[:100]))
        return

    owned = [g for g in sized if g["owned"]]
    ready = [g for g in sized if not g["owned"] and not g["live"] and not g["inside"]]
    in_use = [g for g in sized if not g["owned"] and g["live"]]
    rdata = section_named(".rdata") or (0, 0)
    print("%d globals: %d owned, %d ready to own, %d still used by game code, %d of unknown size (%d of them in "
          ".rdata)" % (len(merged), len(owned), len(ready), len(in_use), len(unsized),
                       sum(1 for g in unsized if rdata[0] <= g["address"] < rdata[1])))
    print("functions: %d replaced, %d dead, %d live; %d \"pointers\" inside code images and %d references hung "
          "on a MOV reg, imm ignored" % (
              len(replaced & set(funcs)), len(set(funcs) - replaced - live), len(live), len(ignored), spurious))
    if stale:
        print("\nOWNED, BUT OUR OWN CODE STILL REACHES THE GAME'S COPY:")
        for g, what in stale:
            print("  %-28s %s" % (g["name"], what))
    if owned_bad:
        print("\nOWNED BUT STILL IN USE - these read and write the game's copy, not ours:")
        for g in owned_bad:
            print("  " + describe(g) + "   " + ", ".join(live_list(g, 4)))
    if shared:
        print("\nOwned, identical read-only copies the game's code still reads (harmless):")
        for g in shared:
            print("  " + describe(g) + "   " + ", ".join(live_list(g, 3)))
    print("\nReady to own (nothing live touches them):")
    for g in ready:
        print("  " + describe(g) + ("   [has initial data]" if g["initialised"] else "") +
              ("   [raw addresses in our source: %d]" % len(g["literals"]) if g["literals"] else ""))
    limit = None if "--all" in flags else 25
    print("\nStill used by game code (fewest live functions first):")
    for g in sorted(in_use, key=lambda g: len(g["live"]))[:limit]:
        more = len(g["live"]) - 3
        print("  %s   %d: %s%s" % (describe(g), len(g["live"]), ", ".join(live_list(g, 3)),
                                  " +%d more" % more if more > 0 else ""))
    if limit and len(in_use) > limit:
        print("  ... %d more (--all)" % (len(in_use) - limit))
    # A global whose address is cast to another pointer type is probably the start of something bigger - a list
    # head used as if it were an object, say (DynamicObjList). Its size then comes from what the code does with it,
    # not from its define, and owning it alone would break whatever lies beyond.
    cast_names = {}
    for name, path, line, text in read_source.casts:
        cast_names.setdefault(name, []).append("%s:%d" % (path, line))
    risky = [g for g in sized if g["name"] in cast_names and not g["live"]]
    if risky:
        print("\nAddress cast to another type - check it is not the start of something bigger before owning it:")
        for g in risky:
            print("  %-28s %s%s" % (g["name"], ", ".join(cast_names[g["name"]][:3]), "  [owned]" if g["owned"] else ""))
    overlapping = [g for g in sized if g["literals"] or g["inside"]]
    if overlapping:
        print("\nReached through a raw address or a second definition inside another global:")
        for g in overlapping:
            why = (["inside " + ", ".join(g["inside"])] if g["inside"] else []) + \
                  ["%s:%d" % (l[1], l[2]) for l in g["literals"]]
            print("  %-28s %s" % (g["name"], "; ".join(why)))
    # Unsized pointers into .rdata are vtables, strings and constant tables: the game never writes them, and they
    # move into the DLL only with the code that uses them, so they are counted rather than listed for tagging.
    unsized_data = [g for g in unsized if not (rdata[0] <= g["address"] < rdata[1])]
    if unsized_data:
        print("\nUnknown size (tag with // XBE_GLOBAL(address, size) on the line before):")
        for g in unsized_data:
            print("  %-28s %08x %s:%d" % (g["name"], g["address"], g["file"], g["line"]))
    if len(unsized_data) < len(unsized):
        print("\n%d more of unknown size point into .rdata (vtables, strings, constant tables): not listed" %
              (len(unsized) - len(unsized_data)))


if __name__ == "__main__":
    main()
