# Credits: Nightfire Research Team - (2024 - 2025)

import datetime
import json
import os
import re

# Sub-tasks defined in other files for readability
from uihandler import generate_handler_switch

generate_handler_switch()

def generate_auto_inject(side, ghidra_funcs):
    injections = []

    autoinjects = gather_functions_with_tag("AUTOINJECT", side=side)

    # Look up addresses
    for f in autoinjects:
        matching_func = [x for x in ghidra_funcs if x['name'] == f[1]]
        assert len(matching_func) >= 1,f"Function {f[1]} not found, qty is {len(matching_func)}"
        
        # Thunked functions can appear multiple times, so we need to inject them in all places
        for mf in matching_func:
            addr = mf['address']
            injections.append((addr, f[1],))

    # FUNC_AT(x) with a given address
    injections.extend(gather_functions_with_tag("FUNC_AT", True, side))

    # Save the injections to a file
    output_file = f"src/{side}/autogenerated_injections.inc"
    with open(output_file, 'w') as file:
        file.write(generate_injections(injections))
    print(f"Autogenerated injections saved to {output_file}")

    return injections

def generate_auto_funcs(side, ghidra_funcs):
    # For all functions in the source code which are:
    # - Tagged with an "AUTOGEN" comment
    # Create a wrapper function that calls the original function via function pointer
    # Note - we could do this for all functions that haven't been injected, but it's more explicit to only do it for functions that are tagged
    auto_funcs = gather_functions_with_tag("AUTOGEN", side=side)
    helpers = f"#include \"{side}helpers.h\""
    output_file = f"// This file is autogenerated. Do not modify.\n{helpers}\n\n"
    for f in auto_funcs:

        matching_func = [x for x in ghidra_funcs if x['name'] == f[1]]
        assert len(matching_func) == 1, f"Function {f[1]} duplicated or not found (qty is {len(matching_func)})"
        gf = matching_func[0]


        param_types = ", ".join(gf['param_types']) if gf['param_types'] else "void"
        addr = gf['address']
        arg_list = []
        arg_names = []
        for i, type in enumerate(gf['param_types']):
            arg_list.append(f"{type} arg{i}")
            arg_names.append(f"arg{i}")

        al = ", ".join(arg_list)
        an = ", ".join(arg_names)
        cc = "" if gf['calling_convention'] == "default" else gf['calling_convention']

        if "_Handler" in gf['name']:
            cc = "__cdecl" # HACKHACKHACK not sure if these are all cdecl or stdcall

        output_file += f"""
    {gf['return_type']} {cc} {gf['name']}({al}) {{
        return reinterpret_cast<{gf['return_type']} (*)({param_types})>({addr})({an});
    }}
    """
    with open(f"src/{side}/autogenerated_functions.inc", 'w') as file:
        file.write(output_file)

    return auto_funcs

def generate(side):
    ghidra_funcs = json.load(open(f"tools/functions_{side}.json", 'r'))

    # For all functions in the C/C++ codebase which are either:
    # - Tagged with a "FUNC_AT" comment and an address
    # - Tagged with an "AUTOINJECT" comment
    # Generate an injection entry

    injections = generate_auto_inject(side, ghidra_funcs)
    uninjectable = gather_functions_with_tag("UNINJECTABLE", side=side)

    # Print statistics
    num_injecions = len(injections)
    num_uninjectable = len(uninjectable)
    total_funcs = len(ghidra_funcs)
    ratio_complete = (num_injecions + num_uninjectable) / total_funcs

    print(f"Found {num_injecions} injections, {num_uninjectable} uninjectable but implemented, of {total_funcs} known functions ({ratio_complete*100:.2f}%)")

    auto_funcs = generate_auto_funcs(side, ghidra_funcs)
    auto_func_count = len(auto_funcs)
    ratio_auto = auto_func_count / total_funcs

    print(f"Found {auto_func_count} auto gen'd for {total_funcs} known functions ({ratio_auto*100:.2f}%)")

def gather_functions_with_tag(tag_name=None, has_params=False, side="action"):
    functions = []
    exclude = { "driving" if side == "action" else "action" }
    for root, dirs, files in os.walk("src"):
        # We only ever want to get the data for one of the two sides
        [dirs.remove(d) for d in list(dirs) if d in exclude]
        for file in files:
            if not file.endswith(('.c', '.cpp')):
                continue

            file_path = os.path.join(root, file)
            with open(file_path, 'r') as file:
                lines = file.readlines()
                for i in range(len(lines)):
                    line = lines[i]
                    if has_params:
                        match = re.search(rf'// {tag_name}\((\w+)\)', line)
                    else:
                        match = re.search(rf'// {tag_name}', line)
                    if match:
                        address = match.group(1) if has_params else None
                        next_line = lines[i+1].strip()

                        # We expect a function declaration, eg "void func_name(int a, int b) {"
                        # We want to extract the function name, eg "func_name" - ie the token preceding the first "(" character

                        function_name = re.search(r'(\w+)\s*\(', next_line).group(1)
                        functions.append((address, function_name))
    return functions

def generate_injections(function_names):
    header = "// This file is autogenerated. Do not modify.\n"
    header += f"// Generated on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    injections = []
    for address, function_name in function_names:
        if not address.startswith("0x"):
            address = f"0x{address}"
        injection = f"WriteJmpTo({address}, (size_t)&{function_name});" if address else f"CreateWrapperFunction(&{function_name});"
        injections.append(injection)
    return header + "\n".join(injections)

generate("action")
generate("driving")

# For all types in the Ghidra database where:
# - There are fields
# Create a packed struct definition

# TODO: This


# For all enums in the Ghidra database
# Create an enum definition

# TODO: This
