import os
import re
import datetime
def find_injected_functions(file_path):
    functions = []
    with open(file_path, 'r') as file:
        lines = file.readlines()
        for i in range(len(lines)):
            line = lines[i]
            match = re.search(r'// FUNC_AT\((\w+)\)', line)
            if match:
                address = match.group(1)
                next_line = lines[i+1].strip()

                # We expect a function declaration, eg "void func_name(int a, int b) {"
                # We want to extract the function name, eg "func_name" - ie the token preceding the first "(" character

                function_name = re.search(r'(\w+)\s*\(', next_line).group(1)
                functions.append((address, function_name))
    return functions

def collect_injected_functions(directory):
    functions = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith(('.c', '.cpp')):
                file_path = os.path.join(root, file)
                functions.extend(find_injected_functions(file_path))
    return functions

def generate_injections(function_names):
    header = "// This file is autogenerated. Do not modify.\n"
    header += f"// Generated on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    injections = []
    for address, function_name in function_names:
        injection = f"WriteJmpRet(0x{address}, (size_t)&{function_name});"
        injections.append(injection)
    return header + "\n".join(injections)


# For all functions in the C/C++ codebase which are:
# - Tagged with a "FUNC_AT" comment
# Generate an injection entry
injections = generate_injections(collect_injected_functions("src"))
output_file = "src/action/autogenerated_injections.inc"
with open(output_file, 'w') as file:
    file.write(injections)
print(f"Autogenerated injections saved to {output_file}")


# For all functions in the Ghidra database where:
# - The function is not already reimplemented / injected
# - The function uses a standard calling convention (TODO: Implement naked ASM wrappers for non-standard calling conventions)
# Create a wrapper function

# TODO: This


# For all types in the Ghidra database where:
# - There are fields
# Create a struct definition

# TODO: This
