# Credits: Nightfire Research Team - (2024 - 2025)

# From Handler_HandleMessage
ui_hashcodes = {
    0x40000009: "P_START",
    # TODO: Non-contiguous block of crap
    0x4000000c: "P_NIS",
    0x40000012: "P_MPOPTIONS",
    0x40000013: "P_MPMAP",
    0x40000014: "P_MPRULES",
    0x40000017: "P_MPPLAYERMODS",
    0x40000019: "P_MPJOIN",
    0x4000001a: "P_MPSCENARIO",
    0x4000001b: "P_CNSELECT",
    0x4000001c: "P_NFMAP",
    0x4000001d: "P_CNMENU",
    0x40000020: "P_CNNAME",
    0x40000022: "P_CNCONTROLS",
    0x40000023: "P_NFDFCTY",
    0x40000025: "P_NFSELECT",
    0x40000027: "P_MPBOTS",
    0x40000028: "P_MPENVIROMODS",
    0x4000002b: "P_DOSSIER",
    0x4000002c: "P_MPBOTSETUP",
    0x4000002d: "P_CNOPTIONS",
    0x4000002e: "P_CNMPOPTIONS",
    0x40000030: "P_CREDITS",
    0x40000031: "P_CNAVOPTIONS",
    0x40000032: "P_INTRO",
    0x40000033: "P_MPDEBRIEFING",
    0x40000034: "P_LANGUAGE",
    0x40000035: "P_ATTRACT",
    0x40000036: "P_NFRESULTS",
    0x40000037: "P_NFSTATS",
    0x40000038: "P_NFBONUS",
    0x4000003a: "P_DSRECORDS",
    0x4000003b: "P_DSREWARDS",
    0x4000003c: "P_DSGADGETS",
    0x4000003d: "P_DSWEAPONS",
    0x4000003f: "P_MPBOTCHOOSE",
    0x40000042: "P_ENDMISSION",
    0x40000043: "P_ESTHERO",
    0x40000044: "P_TWEAKS",
    0x40000046: "P_TWEAKS2",
    # TODO: Non-contiguous block of crap
    0x40000049: "P_MPCONFIRM",
    0x4000004a: "P_PARISENUM",
    0x4000004b: "P_PAUSE",
    0x4000004c: "P_CHEATMEDAL",
    0x4000004e: "P_TRAILER",
    0x4000004f: "P_FMVTEST",
    0x40000050: "P_FMVPLAYER",
    0x40000051: "P_MPSETUP",
    0x40000053: "P_WINGAME",
    0x40000002: "P_MAIN",
    # Switch to controls rather than pages?
    0x10000002: "C_GONIGHTFIRE",
    0x10000003: "C_GOMULTIPLAYER",
    0x10000004: "C_GOCODENAMES",
    # TODO: Non-contiguous block of crap
    0x10000006: "C_SBMPMAP",
    0x1000000e: "C_SBNFMAP",
    0x10000010: "C_LBPMMAP",
    0x10000012: "C_CHCHWS",
    0x10000015: "C_CHCHDRONES",
    0x10000016: "C_CHCHBLIND",
    0x10000017: "C_CHCHDEBUG",
    0x10000018: "C_CHCHZEROG",
    0x10000019: "C_CHCHFLY",
    0x1000001a: "C_CHCHCOORDS",
    0x1000001b: "C_CHCHMUSIC",
    0x1000001c: "C_CHCHHUD",
    0x10000025: "C_RBCONTROL",
    0x10000028: "C_GCPAUSE",
    0x1000003e: "C_NIS",
    0x10000074: "C_KEYBOARD",
    0x1000009c: "C_SBMPSCEN",
    0x100000ba: "C_KEYPAD",
    0x100000bd: "C_CHCHDUMMY",
    0x100000bf: "C_SBNFDFCTY",
    0x100000c7: "C_CHCHALLOWFREEZE",
    0x100000e5: "C_SBNFCN",
    # TODO: Default case - CHCHWEAP?
    0x10000173: "C_SBDSWPSCROLL", # Dossier Weapon Scroll?
    0x10000174: "C_RBDSRECORDS",
    # TODO: Non-contiguous block of crap
    0x1000017a: "C_RBDSREWARDS",
    0x10000193: "C_SBMPBTCHOOSE",
    0x1000019f: "C_RBMPSTART",
    0x100001a1: "C_RBMPSETUP",
    # TODO: Jump
    0x100001f7: "C_CHCHBRIGHT",
    0x10000216: "C_CHCHUNLOCK",
    0x1000021d: "C_CHCHCONTROLS",
    0x1000022a: "C_RBMPFINISH",
    0x1000022b: "C_RBMPCNAME",
    0x100000e8: "C_CHCHHEALTH",
    # TODO: Non-contiguous block of crap
    0x100000eb: "C_SBCNSELECT",
    0x100000f4: "C_SBMPOPTIONS",
    0x100000fc: "C_LBERROPTIONS",
    0x10000100: "C_SBCNOPTIONS",
    0x10000101: "C_CHCHDRAWALL",
    0x1000010c: "C_SBDOSSIER",
    0x10000114: "C_SBBOTS",
    0x10000120: "C_LBMSGOPTIONS",
    0x1000015d: "C_MPDBG",
    0x1000015e: "C_LANGUAGE",
    0x10000169: "C_CHCHLOCKUP",
    # Default case - SBDSGTSCROLL. Confirmed against PS2.
    0x1000016f: "C_SBDSGTSCROLL", # Submenu Dossier Gadgets Scroll?
}

implemented = ["C_SBDOSSIER", "P_DOSSIER", "P_MPMAP", "C_SBMPMAP", "P_MPSCENARIO", "P_MPPLAYERMODS", "P_MPENVIROMODS", "P_DSGADGETS", "C_SBDSGTSCROLL", "C_SBDSWPSCROLL", "P_DSWEAPONS", "P_DSREWARDS", "P_DSRECORDS"]

def generate_handler_switch():
    output = """// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY.
// See tools/uihandler.py for more information.

#include "../actionhelpers.h"
#include "ui.h"

#include <stdio.h>

"""

    for _, name in ui_hashcodes.items():
        if not name in implemented:
            output += f"// AUTOGEN\nbool {name}_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);\n"

    for name in implemented:
        if not name in ui_hashcodes.values():
            raise Exception(f"Implemented handler {name} not in hashcode list, did you remove the _Handler suffix?")


    output += """
// AUTOINJECT
bool Handler_HandleMessage(uchar param_1, M_CONTROL *param_2, uint param_3, int param_4, int param_5)
{
    uint hashcode = param_2->hashcode;
    switch(hashcode) {
"""

    for addr, name in ui_hashcodes.items():
        output += f"        case {name}: return {name}_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);\n"

    output += """
        default: {printf("UNHANDLED MESSAGE HANDLER FOR TYPE: 0x%08x, args: 0x%08x,  0x%08x,  0x%08x,  0x%08x,  0x%08x\\n", hashcode, param_1, param_2, param_3, param_4, param_5);}
    }
    return (hashcode & 0xffffff00);
}
"""

    # Must be a CPP file because of the autogen/autoinject comments
    # newline pinned so this generated file is byte-identical whichever platform runs the build;
    # in text mode Python would write CRLF on Windows and LF everywhere else, and ui.cpp is
    # tracked, so the tree would come up dirty after every cross build.
    with open("src/action/ui/ui.cpp", 'w', newline='\r\n') as file:
        file.write(output)
