#include "inject.h"

#include "action/math/math.h"
#include "action/game.h"
#include "action/input.h"
#include "action/util/crc.h"
#include "action/memory.h"
#include "action/sound/music.h"
#include "action/ui/ui.h"
#include "action/engine/psiFile.h"
#include "action/game/view.h"
#include "action/game/obj/car.h"
#include "action/game/mp/multiplayer.h"

#include "common/launchInfo.h"

#include "cxbx/cxbxbinding.h"

void WriteMemory(size_t offset, void *data, size_t size)
{
  memcpy((void *) offset, data, size);
}

void WriteByte(size_t offset, unsigned char byte)
{
  WriteMemory(offset, &byte, 1);
}

void FillBytes(size_t offset, unsigned char byte, size_t count)
{
  memset((void*)offset, byte, count);
}

void WriteJmpTo(size_t from, size_t to)
{
  size_t relative = to - (from + 5);

  WriteByte(from, 0xE9);
  WriteMemory(from + 1, &relative, sizeof(relative));
}

void Inject()
{

  // Experiments with increasing resolution beyond original limits
  
  // 640x480: Default
  // 800x600: Stable, UI elements misaligned
  // 1024x768: Various graphics are broken entirely, videos fail to play, will crash if cameras are scaled
  // 1280x720: crashes at Mem_Init
  // 1920x1080: crashes at Mem_Init
  int width = SCREEN_WIDTH;
  int height = SCREEN_HEIGHT;
  float fWidth = (float)width;
  float fHeight = (float)height;

  // This is in the params to D3DCreateDevice
  WriteMemory(0x000e6efc, &width, 4);
  WriteMemory(0x000e6f04, &height, 4);

  // This is D3DDevice_SetViewport(&local_98), and a global, slightly later on
  WriteMemory(0x000e6ceb, &width, 4);
  WriteMemory(0x000e6cd7, &height, 4);

  // This is psiPostDraw
  WriteMemory(0x000dd8e6, &width, 4);
  WriteMemory(0x000dd8e1, &height, 4);

  // psiFadeView - full screen sprite for fade-out
  WriteMemory(0x000de594, &fWidth, 4);
  WriteMemory(0x000de59c, &fHeight, 4);

  // Camera_CreateCameras has multiple, covering camera dimensions and positioning of MP windows
  WriteMemory(0x0025d23, &width, 4); // Camera 0 create
  WriteMemory(0x0025d1c, &height, 4);
  WriteMemory(0x0025d45, &width, 4); // Camera 5 create
  WriteMemory(0x0025d40, &height, 4);
  WriteMemory(0x0025d62, &width, 4); // Camera 7 create
  WriteMemory(0x0025d5d, &height, 4);
  WriteMemory(0x0025d82, &width, 4); // Camera 4 create
  WriteMemory(0x0025d7d, &height, 4);
  WriteMemory(0x0025d97, &width, 4); // Camera 6 create
  WriteMemory(0x0025d92, &height, 4);
  WriteMemory(0x0025daf, &width, 4); // Camera 8 create
  WriteMemory(0x0025daa, &height, 4);
  WriteMemory(0x0025dc4, &width, 4); // Camera 10 create
  WriteMemory(0x0025dbf, &height, 4);
  WriteMemory(0x0025e11, &width, 4); // Camera 9 create
  WriteMemory(0x0025e0c, &height, 4);
  WriteMemory(0x0025e51, &width, 4); // Player first-person camera, and multiplayer cameras
  WriteMemory(0x0025e4c, &height, 4);
  WriteMemory(0x0025e87, &fWidth, 4); // Camera to screen pixel bounds (single player only)
  WriteMemory(0x0025e82, &fHeight, 4);
  // TODO: Multiplayer scaling
  // TODO: Label_Init
  // TODO: Page_Init
  // TODO: HUD_CreateRadar


  //  FUN_0008fdd0 - Sprite related?
  WriteMemory(0x008fdd8, &width, 4);
  WriteMemory(0x008fde5, &height, 4);

  // Around 00093ef1 in FUN_00093960 - menu-related?
  WriteMemory(0x00093ef2, &width, 4);
  WriteMemory(0x00093efe, &height, 4);

  // Around 000e7212 in FUN_000e7130 - call to XGSetTextureHeader - buffer for full-screen blur effect?
  WriteMemory(0x000e7218, &width, 4);
  WriteMemory(0x000e7213, &height, 4);
  WriteMemory(0x000e7306, &fWidth, 4);
  WriteMemory(0x000e7301, &fHeight, 4);
  WriteMemory(0x000e7312, &fWidth, 4);
  WriteMemory(0x000e730d, &fHeight, 4);

  // Around FUN_000e8a90 - FMV related?
  // Early bit - set up?
  // WriteMemory(0x000e8adc, &width, 4);
  // WriteMemory(0x000e8ad7, &height, 4);
  // Later bit - compare to something else?
  // TODO: This


  /*
   * Function Patching
   */
#include "action/autogenerated_injections.inc"


  // Patched to enable Action and Driving to pass messages
  // These are common to both, so we can't use autogeneration
  WriteJmpTo(0x000eb0fb, (size_t)&XLaunchNewImageA);
  WriteJmpTo(0x000eb050, (size_t)&XGetLaunchInfo);


  // Special case for weapon stats
  // This has the limitation that the DLL must be injected before the constructor is called otherwise it will have no effect
  void *ptrCtorWeaponDefinitionTable = &ctor_WeaponDefinitionTable;
  WriteMemory(0x0016313c, &ptrCtorWeaponDefinitionTable, 4);

}