#ifndef COMMON_XBECLASS_H_
#define COMMON_XBECLASS_H_

#include <stddef.h>

// ---------------------------------------------------------------------------------------------------------------
// Overlay classes: C++ classes that stand in for one of the game's, so that a replacement can be a member
// function and `this->field` lands where the game keeps it. See docs/driving-injection-framework.md, section 4.
//
// The rules, each of which is a way this silently goes wrong otherwise:
//
//   - The exact layout, field by field, checked with XBE_CLASS_SIZE and XBE_FIELD below against what the game
//     uses (Ghidra's structure, or the offsets in the disassembly).
//   - No `virtual` keyword. A class with a vtable declares `void **vtable;` as its first member; the compiler
//     must never add a vtable pointer of its own. A virtual method is replaced by patching the function the
//     vtable points at, like any other.
//   - Never constructed by our code. Instances are the game's, and `this` is reinterpreted; objects are made by
//     calling the game's own constructors.
//   - Everything public. Single, public, non-virtual inheritance only, and only where Ghidra's structure says
//     so: its first field is super_<Base>, of the base's type (Ghidra's own convention for a base class). The
//     generated layout then holds only the derived class's own fields, from the end of the base, and the build
//     refuses a class whose declared base disagrees with Ghidra's in either direction. The base's vtable pointer
//     is the derived class's too, as in the game (RAutonomousObj : RSceneObj is the worked example).
//   - Constructors and destructors are ordinary methods (Construct, Destruct) tagged with FUNC_AT or
//     AUTOGEN(address), since the language will not give their addresses.
//
// Methods not yet reimplemented are declared in the class with `// AUTOGEN` above them, and tools/preprocess.py
// generates a body that calls the original through `this` (src/driving/autogenerated_functions.inc).
// ---------------------------------------------------------------------------------------------------------------

#define XBE_CLASS_SIZE(Class, size)                                                                          \
    static_assert(sizeof(Class) == (size), #Class " is not the size of the game's (" #size " bytes)")

#define XBE_FIELD(Class, field, offset)                                                                      \
    static_assert(offsetof(Class, field) == (offset), #Class "::" #field " is not at the game's offset (" #offset ")")

#endif // COMMON_XBECLASS_H_
