#include "../helpers.h"

// AUTOINJECT
int __cdecl Handler_HandleMessage(unsigned char param_1,void *param_2,uint param_3,int param_4,int param_5) {

uint hashcode = *(uint *)((int)param_2+0x18);
// Automatically generated from a mapping of hashcode to name
#include "autogenerated_handler.inc"

}