// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY.
// See tools/uihandler.py for more information.

#include "../actionhelpers.h"
#include "ui.h"

#include <stdio.h>

// AUTOGEN
bool P_START_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_NIS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPOPTIONS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPMAP_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPRULES_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPPLAYERMODS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPJOIN_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPSCENARIO_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_CNSELECT_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_NFMAP_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_CNMENU_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_CNNAME_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_CNCONTROLS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_NFDFCTY_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_NFSELECT_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPBOTS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPENVIROMODS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPBOTSETUP_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_CNOPTIONS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_CNMPOPTIONS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_CREDITS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_CNAVOPTIONS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_INTRO_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPDEBRIEFING_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_LANGUAGE_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_ATTRACT_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_NFRESULTS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_NFSTATS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_NFBONUS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_DSRECORDS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_DSREWARDS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_DSGADGETS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_DSWEAPONS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPBOTCHOOSE_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_ENDMISSION_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_ESTHERO_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_TWEAKS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_TWEAKS2_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPCONFIRM_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_PARISENUM_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_PAUSE_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_CHEATMEDAL_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_TRAILER_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_FMVTEST_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_FMVPLAYER_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MPSETUP_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_WINGAME_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool P_MAIN_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_GONIGHTFIRE_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_GOMULTIPLAYER_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_GOCODENAMES_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBMPMAP_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBNFMAP_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_LBPMMAP_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHWS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHDRONES_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHBLIND_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHDEBUG_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHZEROG_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHFLY_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHCOORDS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHMUSIC_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHHUD_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_RBCONTROL_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_GCPAUSE_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_NIS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_KEYBOARD_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBMPSCEN_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_KEYPAD_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHDUMMY_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBNFDFCTY_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHALLOWFREEZE_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBNFCN_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBDSWPSCROLL_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_RBDSRECORDS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_RBDSREWARDS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBMPBTCHOOSE_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_RBMPSTART_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_RBMPSETUP_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHBRIGHT_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHUNLOCK_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHCONTROLS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_RBMPFINISH_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_RBMPCNAME_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHHEALTH_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBCNSELECT_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBMPOPTIONS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_LBERROPTIONS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBCNOPTIONS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHDRAWALL_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBBOTS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_LBMSGOPTIONS_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_MPDBG_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_LANGUAGE_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_CHCHLOCKUP_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);
// AUTOGEN
bool C_SBDSGTSCROLL_Handler(uchar param_1, M_CONTROL *param_2, uint hashcode, uint param_3, int param_4, int param_5);

// AUTOINJECT
bool Handler_HandleMessage(uchar param_1, M_CONTROL *param_2, uint param_3, int param_4, int param_5)
{
    uint hashcode = param_2->hashcode;
    switch(hashcode) {
        case 0x40000009: return P_START_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000000c: return P_NIS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000012: return P_MPOPTIONS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000013: return P_MPMAP_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000014: return P_MPRULES_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000017: return P_MPPLAYERMODS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000019: return P_MPJOIN_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000001a: return P_MPSCENARIO_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000001b: return P_CNSELECT_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000001c: return P_NFMAP_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000001d: return P_CNMENU_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000020: return P_CNNAME_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000022: return P_CNCONTROLS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000023: return P_NFDFCTY_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000025: return P_NFSELECT_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000027: return P_MPBOTS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000028: return P_MPENVIROMODS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000002b: return P_DOSSIER_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000002c: return P_MPBOTSETUP_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000002d: return P_CNOPTIONS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000002e: return P_CNMPOPTIONS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000030: return P_CREDITS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000031: return P_CNAVOPTIONS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000032: return P_INTRO_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000033: return P_MPDEBRIEFING_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000034: return P_LANGUAGE_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000035: return P_ATTRACT_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000036: return P_NFRESULTS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000037: return P_NFSTATS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000038: return P_NFBONUS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000003a: return P_DSRECORDS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000003b: return P_DSREWARDS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000003c: return P_DSGADGETS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000003d: return P_DSWEAPONS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000003f: return P_MPBOTCHOOSE_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000042: return P_ENDMISSION_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000043: return P_ESTHERO_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000044: return P_TWEAKS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000046: return P_TWEAKS2_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000049: return P_MPCONFIRM_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000004a: return P_PARISENUM_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000004b: return P_PAUSE_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000004c: return P_CHEATMEDAL_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000004e: return P_TRAILER_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x4000004f: return P_FMVTEST_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000050: return P_FMVPLAYER_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000051: return P_MPSETUP_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000053: return P_WINGAME_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x40000002: return P_MAIN_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000002: return C_GONIGHTFIRE_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000003: return C_GOMULTIPLAYER_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000004: return C_GOCODENAMES_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000006: return C_SBMPMAP_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000000e: return C_SBNFMAP_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000010: return C_LBPMMAP_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000012: return C_CHCHWS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000015: return C_CHCHDRONES_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000016: return C_CHCHBLIND_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000017: return C_CHCHDEBUG_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000018: return C_CHCHZEROG_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000019: return C_CHCHFLY_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000001a: return C_CHCHCOORDS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000001b: return C_CHCHMUSIC_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000001c: return C_CHCHHUD_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000025: return C_RBCONTROL_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000028: return C_GCPAUSE_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000003e: return C_NIS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000074: return C_KEYBOARD_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000009c: return C_SBMPSCEN_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100000ba: return C_KEYPAD_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100000bd: return C_CHCHDUMMY_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100000bf: return C_SBNFDFCTY_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100000c7: return C_CHCHALLOWFREEZE_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100000e5: return C_SBNFCN_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000173: return C_SBDSWPSCROLL_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000174: return C_RBDSRECORDS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000017a: return C_RBDSREWARDS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000193: return C_SBMPBTCHOOSE_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000019f: return C_RBMPSTART_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100001a1: return C_RBMPSETUP_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100001f7: return C_CHCHBRIGHT_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000216: return C_CHCHUNLOCK_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000021d: return C_CHCHCONTROLS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000022a: return C_RBMPFINISH_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000022b: return C_RBMPCNAME_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100000e8: return C_CHCHHEALTH_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100000eb: return C_SBCNSELECT_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100000f4: return C_SBMPOPTIONS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x100000fc: return C_LBERROPTIONS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000100: return C_SBCNOPTIONS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000101: return C_CHCHDRAWALL_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000010c: return C_SBDOSSIER_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000114: return C_SBBOTS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000120: return C_LBMSGOPTIONS_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000015d: return C_MPDBG_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000015e: return C_LANGUAGE_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x10000169: return C_CHCHLOCKUP_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);
        case 0x1000016f: return C_SBDSGTSCROLL_Handler(param_1, param_2, hashcode, param_3, param_4, param_5);

        default: {printf("UNHANDLED MESSAGE HANDLER FOR TYPE: 0x%08x\n",hashcode);}
    }
    return (hashcode & 0xffffff00);
}
