#pragma once

#include "../common/xbeClass.h"
#include "autogenerated_layouts.h"

// An event in the scheduler's event buffer (Ghidra: Event, 4 bytes - just the vtable; each event class adds its own
// data after it, which is why events vary in size). An overlay class - see src/common/xbeClass.h. Every event is
// allocated from the buffer by Event::operator new and processed by the event manager, which destroys it.
struct Event {
    XBE_FIELDS(Event)

    // Slot 0: MSVC's scalar deleting destructor, `this` and a flags word (bit 0: free the memory too). For an
    // event, destroying it is what runs it - its destructor does the event's work and operator delete then
    // consumes its bytes from the buffer - so the event manager calls this with 1 for every event in turn. Called
    // through the event's own vtable, so it reaches whichever of the ~185 event classes it is.
    // VIRTUAL(0)
    void *DeletingDestructor(unsigned int flags);
};

void EventManager__RunEvents(void);
