#pragma once

#include <stddef.h>
#include <stdint.h>

#include "../common/xbeClass.h"
#include "autogenerated_layouts.h"

// ---------------------------------------------------------------------------------------------------------------
// The scheduler's task lists (docs/driving-engine-plan.md, section 2). A Schedule holds its tasks in buckets - one
// for the once-per-loop and sim-rate schedules, two for the half rate, four for the quarter rate - and each bucket
// is an MSVC std::list<TaskRecord> allocated on its own. A tick runs one bucket; within it, a task runs when its
// priority ("spacing") is the priority being run, so the scheduler's eight passes per tick order the tasks.
//
// A task is a callback from RegisterEvent's table (by event number) with a word of data, an initial delay and a
// number of runs (0: forever). The game's tasks are the seven RunTheGame adds - the simulation, animation, AI and
// camera updates, the render, the audio update and the end of the frame - plus the ones mission events add.
// ---------------------------------------------------------------------------------------------------------------

// A scheduled task (Ghidra: TaskRecord, 20 bytes). AddTask fills it on the stack and copies it into the list's node.
struct TaskRecord {
    int32_t eventType;          // +0x00 which callback: an index into RegisterEvent's table
    uint32_t staticData;        // +0x04 handed to the callback
    uint8_t spacing;            // +0x08 the priority (0-7) the task runs at
    uint8_t unknown09;          // +0x09 never written: whatever was on AddTask's stack
    uint16_t delayTicks;        // +0x0a runs of its bucket to skip before the first call
    uint16_t numTimesToFire;    // +0x0c calls left; 0 runs it for ever
    uint16_t unknown0e;         // +0x0e never written
    uint32_t taskNum;           // +0x10 the schedule's serial number for it, what RemoveTask looks for
};
static_assert(sizeof(TaskRecord) == 0x14, "TaskRecord is 20 bytes");

// A node of a bucket's list (Ghidra's TaskRecord_LListEntry layout: next, previous, the record; 0x1c bytes, from
// the fixed-size pools under the name "STL").
struct TaskNode {
    TaskNode *next;             // +0x00
    TaskNode *prev;             // +0x04
    TaskRecord record;          // +0x08
};
static_assert(sizeof(TaskNode) == 0x1c, "TaskNode is 0x1c bytes");

// One bucket: an MSVC std::list<TaskRecord> - its allocator byte, the head node (a sentinel: the list is circular
// through it) and the count (12 bytes, from the pools under the name "TaskList"). Schedule's generated layout calls
// the pointers to these TaskRecord_LListEntry, Ghidra's name for them; this is that type. Each method here is one
// of the game's compiled copies of the std::list members, at its own address.
struct TaskRecord_LListEntry {
    uint8_t allocator;          // +0x00 std::allocator, empty
    uint8_t _pad01[3];
    TaskNode *head;             // +0x04
    uint32_t size;              // +0x08

    // erase(first, last) (0x0005bbe0): unlinks and frees every node from first up to last, skipping the head,
    // and answers last through MSVC's hidden result pointer.
    TaskNode **Erase(TaskNode **result, TaskNode *first, TaskNode *last);
    // _Buynode(next, prev, value) (0x0005bc30): a node holding a copy of the record, linked to nothing yet - only
    // its own pointers are set. Does not use `this`.
    TaskNode* BuyNode(TaskNode *next, TaskNode *prev, const TaskRecord *record);
    // _Buynode() (0x0005bda0): the head node, pointing at itself both ways.
    static TaskNode* BuyHead();
    // The destructor (0x0005bdc0): every node, then the head.
    void Destruct();
    // _Incsize(count) (0x0005bfe0): the count grows by `count`; past 0x0ccccccc it throws length_error.
    void IncSize(uint32_t count);
};
typedef TaskRecord_LListEntry TaskList;
static_assert(sizeof(TaskList) == 0xc, "a task list is 12 bytes");

// What a task runs: the callback RegisterEvent::LookupEvent gives for its event number, called with the task's data.
typedef void (*TaskCallback)(uint32_t staticData);

// A schedule's vtable, the game's: slot 0 the scalar deleting destructor, slot 1 Process.
struct vtable_Schedule {
    void *deletingDestructor;
    void *process;
};

// One of the scheduler's task lists (Ghidra: Schedule, 44 bytes). An overlay class - see src/common/xbeClass.h.
// The fields are Ghidra's (vtable, next, listOfTasks[8] and numTasks), generated from tools/structs_driving.json;
// `next` is in fact the number of buckets in use (1, 2 or 4), which BucketCount reads, and numTasks the serial
// number the next task gets. The schedules the game makes are a Schedule with a subclass's vtable (see Scheduler).
struct Schedule {
    XBE_FIELDS(Schedule)

    // The number of buckets: Ghidra's `next` field.
    int BucketCount() const { return (int)(intptr_t)next; }

    // The constructor (0x0005be00): `buckets` empty task lists, the base vtable, task numbers from 1000.
    Schedule* Construct(int buckets);
    // The destructor (0x0005bf80), and a second copy of it that only jumps there (0x0005c130), which the
    // subclasses' deleting destructor calls.
    void Destruct();
    void DestructDerived();
    // The scalar deleting destructors: the base class's (0x0005bfc0, slot 0 of Schedule's vtable) and the
    // subclasses' (0x0005c110, slot 0 of the other four). Bit 0 of `flags` frees the memory too.
    Schedule* Delete(unsigned flags);
    Schedule* DeleteDerived(unsigned flags);

    // Slot 0, the deleting destructor of whichever class the schedule is, called through its own vtable.
    // VIRTUAL(0)
    Schedule *DeletingDestructor(unsigned flags);

    // Adds a task to the emptiest bucket (0x0005c490). `unused` is never read.
    void AddTask(int eventType, uint32_t staticData, unsigned short spacing, bool unused, int delayTicks,
                 int repeats);
    // Removes the task with this serial number, wherever it is (0x0005bc70). True if there was one.
    bool RemoveTask(uint32_t taskNum);
    // Empties every bucket, giving each a new list (0x0005bec0).
    void RemoveAllTasks();
    // Runs the tasks in one bucket whose spacing matches `priority` (0x0005bce0).
    void RunTasks(int bucket, unsigned short priority);

    // Slot 1: runs this schedule's tasks for a tick. The subclass decides which bucket a tick runs: always the
    // first for the once-per-loop and sim-rate schedules (0x0005bd70, one function serving both), tick & 1 for
    // the half rate (0x0005bd80), tick & 3 for the quarter rate (0x0005bd90). The base Schedule's slot is pure
    // virtual. Scheduler::Run calls it through the schedule's own vtable, which reaches the ports below.
    // VIRTUAL(1)
    void Process(int tick, unsigned short priority);

    void ProcessFirstBucket(int tick, unsigned short priority);
    void ProcessHalfRate(int tick, unsigned short priority);
    void ProcessQuarterRate(int tick, unsigned short priority);
};
