#pragma once

#include "../common/xbeClass.h"
#include "autogenerated_layouts.h"
#include "Schedule.hpp"

// The game's scheduler (Ghidra: Scheduler, 36 bytes), an overlay class - see src/common/xbeClass.h. Its fields
// are Ghidra's, generated from tools/structs_driving.json and checked: the four schedules, listOfSchedules,
// lastTickCount, maybeElapsedTime, the cinematicModeSkipping byte at +0x1d, and timeScale.
class Scheduler {

public:
    XBE_FIELDS(Scheduler)

    void Run(int i);
};
