#pragma once

#include "../common/xbeClass.h"
#include "autogenerated_layouts.h"

// One of the scheduler's task lists (Ghidra: Schedule, 44 bytes). An overlay class - see src/common/xbeClass.h:
// the game's own instances, reinterpreted, with its methods either reimplemented or, as here, declared
// AUTOGEN so that calling one reaches the original. The fields are Ghidra's (vtable, next, listOfTasks[8] -
// one task list per priority bucket - and numTasks), generated from tools/structs_driving.json and checked.
struct Schedule {
    XBE_FIELDS(Schedule)

    // Runs the tasks in one bucket whose spacing matches `priority` (0x0005bce0).
    // AUTOGEN
    void RunTasks(int bucket, unsigned short priority);
};
