#pragma once

#include <stdint.h>

#include "../common/xbeClass.h"
#include "autogenerated_layouts.h"
#include "Schedule.hpp"

// The scheduler's list of its simulation schedules (Ghidra: Vector_Schedule, 16 bytes): an MSVC
// std::vector<Schedule *> - allocator byte, first, last, end of storage. Its two methods are the game's compiled
// copies of push_back and _Insert_n.
struct Vector_Schedule {
    uint8_t allocator;          // +0x00 std::allocator, empty
    uint8_t _pad01[3];
    Schedule **first;           // +0x04
    Schedule **last;            // +0x08
    Schedule **end;             // +0x0c

    unsigned Size() const { return first != NULL ? unsigned(last - first) : 0; }
    unsigned Capacity() const { return first != NULL ? unsigned(end - first) : 0; }

    // push_back (0x0005c540).
    void Insert(Schedule *const *schedule);
    // _Insert_n(where, count, value) (0x0005c1a0): `count` copies of the value before `where`, growing the
    // storage by half again (or to fit) when it is full.
    void InsertN(Schedule **where, unsigned count, Schedule *const *value);
    // _Xlen (0x0005c090): throws length_error("vector<T> too long").
    static void Xlen();
};
static_assert(sizeof(Vector_Schedule) == 0x10, "Vector_Schedule is 16 bytes");

// The game's scheduler (Ghidra: Scheduler, 36 bytes), an overlay class - see src/common/xbeClass.h. Its fields
// are Ghidra's, generated from tools/structs_driving.json and checked: the four schedules, listOfSchedules,
// lastTickCount, maybeElapsedTime, the cinematicModeSkipping byte at +0x1d, and timeScale. There is one, made by
// GameLoop_StartUp through Init and destroyed by GameLoop_CleanUp through Shutdown.
class Scheduler {

public:
    XBE_FIELDS(Scheduler)

    // The constructor (0x0005c5b0): the four schedules, the three simulation ones also in listOfSchedules.
    Scheduler* Construct();
    // The destructor (0x0005c140): every schedule through its deleting destructor, then the list.
    void Destruct();

    // Makes the scheduler, once (0x0005c740).
    static void Init();
    // Destroys it (0x0005c460).
    static void Shutdown();
    // Normal speed, no skipping, and the clock taken as now (0x0005ba40, from ERestart's destructor).
    static void Reset();
    // The clock taken as now (0x0005ba70).
    void ResetTime();

    void Run(int i);
};

// The event number to callback tables a task or a mission event is looked up in (Ghidra: RegisterEvent).
class RegisterEvent {
public:
    // The callback that runs event number `event` (0x0005a5e0).
    static TaskCallback LookupEvent(int event);
    // The resolver CARP data uses for event number `event` (0x0005a5f0).
    static void* ResolveEvent(int event);
};

// The game's clock (docs/driving-engine-plan.md, section 2): a timer task counting the ticks at the video refresh
// rate, which Scheduler::Run turns into simulation ticks.
void RealClock_InterruptHandler();   // 0x0005b9f0, run by the timer
void RealClock_Init();               // 0x0005ba10
void RealClock_CleanUp();            // 0x0005ba30
