name: CI

on: push

jobs:
  build:
    #name:
    runs-on: windows-2022

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      #- name: Install vc141_xp
      #  run: |
      #    Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList 'modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --quiet --add Microsoft.VisualStudio.Component.WinXP' -Wait -PassThru

      - name: Create Build Folder
        run: |
          cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake $GITHUB_WORKSPACE -G "Visual Studio 17 2022" -A Win32
          # cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -T v141_xp -A Win32

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: |
          cmake --build . --config Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ runner.workspace }}/build/Release

      - name: Upload Decomp Reports
        uses: actions/upload-artifact@v4
        with:
          name: decomp-reports
          path: |
            ${{ github.workspace }}/report_action.json
            ${{ github.workspace }}/report_driving.json
