#ifndef DRIVING_WORLD_COLLISIONTYPES_H_
#define DRIVING_WORLD_COLLISIONTYPES_H_

// ---------------------------------------------------------------------------------------------------------------
// The collision system's data, shared by its parts: the track's collision records as the CARP file lays them out
// (the collision instances and objects, their articles' triangle strips, barriers and windows, the grid's cells),
// what a query answers (WorldCollisionInfo), and the vectors the queries fill (std::vectors, CoreContainers.h's
// GameVector layout). The classes' methods are ported beside the code that owns them: WCollisionMgr's queries in
// CollisionQueries.cpp, its lists and lifecycle in CollisionManager.cpp, the instances, objects and window records
// in CollisionInstance.cpp, the grid in Grid.cpp, the colliders' vectors in Collider.cpp.
//
// Vectors are data/CoordConvert.h's Coord3 and Coord4; matrices the engine's MATRIX4 (row vectors, the translation
// in row 3). A segment is two Coord4s, start then end.
// ---------------------------------------------------------------------------------------------------------------

#include <stddef.h>
#include <stdint.h>

#include "../autogenerated_layouts.h"   // MATRIX4
#include "../data/CoordConvert.h"       // Coord3, Coord4
#include "../engine/CoreContainers.h"   // GameVector

class UGroup;
struct WMapHeader;                      // Tree.h

// A matrix's row as a vector (row 3: the translation)
inline Coord4 *MatrixRow(MATRIX4 *matrix, int row) {
    return reinterpret_cast<Coord4 *>(matrix->mtx[row]);
}
inline const Coord4 *MatrixRow(const MATRIX4 *matrix, int row) {
    return reinterpret_cast<const Coord4 *>(matrix->mtx[row]);
}

// ---- the faces: what the fourth word of a triangle's last corner says about it

// A face's tag (the strips' triangles, the barriers; WWorldPos and WorldCollisionInfo carry it on): its type,
// flags, and an id. GetInstanceStripList reads a strip triangle's id as the radius, in sixteenths, of the sphere
// round the triangle.
struct FaceTag {
    uint8_t type;               // +0x00 SurfaceBumpHeight's surface: 2-10 bumpy
    uint8_t subType;            // +0x01 FaceSubType bits; faces and barriers sharing a bit with
                                //       WCollisionMgr::barrierMask are skipped
    uint16_t id;                // +0x02
};
static_assert(sizeof(FaceTag) == 4, "a face tag is a word");

enum FaceSubType : uint8_t {
    kFaceIgnored = 0x04,        // never found by the searches under a point
};

enum StripFlags : uint32_t {
    kStripStartsClockwise = 0x1,    // the strip's first triangle is wound clockwise (in x/z), the next the other way
    kStripEitherWinding = 0x2,      // a triangle may be wound either way
};

// ---- the collision articles: an instance's geometry ("ca" data)

// A vertex of a collision triangle strip. The fourth word is genuinely three things: the strip's vertex count in the
// first vertex, its flags in the second, and in every later one the tag of the triangle that vertex completes.
struct StripVertex {
    float x, y, z;              // +0x00
    union {
        int32_t count;          // +0x0c the first vertex: the number of vertices
        uint32_t flags;         // +0x0c the second: StripFlags
        FaceTag tag;            // +0x0c the others: the triangle (this vertex and the two before it)
    };

    Coord3 &Position() { return *reinterpret_cast<Coord3 *>(this); }
    const Coord3 &Position() const { return *reinterpret_cast<const Coord3 *>(this); }
};
static_assert(sizeof(StripVertex) == 0x10, "a strip vertex is 16 bytes");

// Three strip vertices: a triangle of a strip where it lies, or one carried into the world's frame (WWorldPos's
// face: corner[1].flags its strip's flags, corner[2].tag its tag).
struct StripTriangle {
    StripVertex corner[3];

    float LowestY() const;      // the lowest of its three heights                              0x000bf480
};
static_assert(sizeof(StripTriangle) == 0x30, "a strip triangle is 48 bytes");

// A strip's bounding sphere, and where the strip is.
struct CollisionStrip {
    Coord3 centre;              // +0x00 in the instance's frame
    uint16_t radius;            // +0x0c in sixteenths
    uint16_t vertexOffset;      // +0x0e the strip's vertices, from the article's +0x20
};
static_assert(sizeof(CollisionStrip) == 0x10, "a strip's sphere is 16 bytes");

// A barrier: a vertical wall from (x0, z0) to (x1, z1), from height y0 up to y1. As a segment (two Coord4s), the
// fourth words are its tag and its inverse length.
struct CollisionBarrier {
    float x0, y0, z0;           // +0x00
    FaceTag tag;                // +0x0c
    float x1, y1, z1;           // +0x10
    float inverseLength;        // +0x1c of the wall in x/z: scales (dz, -dx) to its unit normal

    const Coord4 *Segment() const { return reinterpret_cast<const Coord4 *>(this); }

    // The squared distance in the ground plane from the point to the wall, answered unrounded.     0x000be950
    double DistanceSquared2D(const Coord4 *point) const;
};
static_assert(sizeof(CollisionBarrier) == 0x20, "a barrier is 32 bytes");

// A window pane, quantised: its near edge along a horizontal direction (in 1/8192 of it) and its top (in 1/256),
// then its width along the direction and its height down from the top.
struct WindowPane {
    int16_t start;              // +0x00
    int16_t top;                // +0x02
    int16_t width;              // +0x04
    int16_t height;             // +0x06

    // The four corners round the pane from the top near one, from an origin and the direction.    0x000bea50
    void MakeCorners(const Coord4 *origin, const Coord4 *along, Coord3 *corners) const;
};
static_assert(sizeof(WindowPane) == 8, "a window pane is 8 bytes");

// A set of panes: its pane count and id, then the panes.
struct WindowSet {
    uint32_t paneCount;         // +0x00
    uint32_t id;                // +0x04
    // +0x08 WindowPane panes[paneCount]

    const WindowPane *Panes() const { return reinterpret_cast<const WindowPane *>(this + 1); }
};
static_assert(sizeof(WindowSet) == sizeof(WindowPane), "a set's head is one pane long: the sets step in panes");

// A window group ("wGroup" in the PS2 build's warning): its sets of panes, one per instance variant
// (WCollisionInstance::flags >> 2).
struct WindowGroup {
    uint32_t setCount;          // +0x00
    uint32_t size;              // +0x04 bytes to the next group
    uint32_t id;                // +0x08 WorldCollisionInfo::groupId
    // +0x0c the sets

    const WindowSet *Sets() const { return reinterpret_cast<const WindowSet *>(this + 1); }
    // The set with the id, NULL if none                                                          0x000beb40
    const WindowSet* FindSet(uint32_t id) const;
};
static_assert(sizeof(WindowGroup) == 0xc, "a window group's head is 12 bytes");

// The damage of one pane (0x2c bytes; the window map's value, and the data of the EHitWindow event raised for it):
// a kind (random 0-3, +4 high up), the hits since, and the pane's two corners in the instance's frame.
struct WindowHit {
    uint32_t kind;              // +0x00
    uint32_t hits;              // +0x04 more hits on a broken pane
    uint32_t unknown08;         // +0x08 zero
    Coord4 corner0;             // +0x0c w = 1
    Coord4 corner1;             // +0x1c w = 1

    WindowHit* Construct(uint32_t kind, uint32_t hits, const Coord3 *corner0, const Coord3 *corner1);   // 0x000beb70
};
static_assert(sizeof(WindowHit) == 0x2c, "a window hit is 44 bytes");

// A collision article: a header of counts and offsets, then the strips' spheres (+0x20), their vertices, the
// barriers (+0x20 + barrierOffset) and the window groups after them (+ windowOffset).
struct CollisionArticle {
    uint16_t stripCount;        // +0x00
    uint16_t barrierOffset;     // +0x02 from +0x20
    uint16_t barrierCount;      // +0x04
    uint16_t windowOffset;      // +0x06 from the barriers
    uint16_t windowGroupCount;  // +0x08
    uint8_t unknown0a[0x16];

    const uint8_t *Body() const { return reinterpret_cast<const uint8_t *>(this + 1); }
    const CollisionStrip *Strips() const { return reinterpret_cast<const CollisionStrip *>(Body()); }
    const CollisionBarrier *Barriers() const {
        return reinterpret_cast<const CollisionBarrier *>(Body() + barrierOffset);
    }
    const StripVertex *Vertices(const CollisionStrip *strip) const {
        return reinterpret_cast<const StripVertex *>(Body() + strip->vertexOffset);
    }
    const WindowGroup *WindowGroups() const {
        return reinterpret_cast<const WindowGroup *>(Body() + barrierOffset + windowOffset);
    }
};
static_assert(sizeof(CollisionArticle) == 0x20, "an article's header is 32 bytes");

// ---- the world's render instances (fgWorld)

// A placed render instance (fgWorld->renderInstances, 0x40 bytes): its matrix, whose rows' fourth words carry other
// data - row 1's (+0x1c) leads through two handles to the model's CARP data group, where SetCollisionArticle looks
// its articles up.
struct RWorldInstance {
    MATRIX4 matrix;

    UGroup ***Model() const { return *reinterpret_cast<UGroup ***const *>(&matrix.mtx[1][3]); }
};
static_assert(sizeof(RWorldInstance) == 0x40, "a world render instance is 64 bytes");

// The world's loaded data (WWorld's object): only the fields the collision system reads.
struct WWorldData {
    uint8_t unknown00[0x14];
    UGroup *mapGroup;           // +0x14 the 'Map ' group: the render instances' names
    uint8_t unknown18[4];
    WMapHeader *map;            // +0x1c the scene tree's header (Tree.h)
    RWorldInstance *renderInstances;    // +0x20
};
static_assert(offsetof(WWorldData, renderInstances) == 0x20, "fgWorld's render instances");

#define fgWorld (*(WWorldData **)0x0023f310)

// ---- the placed things

enum CollisionInstanceFlags : uint8_t {
    kInstanceFacesAbove = 0x01, // its faces are looked for above the point, not below
    kInstanceFlag02 = 0x02,     // WorldCollisionInfo::flag52
    kInstanceTilted = 0x03,     // either bit: rotated off the vertical, its up axis computed (the barrier list
                                //   then keeps its barriers in its own frame), and always listed
};

// A collision instance ("ci" data, 0x40 bytes): a piece of collision geometry placed in the world. Its rotation is
// kept as the right and forward axes (the up axis is their cross product, or straight up for an instance that is
// not tilted), with the half sizes of its box in their fourth words; its position is the translation of the world's
// frame in its own (MakeMatrix's row 3), the inverse of its render instance's.
class WCollisionInstance {
public:
    Coord3 right;               // +0x00
    float halfSizeX;            // +0x0c its box's half size along right
    uint32_t queryStamp;        // +0x10 the last list query that took it (WCollisionMgr::queryStamp)
    float halfHeight;           // +0x14
    uint8_t flags;              // +0x18 CollisionInstanceFlags; >> 2: the window variant
    uint8_t unknown19;
    uint16_t renderIndex;       // +0x1a its render instance (fgWorld->renderInstances), and its name
    union {                     // +0x1c
        CollisionArticle *article;  // its geometry, from WCollisionMgr::Init on (colliders and WWorldPos keep it
                                    // to see that it has not changed)
        UGroup *articleGroup;       // before: the CARP group of its article, as the loader resolved it
    };
    Coord3 forward;             // +0x20
    float halfSizeZ;            // +0x2c
    Coord3 position;            // +0x30
    float radius;               // +0x3c its bounding radius (the grid keeps it in the cells round it)

    MATRIX4* GetRenderInstance();                       // 0x000be780
    const char* GetName();                              // 0x000be7a0
    void CalcPosition(Coord3 *local);                   // 0x000be810: the world origin in its frame
    void MakeMatrix(MATRIX4 *out, bool translate);      // 0x000be8b0: the world into its frame
};
static_assert(sizeof(WCollisionInstance) == 0x40, "a collision instance is 64 bytes");
static_assert(offsetof(WCollisionInstance, article) == 0x1c && offsetof(WCollisionInstance, forward) == 0x20,
              "collision instance layout");

enum CollisionObjectFlags : uint8_t {
    kObjectFlag01 = 0x01,       // moves with its render instance; WorldCollisionInfo::flag52
};

// A collision object ("co" data, 0x30 bytes): an upright cylinder or a box, placed by one of the world's render
// instances. Its position follows its render instance's translation (the grid's dynamic elements copy it every
// frame, Grid.cpp).
class WCollisionObject {
public:
    Coord3 position;            // +0x00 the cylinder's foot
    float radius;               // +0x0c the cylinder's
    Coord4 halfExtents;         // +0x10 the box's; the cylinder is 2 * halfExtents.y tall
    uint8_t isCylinder;         // +0x20 1 a cylinder, 0 a box
    uint8_t unknown21;
    uint8_t flags;              // +0x22 CollisionObjectFlags
    uint8_t unknown23;
    uint16_t renderIndex;       // +0x24 its render instance in fgWorld->renderInstances
    uint8_t faceType;           // +0x26
    uint8_t faceSubType;        // +0x27
    uint8_t unknown28[8];

    void MakeMatrix(MATRIX4 *out, bool translate);      // 0x000be6f0
};
static_assert(sizeof(WCollisionObject) == 0x30, "a collision object is 48 bytes");
static_assert(offsetof(WCollisionObject, isCylinder) == 0x20 && offsetof(WCollisionObject, renderIndex) == 0x24 &&
              offsetof(WCollisionObject, faceType) == 0x26, "collision object layout");

// ---- what the queries answer

enum WorldHitType : uint8_t {
    kHitNone = 0,
    kHitWorld = 1,              // a face of the world
    kHitBarrier = 2,            // a barrier (CheckHitWindow then looks for a window)
    kHitObject = 3,             // a collision object
};

// WCollisionMgr::WorldCollisionInfo (the PS2 build's symbol): one hit (0x60 bytes). FUN_0001d9f0 constructs it
// (point (0,0,0,1), the rest zero, except +0x20..+0x3f, which the Xbox build copies from its own uninitialised
// stack, and the normal, which it leaves). A barrier hit copies its BarrierListEntry over +0x20..+0x47: the
// barrier's two ends in the world's frame (the fourth words its tag and its inverse length), its instance and its
// index, which is also the id of the window group CheckHitWindow looks for.
struct WorldCollisionInfo {
    Coord4 point;               // +0x00 where the hit is
    Coord4 normal;              // +0x10
    Coord4 segmentStart;        // +0x20 a barrier's first end
    Coord4 segmentEnd;          // +0x30 its second end
    WCollisionInstance *instance;   // +0x40 the barrier's instance
    uint32_t groupId;           // +0x44 the barrier's index: its window group
    WCollisionObject *object;   // +0x48 the object hit
    uint32_t unknown4c;
    uint8_t faceType;           // +0x50 (0x70 once a window broke)
    uint8_t faceSubType;        // +0x51
    uint8_t flag52;             // +0x52 the instance's kInstanceFlag02, or the object's kObjectFlag01
    uint8_t hitType;            // +0x53 WorldHitType
    uint16_t unknown54;
    uint16_t unknown56;
    WCollisionInstance *faceInstance;   // +0x58 the face's instance (a barrier's, or WWorldPos::instance)
    uint32_t unknown5c;
};
static_assert(sizeof(WorldCollisionInfo) == 0x60, "WorldCollisionInfo is 96 bytes");

// ---- the collision system's std::vectors (Dinkumware's, as the game compiled them)

template <class T>
struct ColVector : GameVector<T> {
    uint32_t Size() const { return this->first == NULL ? 0 : uint32_t(this->last - this->first); }
    uint32_t Capacity() const { return this->first == NULL ? 0 : uint32_t(this->end - this->first); }
};

// The library code shared by every vector of pointers (the linker folded the copies together).
struct PointerVector : ColVector<void *> {
    void** Ucopy(void *const *first, void *const *last, void **dest);           // 0x000c1230: answers the end
    void** Ufill(void **first, uint32_t count, void *const *value);            // 0x000c1290: answers the end
};

// The strips of one instance near a point (new'd, 0x14 bytes): the vector, then the instance's article when they
// were listed.
struct StripList : ColVector<const CollisionStrip *> {
    CollisionArticle *article;  // +0x10

    void PushBack(const CollisionStrip *const *strip);  // inlined in the game
    void InsertN(const CollisionStrip **where, uint32_t count, const CollisionStrip *const *value);   // 0x000c2c70
    void Xlen();                // std::length_error("vector<T> too long")                     0x000c1eb0
};
static_assert(sizeof(StripList) == 0x14, "a strip list is 20 bytes");

struct InstanceListEntry {
    WCollisionInstance *instance;
    StripList *strips;          // NULL: every strip of the instance
};
static_assert(sizeof(InstanceListEntry) == 8, "an instance list entry is 8 bytes");

struct InstanceList : ColVector<InstanceListEntry> {
    void PushBack(const InstanceListEntry *entry);                                          // 0x000c3180
    void InsertN(InstanceListEntry *where, uint32_t count, const InstanceListEntry *value); // 0x000c1f30
    InstanceListEntry* Ufill(InstanceListEntry *first, uint32_t count, const InstanceListEntry *value);   // 0x000c12c0
    void Reserve(uint32_t count);                                                           // 0x000bdf60
};

// A barrier near the query, carried into the world's frame unless its instance is tilted (then in the
// instance's): the barrier, its instance and its index in the instance's article.
struct BarrierListEntry {
    CollisionBarrier barrier;   // +0x00
    WCollisionInstance *instance;   // +0x20
    uint32_t index;             // +0x24
};
static_assert(sizeof(BarrierListEntry) == 0x28, "a barrier list entry is 40 bytes");

struct BarrierList : ColVector<BarrierListEntry> {
    void PushBack(const BarrierListEntry *entry);                                           // 0x000c30f0
    BarrierListEntry** Insert(BarrierListEntry **result, BarrierListEntry *where, const BarrierListEntry *value);   // 0x000c2b40
    void InsertN(BarrierListEntry *where, uint32_t count, const BarrierListEntry *value);   // 0x000c18c0
    BarrierListEntry* Ufill(BarrierListEntry *first, uint32_t count, const BarrierListEntry *value);   // 0x000c1260
    void Reserve(uint32_t count);                                                           // 0x000bde10
    void Tidy();                                                                            // 0x000bd9a0
    BarrierListEntry* Ucopy(BarrierListEntry *first, BarrierListEntry *last, BarrierListEntry *dest);   // 0x000bd970
};

struct ObjectList : ColVector<WCollisionObject *> {
    void PushBack(WCollisionObject *const *object);                                         // inlined in the game
    void Reserve(uint32_t count);                                                           // 0x000c2970
    void InsertN(WCollisionObject **where, uint32_t count, WCollisionObject *const *value); // 0x000c1bf0
};

// ---- the grid's cells (Grid.h has the grid)

// What a grid entry is
enum WGridElementType : uint32_t {
    kGridInstance = 0,          // a collision instance
    kGridObject = 2,            // a collision object
};

// The cells a search found (cell numbers)
struct WGridCellList : ColVector<uint32_t> {
    void InsertN(uint32_t *where, uint32_t count, const uint32_t *value);    // 0x000c5be0
    void PushBack(const uint32_t *value);                                    // 0x000c5ea0
    void Reserve(uint32_t count);                                            // 0x000c27a0
};

// A moving thing in a cell's list (std::list<...>'s node and the list, made with new)
struct WGridDynamicEntry {
    uint16_t index;             // the instance's or object's number
    uint16_t unknown02;         // (the original leaves its stack's bytes here)
    uint32_t type;              // WGridElementType
};

struct WGridDynamicNode {
    WGridDynamicNode *next;     // +0x00
    WGridDynamicNode *prev;     // +0x04
    WGridDynamicEntry value;    // +0x08
};
static_assert(sizeof(WGridDynamicNode) == 0x10, "a cell list's node is 0x10 bytes");

struct WGridDynamicList {
    uint32_t allocator;
    WGridDynamicNode *head;     // +0x04 the sentinel
    uint32_t size;

    WGridDynamicNode** Erase(WGridDynamicNode **result, WGridDynamicNode *first, WGridDynamicNode *last);   // 0x000c5830
    WGridDynamicNode* BuyNode(WGridDynamicNode *next, WGridDynamicNode *prev, const WGridDynamicEntry *value);   // 0x000c5880
    WGridDynamicNode* BuyHead();                                             // 0x000c5970
    void Destruct();                                                         // 0x000c59b0
    void IncreaseSize(uint32_t count);                                       // 0x000c5a80
};
static_assert(sizeof(WGridDynamicList) == 0xc, "a cell list is 0xc bytes");

// A cell's node (the 'cn  ' record's data): the moving things' list, then the static things by type - their
// counts, and where each type's numbers start (in bytes after the 0x10-byte head)
struct WGridNode {
    WGridDynamicList *dynamic;  // +0x00 NULL until something moves in
    uint8_t staticCount[4];     // +0x04 by WGridElementType
    uint16_t staticOffset[4];   // +0x08

    const uint16_t *StaticIndices(uint32_t type) const {
        return reinterpret_cast<const uint16_t *>(reinterpret_cast<const uint8_t *>(this + 1) + staticOffset[type]);
    }

    void RemoveDynamic(uint32_t index, uint32_t type);                       // 0x000c5900
    void AddDynamic(uint16_t index, uint32_t type);                          // 0x000c5f10
};
static_assert(sizeof(WGridNode) == 0x10, "a grid node's head is 0x10 bytes");

// Steps through one type of element listed in a grid cell: the cell's own (static) indices, then the dynamic ones.
struct GridCellIterator {
    uint32_t type;              // +0x00 WGridElementType
    WGridNode *cell;            // +0x04
    int remaining;              // +0x08 of the cell's own
    const uint16_t *current;    // +0x0c
    uint8_t active;             // +0x10
    uint8_t inDynamic;          // +0x11
    uint8_t unknown12[2];
    WGridDynamicNode *dynamic;  // +0x14 the next dynamic node to look at

    GridCellIterator* Construct(WGridNode *cell, uint32_t type);      // 0x000bfee0
    const uint16_t* Next();     // the element, NULL at the end         0x000bff50
};
static_assert(sizeof(GridCellIterator) == 0x18, "a grid cell iterator is 24 bytes");

// ---- the geometry helpers on the strips' triangles (CollisionInstance.cpp)

// Point-in-triangle tests in the ground plane (x, z) against three strip vertices: the signed areas of the point
// with each edge, all of one sign.
bool PointInTriangle2D(const Coord3 *point, const StripVertex *triangle);            // 0x000bebd0: either winding
bool PointInTriangle2DClockwise(const Coord3 *point, const StripVertex *triangle);   // 0x000becb0: all areas <= 0
bool PointInTriangle2DCounter(const Coord3 *point, const StripVertex *triangle);     // 0x000bed40: all areas >= 0

#endif // DRIVING_WORLD_COLLISIONTYPES_H_
