#ifndef DRIVING_WORLD_VISCURTAIN_H_
#define DRIVING_WORLD_VISCURTAIN_H_

// ---------------------------------------------------------------------------------------------------------------
// The visibility curtains: vertical walls in the track that hide what is behind them. Each frame the renderer
// (WRender, world/Render.cpp) clears the active list and adds the curtains of the scene tree nodes it finds visible;
// a curtain is added only when the eye is on its front side, as four planes - the wall itself, the two from the
// eye through its ends, and the one through its far end - and a sphere is hidden when it is behind all four of one
// curtain's planes. See VisCurtain.cpp.
// ---------------------------------------------------------------------------------------------------------------

#include <stddef.h>
#include <stdint.h>

#include "../autogenerated_layouts.h"     // MATRIX4
#include "../data/CoordConvert.h"

// A curtain (0x20 bytes): the wall's two bottom-to-top ends; start.w is half its length in the ground plane.
class WVisCurtain {
public:
    Coord4 start;                       // +0x00
    Coord4 end;                         // +0x10

    WVisCurtain* Construct(const Coord4 *from, const Coord4 *to);            // 0x000d0ff0
};
static_assert(sizeof(WVisCurtain) == 0x20, "a curtain is 32 bytes");

// The active curtains' planes, one MATRIX4 each: column i is plane i's normal (rows 0-2) and its distance from the
// origin along it (row 3), so that VU0_MATRIX4_vect3multsub answers a point's distance from each of the four.
constexpr int kMaxActiveCurtains = 63;

void InitActiveCurtainList();                                               // 0x000d0d50
// Adds the curtain's planes if the eye is in front of its wall (the name is ours; Ghidra: FUN_000d0d60).
void AddActiveCurtain(const WVisCurtain *curtain, const Coord4 *eye);       // 0x000d0d60
// False when the sphere (w its radius) is behind every plane of an active curtain - past the far plane by more
// than `farMargin`.
bool IsVisibleAgainstCurtains(const Coord4 *sphere, float farMargin);       // 0x000d0f50

#endif // DRIVING_WORLD_VISCURTAIN_H_
