#pragma once

#include <stdint.h>

#include "../autogenerated_layouts.h"
#include "../data/CoordConvert.h"

// ---------------------------------------------------------------------------------------------------------------
// The collision system's geometry (Ghidra: WWorldMath, static functions, 0x000d2860..0x000d2f10, and
// FasterSegmentIntersect linked before it): segments against segments in the ground plane (x and z), a segment
// against a circle, nearest points on lines, a plane's height, a segment through a plane, and a segment's frame.
// A segment is two consecutive points, seg[0] to seg[1].
// ---------------------------------------------------------------------------------------------------------------

// Whether segments a and b cross in x/z, and where along a (y interpolated) if `hit` is not NULL; the
// parameters on both must lie in [0, 1] (0x000d1060, GetOBBObjectIntersection's).
bool FasterSegmentIntersect(const Coord4 *a, const Coord4 *b, Coord4 *hit);

class WWorldMath {
public:
    // The same with a tolerance of 0.0001 on the parameters (scaled by the denominator) and hit's w set to 1
    // (0x000d2860, the barrier queries').
    static bool SegmentIntersect(const Coord4 *a, const Coord4 *b, Coord4 *hit);
    // Where the segment (x1, z1)-(x2, z2) meets the circle of the given radius about (centreX, centreZ): both
    // parameters 0 when the segment is inside, else the two roots, true when either is in [0, 1] (0x000d29e0).
    static bool IntersectCircle(float x1, float z1, float x2, float z2, float centreX, float centreZ, float radius,
                                float *t1, float *t2);
    // The point of the line through seg in x/z nearest `point`, y 0 (0x000d2b70).
    static void NearestPointLine2D(const Coord4 *point, const Coord4 *seg, Coord4 *nearest);
    // The height at point's x and z of the plane through pointOnPlane with the given normal; pointOnPlane's own
    // height when the normal is horizontal (0x000d2be0). Unrounded.
    static double GetPlaneY(const Coord3 *normal, const Coord3 *pointOnPlane, const Coord3 *point);
    // Where the segment from-to passes through the plane through pointOnPlane with the given normal: the point (x,
    // y and z set) and the parameter, true when that is in [0, 1] (0x000d2c20).
    static bool IntersectSegPlane(const Coord4 *from, const Coord4 *to, const Coord3 *pointOnPlane,
                                  const Coord4 *normal, Coord4 *hit, float *t);
    // The point of the line through seg nearest `point` (0x000d2cf0).
    static void NearestPointLine3D(const Coord4 *point, const Coord4 *seg, Coord4 *nearest);
    // A frame along the segment from-to (0x000d2d70): row 1 the unit vector from - to, rows 0 and 2 perpendicular
    // to it, row 3 `from` (w 1). False, the matrix untouched, when the points are within 0.0001 in each coordinate.
    static bool MakeSegSpaceMatrix(const Coord4 *from, const Coord4 *to, MATRIX4 *matrix);
};
