#pragma once

#include <stddef.h>
#include <stdint.h>

#include "CollisionTypes.h"
#include "../autogenerated_layouts.h"
#include "../data/CoordConvert.h"

// ---------------------------------------------------------------------------------------------------------------
// A place on the world's collision surface (Ghidra: WWorldPos, 0x40 bytes): the triangle of track geometry under
// a point, found among the collision instances near it and kept, with the instance it came from, so that the next
// query at nearly the same place can keep it. The cars' wheels, the AI, the cameras, tyre tracks, scorch marks,
// grenades and missiles each hold one, and ask it for the ground height under them.
// ---------------------------------------------------------------------------------------------------------------

class WWorldPos {
public:
    // The face as WCollisionMgr::FindFaceInCInst hands it back, in the world's frame: corner[2].tag its tag (type
    // and sub-type cleared before each search, type 1 for MakeFaceAtPoint's flat face), corner[1].flags its strip's
    // flags
    StripTriangle face;         // +0x00
    uint8_t valid;              // +0x30 a face was found (or made)
    uint8_t unknown31[3];
    WCollisionInstance *instance;   // +0x34 the instance the face belongs to
    CollisionArticle *article;  // +0x38 the instance's article when the face was found: a changed one makes it stale
    int32_t lastQueryStep;      // +0x3c the simulation step of the last search

    WWorldPos* Construct();                                         // 0x000d2fd0
    // A flat face 0.2 across at the point (0x000d2f10, RigidBody::TempGetHeightInformation's)
    void MakeFaceAtPoint(const Coord3 *point);
    // The face's plane's height under the point; 0 without a face (0x000d2f90). The flag is not read. Unrounded.
    double HeightAtPoint(const Coord3 *point, bool unusedFlag);
    // The face under the point nearest it among the instances; true when any instance had a face there, whether or
    // not it became the nearest (0x000d3050)
    bool FindClosestFace(const InstanceList *instances, const Coord3 *point);
    // The same along the segment from-to, in the segment's frame; always false - callers read `valid`
    // (0x000d3110, GetWorldNormal's and CheckHitWorld's)
    bool FindClosestFace(const InstanceList *instances, const Coord4 *from, const Coord4 *to);
    // The face under the point, among the instances near it (0x000d31f0). With keepCurrent, a face still current
    // (its instance unchanged) that still holds the point is kept and the answer is false; otherwise the search is
    // made and the answer true.
    bool FindClosestFace(const Coord3 *point, bool keepCurrent);
    // The ground normal: the face's, w 0, or straight up without a face. The second argument is not read.
    // (FUN_000a5080, the scorch marks'; the name is ours. The linker placed it among the renderer's code.)
    void GetNormal(Coord4 *normal, int unused);
};
static_assert(sizeof(WWorldPos) == 0x40, "WWorldPos is 0x40 bytes");
static_assert(offsetof(WWorldPos, valid) == 0x30 && offsetof(WWorldPos, article) == 0x38, "WWorldPos layout");
